/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../../../common.js"
  

  export interface IL2MessageManagerInterface extends Interface {
    getFunction(nameOrSignature: "anchorL1L2MessageHashes"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "RollingHashUpdated" | "ServiceVersionMigrated"): EventFragment;

    encodeFunctionData(functionFragment: 'anchorL1L2MessageHashes', values: [BytesLike[], BigNumberish, BigNumberish, BytesLike]): string;

    decodeFunctionResult(functionFragment: 'anchorL1L2MessageHashes', data: BytesLike): Result;
  }

  
    export namespace RollingHashUpdatedEvent {
      export type InputTuple = [messageNumber: BigNumberish, rollingHash: BytesLike];
      export type OutputTuple = [messageNumber: bigint, rollingHash: string];
      export interface OutputObject {messageNumber: bigint, rollingHash: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ServiceVersionMigratedEvent {
      export type InputTuple = [version: BigNumberish];
      export type OutputTuple = [version: bigint];
      export interface OutputObject {version: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface IL2MessageManager extends BaseContract {
    
    connect(runner?: ContractRunner | null): IL2MessageManager;
    waitForDeployment(): Promise<this>;

    interface: IL2MessageManagerInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    anchorL1L2MessageHashes: TypedContractMethod<
      [_messageHashes: BytesLike[], _startingMessageNumber: BigNumberish, _finalMessageNumber: BigNumberish, _finalRollingHash: BytesLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'anchorL1L2MessageHashes'): TypedContractMethod<
      [_messageHashes: BytesLike[], _startingMessageNumber: BigNumberish, _finalMessageNumber: BigNumberish, _finalRollingHash: BytesLike, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'RollingHashUpdated'): TypedContractEvent<RollingHashUpdatedEvent.InputTuple, RollingHashUpdatedEvent.OutputTuple, RollingHashUpdatedEvent.OutputObject>;
getEvent(key: 'ServiceVersionMigrated'): TypedContractEvent<ServiceVersionMigratedEvent.InputTuple, ServiceVersionMigratedEvent.OutputTuple, ServiceVersionMigratedEvent.OutputObject>;

    filters: {
      
      'RollingHashUpdated(uint256,bytes32)': TypedContractEvent<RollingHashUpdatedEvent.InputTuple, RollingHashUpdatedEvent.OutputTuple, RollingHashUpdatedEvent.OutputObject>;
      RollingHashUpdated: TypedContractEvent<RollingHashUpdatedEvent.InputTuple, RollingHashUpdatedEvent.OutputTuple, RollingHashUpdatedEvent.OutputObject>;
    

      'ServiceVersionMigrated(uint256)': TypedContractEvent<ServiceVersionMigratedEvent.InputTuple, ServiceVersionMigratedEvent.OutputTuple, ServiceVersionMigratedEvent.OutputObject>;
      ServiceVersionMigrated: TypedContractEvent<ServiceVersionMigratedEvent.InputTuple, ServiceVersionMigratedEvent.OutputTuple, ServiceVersionMigratedEvent.OutputObject>;
    
    };
  }