/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../../../common.js"
  
export declare namespace IPauseManager {
      
    export type PauseTypeRoleStruct = {pauseType: BigNumberish, role: BytesLike}

    export type PauseTypeRoleStructOutput = [pauseType: bigint, role: string] & {pauseType: bigint, role: string }
  
    }

  export interface TestL2MessageManagerInterface extends Interface {
    getFunction(nameOrSignature: "COOLDOWN_DURATION" | "DEFAULT_ADMIN_ROLE" | "INBOX_STATUS_CLAIMED" | "INBOX_STATUS_RECEIVED" | "INBOX_STATUS_UNKNOWN" | "L1_L2_MESSAGE_SETTER_ROLE" | "PAUSE_ALL_ROLE" | "PAUSE_DURATION" | "PAUSE_L1_L2_ROLE" | "PAUSE_L2_L1_ROLE" | "SECURITY_COUNCIL_ROLE" | "UNPAUSE_ALL_ROLE" | "UNPAUSE_L1_L2_ROLE" | "UNPAUSE_L2_L1_ROLE" | "anchorL1L2MessageHashes" | "getRoleAdmin" | "grantRole" | "hasRole" | "inboxL1L2MessageStatus" | "initialize" | "initializePauseTypesAndPermissions" | "isPaused" | "l1RollingHashes" | "lastAnchoredL1MessageNumber" | "nonSecurityCouncilCooldownEnd" | "pauseByType" | "pauseTypeExpiryTimestamps" | "renounceRole" | "resetNonSecurityCouncilCooldownEnd" | "revokeRole" | "setLastAnchoredL1MessageNumber" | "supportsInterface" | "unPauseByExpiredType" | "unPauseByType" | "updateL1L2MessageStatusToClaimed" | "updatePauseTypeRole" | "updateUnpauseTypeRole"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "Initialized" | "L1L2MessageHashesAddedToInbox" | "MinimumFeeChanged" | "NonSecurityCouncilCooldownEndReset" | "PauseTypeRoleSet" | "PauseTypeRoleUpdated" | "Paused" | "PausedIndefinitely" | "RoleAdminChanged" | "RoleGranted" | "RoleRevoked" | "RollingHashUpdated" | "ServiceVersionMigrated" | "UnPauseTypeRoleSet" | "UnPauseTypeRoleUpdated" | "UnPaused" | "UnPausedDueToExpiry"): EventFragment;

    encodeFunctionData(functionFragment: 'COOLDOWN_DURATION', values?: undefined): string;
encodeFunctionData(functionFragment: 'DEFAULT_ADMIN_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'INBOX_STATUS_CLAIMED', values?: undefined): string;
encodeFunctionData(functionFragment: 'INBOX_STATUS_RECEIVED', values?: undefined): string;
encodeFunctionData(functionFragment: 'INBOX_STATUS_UNKNOWN', values?: undefined): string;
encodeFunctionData(functionFragment: 'L1_L2_MESSAGE_SETTER_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'PAUSE_ALL_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'PAUSE_DURATION', values?: undefined): string;
encodeFunctionData(functionFragment: 'PAUSE_L1_L2_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'PAUSE_L2_L1_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'SECURITY_COUNCIL_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'UNPAUSE_ALL_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'UNPAUSE_L1_L2_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'UNPAUSE_L2_L1_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'anchorL1L2MessageHashes', values: [BytesLike[], BigNumberish, BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'getRoleAdmin', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'grantRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'hasRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'inboxL1L2MessageStatus', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'initialize', values: [AddressLike, AddressLike, IPauseManager.PauseTypeRoleStruct[], IPauseManager.PauseTypeRoleStruct[]]): string;
encodeFunctionData(functionFragment: 'initializePauseTypesAndPermissions', values: [IPauseManager.PauseTypeRoleStruct[], IPauseManager.PauseTypeRoleStruct[]]): string;
encodeFunctionData(functionFragment: 'isPaused', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'l1RollingHashes', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'lastAnchoredL1MessageNumber', values?: undefined): string;
encodeFunctionData(functionFragment: 'nonSecurityCouncilCooldownEnd', values?: undefined): string;
encodeFunctionData(functionFragment: 'pauseByType', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'pauseTypeExpiryTimestamps', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'renounceRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'resetNonSecurityCouncilCooldownEnd', values?: undefined): string;
encodeFunctionData(functionFragment: 'revokeRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'setLastAnchoredL1MessageNumber', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'supportsInterface', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'unPauseByExpiredType', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'unPauseByType', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'updateL1L2MessageStatusToClaimed', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'updatePauseTypeRole', values: [BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'updateUnpauseTypeRole', values: [BigNumberish, BytesLike]): string;

    decodeFunctionResult(functionFragment: 'COOLDOWN_DURATION', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'DEFAULT_ADMIN_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'INBOX_STATUS_CLAIMED', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'INBOX_STATUS_RECEIVED', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'INBOX_STATUS_UNKNOWN', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'L1_L2_MESSAGE_SETTER_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'PAUSE_ALL_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'PAUSE_DURATION', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'PAUSE_L1_L2_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'PAUSE_L2_L1_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'SECURITY_COUNCIL_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'UNPAUSE_ALL_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'UNPAUSE_L1_L2_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'UNPAUSE_L2_L1_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'anchorL1L2MessageHashes', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getRoleAdmin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'grantRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hasRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'inboxL1L2MessageStatus', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'initialize', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'initializePauseTypesAndPermissions', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isPaused', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'l1RollingHashes', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'lastAnchoredL1MessageNumber', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'nonSecurityCouncilCooldownEnd', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pauseByType', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pauseTypeExpiryTimestamps', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'resetNonSecurityCouncilCooldownEnd', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'revokeRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setLastAnchoredL1MessageNumber', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'supportsInterface', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'unPauseByExpiredType', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'unPauseByType', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateL1L2MessageStatusToClaimed', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updatePauseTypeRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateUnpauseTypeRole', data: BytesLike): Result;
  }

  
    export namespace InitializedEvent {
      export type InputTuple = [version: BigNumberish];
      export type OutputTuple = [version: bigint];
      export interface OutputObject {version: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace L1L2MessageHashesAddedToInboxEvent {
      export type InputTuple = [messageHashes: BytesLike[]];
      export type OutputTuple = [messageHashes: string[]];
      export interface OutputObject {messageHashes: string[] };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace MinimumFeeChangedEvent {
      export type InputTuple = [previousMinimumFee: BigNumberish, newMinimumFee: BigNumberish, calledBy: AddressLike];
      export type OutputTuple = [previousMinimumFee: bigint, newMinimumFee: bigint, calledBy: string];
      export interface OutputObject {previousMinimumFee: bigint, newMinimumFee: bigint, calledBy: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace NonSecurityCouncilCooldownEndResetEvent {
      export type InputTuple = [];
      export type OutputTuple = [];
      export interface OutputObject {};
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PauseTypeRoleSetEvent {
      export type InputTuple = [pauseType: BigNumberish, role: BytesLike];
      export type OutputTuple = [pauseType: bigint, role: string];
      export interface OutputObject {pauseType: bigint, role: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PauseTypeRoleUpdatedEvent {
      export type InputTuple = [pauseType: BigNumberish, role: BytesLike, previousRole: BytesLike];
      export type OutputTuple = [pauseType: bigint, role: string, previousRole: string];
      export interface OutputObject {pauseType: bigint, role: string, previousRole: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PausedEvent {
      export type InputTuple = [messageSender: AddressLike, pauseType: BigNumberish];
      export type OutputTuple = [messageSender: string, pauseType: bigint];
      export interface OutputObject {messageSender: string, pauseType: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PausedIndefinitelyEvent {
      export type InputTuple = [messageSender: AddressLike, pauseType: BigNumberish];
      export type OutputTuple = [messageSender: string, pauseType: bigint];
      export interface OutputObject {messageSender: string, pauseType: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleAdminChangedEvent {
      export type InputTuple = [role: BytesLike, previousAdminRole: BytesLike, newAdminRole: BytesLike];
      export type OutputTuple = [role: string, previousAdminRole: string, newAdminRole: string];
      export interface OutputObject {role: string, previousAdminRole: string, newAdminRole: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleGrantedEvent {
      export type InputTuple = [role: BytesLike, account: AddressLike, sender: AddressLike];
      export type OutputTuple = [role: string, account: string, sender: string];
      export interface OutputObject {role: string, account: string, sender: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleRevokedEvent {
      export type InputTuple = [role: BytesLike, account: AddressLike, sender: AddressLike];
      export type OutputTuple = [role: string, account: string, sender: string];
      export interface OutputObject {role: string, account: string, sender: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RollingHashUpdatedEvent {
      export type InputTuple = [messageNumber: BigNumberish, rollingHash: BytesLike];
      export type OutputTuple = [messageNumber: bigint, rollingHash: string];
      export interface OutputObject {messageNumber: bigint, rollingHash: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ServiceVersionMigratedEvent {
      export type InputTuple = [version: BigNumberish];
      export type OutputTuple = [version: bigint];
      export interface OutputObject {version: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace UnPauseTypeRoleSetEvent {
      export type InputTuple = [unPauseType: BigNumberish, role: BytesLike];
      export type OutputTuple = [unPauseType: bigint, role: string];
      export interface OutputObject {unPauseType: bigint, role: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace UnPauseTypeRoleUpdatedEvent {
      export type InputTuple = [unPauseType: BigNumberish, role: BytesLike, previousRole: BytesLike];
      export type OutputTuple = [unPauseType: bigint, role: string, previousRole: string];
      export interface OutputObject {unPauseType: bigint, role: string, previousRole: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace UnPausedEvent {
      export type InputTuple = [messageSender: AddressLike, pauseType: BigNumberish];
      export type OutputTuple = [messageSender: string, pauseType: bigint];
      export interface OutputObject {messageSender: string, pauseType: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace UnPausedDueToExpiryEvent {
      export type InputTuple = [pauseType: BigNumberish];
      export type OutputTuple = [pauseType: bigint];
      export interface OutputObject {pauseType: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface TestL2MessageManager extends BaseContract {
    
    connect(runner?: ContractRunner | null): TestL2MessageManager;
    waitForDeployment(): Promise<this>;

    interface: TestL2MessageManagerInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    COOLDOWN_DURATION: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    DEFAULT_ADMIN_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    INBOX_STATUS_CLAIMED: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    INBOX_STATUS_RECEIVED: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    INBOX_STATUS_UNKNOWN: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    L1_L2_MESSAGE_SETTER_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    PAUSE_ALL_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    PAUSE_DURATION: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    PAUSE_L1_L2_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    PAUSE_L2_L1_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    SECURITY_COUNCIL_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    UNPAUSE_ALL_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    UNPAUSE_L1_L2_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    UNPAUSE_L2_L1_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    anchorL1L2MessageHashes: TypedContractMethod<
      [_messageHashes: BytesLike[], _startingMessageNumber: BigNumberish, _finalMessageNumber: BigNumberish, _finalRollingHash: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    getRoleAdmin: TypedContractMethod<
      [role: BytesLike, ],
      [string],
      'view'
    >
    

    
    grantRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    hasRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    inboxL1L2MessageStatus: TypedContractMethod<
      [messageHash: BytesLike, ],
      [bigint],
      'view'
    >
    

    
    initialize: TypedContractMethod<
      [_pauserManager: AddressLike, _l1l2MessageSetter: AddressLike, _pauseTypeRoles: IPauseManager.PauseTypeRoleStruct[], _unpauseTypeRoles: IPauseManager.PauseTypeRoleStruct[], ],
      [void],
      'nonpayable'
    >
    

    
    initializePauseTypesAndPermissions: TypedContractMethod<
      [_pauseTypeRoles: IPauseManager.PauseTypeRoleStruct[], _unpauseTypeRoles: IPauseManager.PauseTypeRoleStruct[], ],
      [void],
      'nonpayable'
    >
    

    
    isPaused: TypedContractMethod<
      [_pauseType: BigNumberish, ],
      [boolean],
      'view'
    >
    

    
    l1RollingHashes: TypedContractMethod<
      [messageNumber: BigNumberish, ],
      [string],
      'view'
    >
    

    
    lastAnchoredL1MessageNumber: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    nonSecurityCouncilCooldownEnd: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    pauseByType: TypedContractMethod<
      [_pauseType: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    pauseTypeExpiryTimestamps: TypedContractMethod<
      [pauseType: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    renounceRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    resetNonSecurityCouncilCooldownEnd: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    revokeRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setLastAnchoredL1MessageNumber: TypedContractMethod<
      [_messageNumber: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    supportsInterface: TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    unPauseByExpiredType: TypedContractMethod<
      [_pauseType: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    unPauseByType: TypedContractMethod<
      [_pauseType: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    updateL1L2MessageStatusToClaimed: TypedContractMethod<
      [_messageHash: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    updatePauseTypeRole: TypedContractMethod<
      [_pauseType: BigNumberish, _newRole: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    updateUnpauseTypeRole: TypedContractMethod<
      [_pauseType: BigNumberish, _newRole: BytesLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'COOLDOWN_DURATION'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'DEFAULT_ADMIN_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'INBOX_STATUS_CLAIMED'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'INBOX_STATUS_RECEIVED'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'INBOX_STATUS_UNKNOWN'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'L1_L2_MESSAGE_SETTER_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'PAUSE_ALL_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'PAUSE_DURATION'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'PAUSE_L1_L2_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'PAUSE_L2_L1_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'SECURITY_COUNCIL_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'UNPAUSE_ALL_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'UNPAUSE_L1_L2_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'UNPAUSE_L2_L1_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'anchorL1L2MessageHashes'): TypedContractMethod<
      [_messageHashes: BytesLike[], _startingMessageNumber: BigNumberish, _finalMessageNumber: BigNumberish, _finalRollingHash: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getRoleAdmin'): TypedContractMethod<
      [role: BytesLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'grantRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'hasRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'inboxL1L2MessageStatus'): TypedContractMethod<
      [messageHash: BytesLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'initialize'): TypedContractMethod<
      [_pauserManager: AddressLike, _l1l2MessageSetter: AddressLike, _pauseTypeRoles: IPauseManager.PauseTypeRoleStruct[], _unpauseTypeRoles: IPauseManager.PauseTypeRoleStruct[], ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'initializePauseTypesAndPermissions'): TypedContractMethod<
      [_pauseTypeRoles: IPauseManager.PauseTypeRoleStruct[], _unpauseTypeRoles: IPauseManager.PauseTypeRoleStruct[], ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'isPaused'): TypedContractMethod<
      [_pauseType: BigNumberish, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'l1RollingHashes'): TypedContractMethod<
      [messageNumber: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'lastAnchoredL1MessageNumber'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'nonSecurityCouncilCooldownEnd'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'pauseByType'): TypedContractMethod<
      [_pauseType: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'pauseTypeExpiryTimestamps'): TypedContractMethod<
      [pauseType: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'renounceRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'resetNonSecurityCouncilCooldownEnd'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'revokeRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setLastAnchoredL1MessageNumber'): TypedContractMethod<
      [_messageNumber: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'supportsInterface'): TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'unPauseByExpiredType'): TypedContractMethod<
      [_pauseType: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'unPauseByType'): TypedContractMethod<
      [_pauseType: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updateL1L2MessageStatusToClaimed'): TypedContractMethod<
      [_messageHash: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updatePauseTypeRole'): TypedContractMethod<
      [_pauseType: BigNumberish, _newRole: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updateUnpauseTypeRole'): TypedContractMethod<
      [_pauseType: BigNumberish, _newRole: BytesLike, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'Initialized'): TypedContractEvent<InitializedEvent.InputTuple, InitializedEvent.OutputTuple, InitializedEvent.OutputObject>;
getEvent(key: 'L1L2MessageHashesAddedToInbox'): TypedContractEvent<L1L2MessageHashesAddedToInboxEvent.InputTuple, L1L2MessageHashesAddedToInboxEvent.OutputTuple, L1L2MessageHashesAddedToInboxEvent.OutputObject>;
getEvent(key: 'MinimumFeeChanged'): TypedContractEvent<MinimumFeeChangedEvent.InputTuple, MinimumFeeChangedEvent.OutputTuple, MinimumFeeChangedEvent.OutputObject>;
getEvent(key: 'NonSecurityCouncilCooldownEndReset'): TypedContractEvent<NonSecurityCouncilCooldownEndResetEvent.InputTuple, NonSecurityCouncilCooldownEndResetEvent.OutputTuple, NonSecurityCouncilCooldownEndResetEvent.OutputObject>;
getEvent(key: 'PauseTypeRoleSet'): TypedContractEvent<PauseTypeRoleSetEvent.InputTuple, PauseTypeRoleSetEvent.OutputTuple, PauseTypeRoleSetEvent.OutputObject>;
getEvent(key: 'PauseTypeRoleUpdated'): TypedContractEvent<PauseTypeRoleUpdatedEvent.InputTuple, PauseTypeRoleUpdatedEvent.OutputTuple, PauseTypeRoleUpdatedEvent.OutputObject>;
getEvent(key: 'Paused'): TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
getEvent(key: 'PausedIndefinitely'): TypedContractEvent<PausedIndefinitelyEvent.InputTuple, PausedIndefinitelyEvent.OutputTuple, PausedIndefinitelyEvent.OutputObject>;
getEvent(key: 'RoleAdminChanged'): TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
getEvent(key: 'RoleGranted'): TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
getEvent(key: 'RoleRevoked'): TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
getEvent(key: 'RollingHashUpdated'): TypedContractEvent<RollingHashUpdatedEvent.InputTuple, RollingHashUpdatedEvent.OutputTuple, RollingHashUpdatedEvent.OutputObject>;
getEvent(key: 'ServiceVersionMigrated'): TypedContractEvent<ServiceVersionMigratedEvent.InputTuple, ServiceVersionMigratedEvent.OutputTuple, ServiceVersionMigratedEvent.OutputObject>;
getEvent(key: 'UnPauseTypeRoleSet'): TypedContractEvent<UnPauseTypeRoleSetEvent.InputTuple, UnPauseTypeRoleSetEvent.OutputTuple, UnPauseTypeRoleSetEvent.OutputObject>;
getEvent(key: 'UnPauseTypeRoleUpdated'): TypedContractEvent<UnPauseTypeRoleUpdatedEvent.InputTuple, UnPauseTypeRoleUpdatedEvent.OutputTuple, UnPauseTypeRoleUpdatedEvent.OutputObject>;
getEvent(key: 'UnPaused'): TypedContractEvent<UnPausedEvent.InputTuple, UnPausedEvent.OutputTuple, UnPausedEvent.OutputObject>;
getEvent(key: 'UnPausedDueToExpiry'): TypedContractEvent<UnPausedDueToExpiryEvent.InputTuple, UnPausedDueToExpiryEvent.OutputTuple, UnPausedDueToExpiryEvent.OutputObject>;

    filters: {
      
      'Initialized(uint8)': TypedContractEvent<InitializedEvent.InputTuple, InitializedEvent.OutputTuple, InitializedEvent.OutputObject>;
      Initialized: TypedContractEvent<InitializedEvent.InputTuple, InitializedEvent.OutputTuple, InitializedEvent.OutputObject>;
    

      'L1L2MessageHashesAddedToInbox(bytes32[])': TypedContractEvent<L1L2MessageHashesAddedToInboxEvent.InputTuple, L1L2MessageHashesAddedToInboxEvent.OutputTuple, L1L2MessageHashesAddedToInboxEvent.OutputObject>;
      L1L2MessageHashesAddedToInbox: TypedContractEvent<L1L2MessageHashesAddedToInboxEvent.InputTuple, L1L2MessageHashesAddedToInboxEvent.OutputTuple, L1L2MessageHashesAddedToInboxEvent.OutputObject>;
    

      'MinimumFeeChanged(uint256,uint256,address)': TypedContractEvent<MinimumFeeChangedEvent.InputTuple, MinimumFeeChangedEvent.OutputTuple, MinimumFeeChangedEvent.OutputObject>;
      MinimumFeeChanged: TypedContractEvent<MinimumFeeChangedEvent.InputTuple, MinimumFeeChangedEvent.OutputTuple, MinimumFeeChangedEvent.OutputObject>;
    

      'NonSecurityCouncilCooldownEndReset()': TypedContractEvent<NonSecurityCouncilCooldownEndResetEvent.InputTuple, NonSecurityCouncilCooldownEndResetEvent.OutputTuple, NonSecurityCouncilCooldownEndResetEvent.OutputObject>;
      NonSecurityCouncilCooldownEndReset: TypedContractEvent<NonSecurityCouncilCooldownEndResetEvent.InputTuple, NonSecurityCouncilCooldownEndResetEvent.OutputTuple, NonSecurityCouncilCooldownEndResetEvent.OutputObject>;
    

      'PauseTypeRoleSet(uint8,bytes32)': TypedContractEvent<PauseTypeRoleSetEvent.InputTuple, PauseTypeRoleSetEvent.OutputTuple, PauseTypeRoleSetEvent.OutputObject>;
      PauseTypeRoleSet: TypedContractEvent<PauseTypeRoleSetEvent.InputTuple, PauseTypeRoleSetEvent.OutputTuple, PauseTypeRoleSetEvent.OutputObject>;
    

      'PauseTypeRoleUpdated(uint8,bytes32,bytes32)': TypedContractEvent<PauseTypeRoleUpdatedEvent.InputTuple, PauseTypeRoleUpdatedEvent.OutputTuple, PauseTypeRoleUpdatedEvent.OutputObject>;
      PauseTypeRoleUpdated: TypedContractEvent<PauseTypeRoleUpdatedEvent.InputTuple, PauseTypeRoleUpdatedEvent.OutputTuple, PauseTypeRoleUpdatedEvent.OutputObject>;
    

      'Paused(address,uint8)': TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
      Paused: TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
    

      'PausedIndefinitely(address,uint8)': TypedContractEvent<PausedIndefinitelyEvent.InputTuple, PausedIndefinitelyEvent.OutputTuple, PausedIndefinitelyEvent.OutputObject>;
      PausedIndefinitely: TypedContractEvent<PausedIndefinitelyEvent.InputTuple, PausedIndefinitelyEvent.OutputTuple, PausedIndefinitelyEvent.OutputObject>;
    

      'RoleAdminChanged(bytes32,bytes32,bytes32)': TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
      RoleAdminChanged: TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
    

      'RoleGranted(bytes32,address,address)': TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
      RoleGranted: TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
    

      'RoleRevoked(bytes32,address,address)': TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
      RoleRevoked: TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
    

      'RollingHashUpdated(uint256,bytes32)': TypedContractEvent<RollingHashUpdatedEvent.InputTuple, RollingHashUpdatedEvent.OutputTuple, RollingHashUpdatedEvent.OutputObject>;
      RollingHashUpdated: TypedContractEvent<RollingHashUpdatedEvent.InputTuple, RollingHashUpdatedEvent.OutputTuple, RollingHashUpdatedEvent.OutputObject>;
    

      'ServiceVersionMigrated(uint256)': TypedContractEvent<ServiceVersionMigratedEvent.InputTuple, ServiceVersionMigratedEvent.OutputTuple, ServiceVersionMigratedEvent.OutputObject>;
      ServiceVersionMigrated: TypedContractEvent<ServiceVersionMigratedEvent.InputTuple, ServiceVersionMigratedEvent.OutputTuple, ServiceVersionMigratedEvent.OutputObject>;
    

      'UnPauseTypeRoleSet(uint8,bytes32)': TypedContractEvent<UnPauseTypeRoleSetEvent.InputTuple, UnPauseTypeRoleSetEvent.OutputTuple, UnPauseTypeRoleSetEvent.OutputObject>;
      UnPauseTypeRoleSet: TypedContractEvent<UnPauseTypeRoleSetEvent.InputTuple, UnPauseTypeRoleSetEvent.OutputTuple, UnPauseTypeRoleSetEvent.OutputObject>;
    

      'UnPauseTypeRoleUpdated(uint8,bytes32,bytes32)': TypedContractEvent<UnPauseTypeRoleUpdatedEvent.InputTuple, UnPauseTypeRoleUpdatedEvent.OutputTuple, UnPauseTypeRoleUpdatedEvent.OutputObject>;
      UnPauseTypeRoleUpdated: TypedContractEvent<UnPauseTypeRoleUpdatedEvent.InputTuple, UnPauseTypeRoleUpdatedEvent.OutputTuple, UnPauseTypeRoleUpdatedEvent.OutputObject>;
    

      'UnPaused(address,uint8)': TypedContractEvent<UnPausedEvent.InputTuple, UnPausedEvent.OutputTuple, UnPausedEvent.OutputObject>;
      UnPaused: TypedContractEvent<UnPausedEvent.InputTuple, UnPausedEvent.OutputTuple, UnPausedEvent.OutputObject>;
    

      'UnPausedDueToExpiry(uint8)': TypedContractEvent<UnPausedDueToExpiryEvent.InputTuple, UnPausedDueToExpiryEvent.OutputTuple, UnPausedDueToExpiryEvent.OutputObject>;
      UnPausedDueToExpiry: TypedContractEvent<UnPausedDueToExpiryEvent.InputTuple, UnPausedDueToExpiryEvent.OutputTuple, UnPausedDueToExpiryEvent.OutputObject>;
    
    };
  }