export enum ProposalState {
  NEW = "NEW",
  ANALYZED = "ANALYZED",
  ANALYSIS_FAILED = "ANALYSIS_FAILED",
  PENDING_NOTIFY = "PENDING_NOTIFY",
  NOTIFY_FAILED = "NOTIFY_FAILED",
  NOT_NOTIFIED = "NOT_NOTIFIED",
  NOTIFIED = "NOTIFIED",
}
