(module access)

(defcolumns
    TX_NUMBER
    ADDRESS_HI
    ADDRESS_LO
    STORAGE_KEY_HI
    STORAGE_KEY_LO
    ACCESS_GAS
    GAS_RUNNING_TOTAL
    ACCESS_TUPLE_NON_EMPTY)

(defconst
	G_ACCESS_LIST_ADDRESS 2400
	G_ACCESS_LIST_STORAGE 1900)

;TODO