export const MENUS = [
  {
    __id: "4Ue1sSCmmNyS76CTOahmZq",
    __typename: "link",
    name: "About",
    label: "About",
    external: false,
    submenusLeft: [
      {
        __id: "3eX5eGDckzHSaCviFiss7S",
        __typename: "link",
        name: "About Linea",
        label: "About Linea",
        url: "https://linea.mirror.xyz/-GqmTyanSHh1QZhndPCq7Xeju5bgofL5irh5vVvM_t8",
        external: true,
      },
      {
        __id: "7j8XvCYmtCMi58g24jtDDe",
        __typename: "link",
        name: "Linea Association",
        label: "Linea Association",
        url: "https://linea.build/association",
        external: true,
      },
      {
        __id: "1OQZ5zlIztJNxNFX30aKX6",
        __typename: "link",
        name: "Security",
        label: "Security",
        url: "https://linea.build/security",
        external: true,
      },
      {
        __id: "5kG4IZEU6AxJvEFBW1si6k",
        __typename: "link",
        name: "Identity",
        label: "Identity",
        url: "https://linea.build/identity",
        external: true,
      },
      {
        __id: "6UHoii2MrPXPdnnZGPdOrC",
        __typename: "link",
        name: "NFTs",
        label: "NFTs",
        url: "https://linea.build/nft",
        external: true,
      },
      {
        __id: "63l62AIxB4arcvRlI90Dmv",
        __typename: "link",
        name: "Decentralization",
        label: "Decentralization",
        url: "https://docs.linea.build/architecture/overview/decentralization-roadmap",
        external: true,
      },
      {
        __id: "7MWkG4vZFk4G2qnfue0Wex",
        __typename: "link",
        name: "Careers",
        label: "Careers",
        url: "https://consensys.io/open-roles",
        external: true,
      },
      {
        __id: "33aoGWUu2ekjatcELIevwx",
        __typename: "link",
        name: "FAQ",
        label: "FAQ",
        url: "https://linea.build/faq",
        external: true,
      },
    ],
  },
  {
    __id: "kQ8tlhIfoeyolERRzX4WT",
    __typename: "link",
    name: "Bridge",
    label: "Bridge",
    external: false,
    active: true,
    desktopUrl: "/",
    submenusLeft: [
      {
        __id: "3cPGRx3oGMEnLzgw8VUFUJzz",
        __typename: "link",
        name: "Bridge",
        label: "Bridge",
        url: "/",
        mobileOnly: true,
      },
      {
        __id: "6Nafs8i1CnnT6WIaJUqnjezz",
        __typename: "link",
        name: "FAQ",
        label: "FAQ",
        url: "/faq",
      },
    ],
  },
  {
    __id: "1vnfkN5oAGfLUThPFBWNhv",
    __typename: "link",
    name: "Build",
    label: "Build",
    external: false,
    submenusLeft: [
      {
        __id: "3cPGRx3oGMEnLzgw8VUFUJ",
        __typename: "link",
        name: "Get Started",
        label: "Get Started",
        url: "https://linea.build/developers",
        external: true,
      },
      {
        __id: "6Nafs8i1CnnT6WIaJUqnje",
        __typename: "link",
        name: "Documentation",
        label: "Documentation",
        url: "https://docs.linea.build/",
        external: true,
      },
      {
        __id: "7xRLoVywjNIM8dH14ihoxn",
        __typename: "link",
        name: "Block Explorer",
        label: "Block Explorer",
        url: "https://lineascan.build/",
        external: true,
      },
      {
        __id: "1I3TUdem6qKqheJISSn3DL",
        __typename: "link",
        name: "Status",
        label: "Status",
        url: "https://linea.statuspage.io/",
        external: true,
      },
      {
        __id: "66KuNUJVBd5ADw4bqWbkPu",
        __typename: "link",
        name: "Bug Bounty",
        label: "Bug Bounty",
        url: "https://immunefi.com/bug-bounty/linea/information/",
        external: true,
      },
    ],
  },
  {
    __id: "26O3hVvXLdQwEueLMdQ6Xj",
    __typename: "link",
    name: "Explore",
    label: "Explore",
    external: false,
    submenusLeft: [
      {
        __id: "7zkEgKxvhM8zsJNlA6X3vr",
        __typename: "link",
        name: "Ecosystem Hub",
        label: "Ecosystem Hub",
        url: "https://linea.build/ecosystem",
        external: true,
      },
      {
        __id: "5pBMIkaLxw7iA5TYAF8No2",
        __typename: "link",
        name: "Dapp Directory",
        label: "Dapp Directory",
        url: "https://linea.build/apps",
        external: true,
      },
      {
        __id: "6u3coqiWnJ63a8Id82iik0",
        __typename: "link",
        name: "Linea Names",
        label: "Linea Names",
        url: "https://names.linea.build/",
        external: true,
      },
      {
        __id: "3KTVMNOxZDs3ZDZNtENq0k",
        __typename: "link",
        name: "Proof of Humanity",
        label: "Proof of Humanity",
        url: "https://poh.linea.build/",
        external: true,
      },
      {
        __id: "7Jdoj0YJK0rCAlGlvw8yXC",
        __typename: "link",
        name: "Blog",
        label: "Blog",
        url: "https://linea.mirror.xyz/",
        external: true,
      },
      {
        __id: "6HdrcyNTK37Vbx33zY081W",
        __typename: "link",
        name: "Community Forum",
        label: "Community Forum",
        url: "https://community.linea.build/",
        external: true,
      },
      {
        __id: "IW04oKbIyDlHYUGM8LA3g",
        __typename: "link",
        name: "Events",
        label: "Events",
        url: "https://lu.ma/user/Consensys",
        external: true,
      },
    ],
  },
  {
    __id: "1jk7BN1GwfDOKUoSdG5App",
    __typename: "link",
    name: "Resources",
    label: "Resources",
    external: false,
    submenusLeft: [
      {
        __id: "6Nafs8i1CnnT6WIaJUqnje",
        __typename: "link",
        name: "Documentation",
        label: "Documentation",
        url: "https://docs.linea.build/",
        external: true,
      },
      {
        __id: "TmRJrBRLXsOCknW1qZuiT",
        __typename: "link",
        name: "Community Hub",
        label: "Community Hub",
        url: "https://linea.build/community",
        external: true,
      },
      {
        __id: "1q0b1m8Suj25sePbc1dD9g",
        __typename: "link",
        name: "Help Center",
        label: "Help Center",
        url: "https://support.linea.build/",
        external: true,
      },
      {
        __id: "01wv6FiyW8WmBwVSiELs0L",
        __typename: "link",
        name: "Brand Assets",
        label: "Brand Assets",
        url: "https://linea.build/assets",
        external: true,
      },
    ],
    submenusRight: {
      __id: "SQOTqw3aK6kNo3oUGGh7W",
      __typename: "link",
      name: "Socials",
      label: "Socials",
      external: false,
      submenusLeft: [
        {
          __id: "1g41ACZjWPLyENAVaumoSo",
          __typename: "link",
          name: "X",
          label: "X",
          url: "https://x.com/LineaBuild",
          external: true,
          icon: {
            __id: "2DgMlc54Mv2yYX2ygBXkqs",
            __typename: "",
            title: "x",
            description: "",
            file: {
              url: "/images/logo/header/x.svg",
              details: {
                size: 389,
                image: {
                  width: 21,
                  height: 19,
                },
              },
              fileName: "x.svg",
              contentType: "image/svg+xml",
            },
          },
        },
        {
          __id: "5wjaHnBb4aoWPHOKaakXjD",
          __typename: "link",
          name: "Warpcast",
          label: "Warpcast",
          url: "https://warpcast.com/linea",
          external: true,
          icon: {
            __id: "5tF4tbrjbN3qBJCuwgrdoF",
            __typename: "",
            title: "farcaster-final",
            description: "",
            file: {
              url: "/images/logo/header/farcaster-final.svg",
              details: {
                size: 925,
                image: {
                  width: 752,
                  height: 689,
                },
              },
              fileName: "farcaster-final.svg",
              contentType: "image/svg+xml",
            },
          },
        },
        {
          __id: "5SjPjwYhxfoJhxl7H24dSl",
          __typename: "link",
          name: "Discord",
          label: "Discord",
          url: "https://discord.com/invite/linea",
          external: true,
          icon: {
            __id: "3QIUEvZ2GeZLIlOONOxf0L",
            __typename: "",
            title: "discord",
            description: "",
            file: {
              url: "/images/logo/header/discord.svg",
              details: {
                size: 1346,
                image: {
                  width: 21,
                  height: 17,
                },
              },
              fileName: "discord.svg",
              contentType: "image/svg+xml",
            },
          },
        },
        {
          __id: "5ZAvfOudV5DaHlZytyAVtn",
          __typename: "link",
          name: "Youtube",
          label: "Youtube",
          url: "https://www.youtube.com/playlist?list=PLJ06SwdM0bLoTMaxUIJmPBuWnJUc57ZaU",
          external: true,
          icon: {
            __id: "4TJEyttUd01wblxnZBgi4r",
            __typename: "",
            title: "youtube",
            description: "",
            file: {
              url: "/images/logo/header/youtube.svg",
              details: {
                size: 1031,
                image: {
                  width: 24,
                  height: 17,
                },
              },
              fileName: "youtube.svg",
              contentType: "image/svg+xml",
            },
          },
        },
      ],
    },
  },
];
