export const DEFAULT_MAX_FEE_PER_GAS = 100000000000n;
export const DEFAULT_ENFORCE_MAX_GAS_FEE = false;
export const DEFAULT_GAS_ESTIMATION_PERCENTILE = 20;
export const DEFAULT_L2_MESSAGE_TREE_DEPTH = 5;
export const DEFAULT_RATE_LIMIT_MARGIN = 0.95;
export const DEFAULT_ENABLE_LINEA_ESTIMATE_GAS = false;
