module.exports = {
  preset: "ts-jest",
  testEnvironment: "node",
  rootDir: ".",
  testRegex: "test.ts$",
  verbose: true,
  collectCoverage: true,
  collectCoverageFrom: ["src/**/*.ts"],
  coverageReporters: ["html", "lcov", "text"],
  testPathIgnorePatterns: [
    "src/infrastructure/blockchain/abis",
    "src/infrastructure/persistence/migrations/",
    "src/infrastructure/persistence/repositories/",
    "src/infrastructure/persistence/subscribers/",
    "src/index.ts",
    "src/utils/PostmanWinstonLogger.ts",
  ],
  coveragePathIgnorePatterns: [
    "src/infrastructure/blockchain/abis",
    "src/infrastructure/persistence/migrations/",
    "src/infrastructure/persistence/repositories/",
    "src/infrastructure/persistence/subscribers/",
    "src/index.ts",
    "src/utils/PostmanWinstonLogger.ts",
    "src/utils/testing/",
  ],
};
