/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IL1LineaTokenBurner, IL1LineaTokenBurnerInterface } from "../../../operational/interfaces/IL1LineaTokenBurner.js";

  const _abi = [
  {
    "inputs": [],
    "name": "NoTokensToBurn",
    "type": "error"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": false,
        "internalType": "address",
        "name": "messageService",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "address",
        "name": "lineaToken",
        "type": "address"
      }
    ],
    "name": "L1LineaTokenBurnerInitialized",
    "type": "event"
  },
  {
    "inputs": [
      {
        "components": [
          {
            "internalType": "bytes32[]",
            "name": "proof",
            "type": "bytes32[]"
          },
          {
            "internalType": "uint256",
            "name": "messageNumber",
            "type": "uint256"
          },
          {
            "internalType": "uint32",
            "name": "leafIndex",
            "type": "uint32"
          },
          {
            "internalType": "address",
            "name": "from",
            "type": "address"
          },
          {
            "internalType": "address",
            "name": "to",
            "type": "address"
          },
          {
            "internalType": "uint256",
            "name": "fee",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "value",
            "type": "uint256"
          },
          {
            "internalType": "address payable",
            "name": "feeRecipient",
            "type": "address"
          },
          {
            "internalType": "bytes32",
            "name": "merkleRoot",
            "type": "bytes32"
          },
          {
            "internalType": "bytes",
            "name": "data",
            "type": "bytes"
          }
        ],
        "internalType": "struct IL1MessageService.ClaimMessageWithProofParams",
        "name": "_params",
        "type": "tuple"
      }
    ],
    "name": "claimMessageWithProof",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  export class IL1LineaTokenBurner__factory {
    static readonly abi = _abi;
    static createInterface(): IL1LineaTokenBurnerInterface {
      return new Interface(_abi) as IL1LineaTokenBurnerInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IL1LineaTokenBurner {
      return new Contract(address, _abi, runner) as unknown as IL1LineaTokenBurner;
    }
  }
  