(module blsdata)

(defun (phase_sum)
    (+ (* PHASE_POINT_EVALUATION_DATA DATA_POINT_EVALUATION_FLAG)
       (* PHASE_POINT_EVALUATION_RESULT RSLT_POINT_EVALUATION_FLAG)
       (* PHASE_BLS_G1_ADD_DATA DATA_BLS_G1_ADD_FLAG)
       (* PHASE_BLS_G1_ADD_RESULT RSLT_BLS_G1_ADD_FLAG)
       (* PHASE_BLS_G1_MSM_DATA DATA_BLS_G1_MSM_FLAG)
       (* PHASE_BLS_G1_MSM_RESULT RSLT_BLS_G1_MSM_FLAG)
       (* PHASE_BLS_G2_ADD_DATA DATA_BLS_G2_ADD_FLAG)
       (* PHASE_BLS_G2_ADD_RESULT RSLT_BLS_G2_ADD_FLAG)
       (* PHASE_BLS_G2_MSM_DATA DATA_BLS_G2_MSM_FLAG)
       (* PHASE_BLS_G2_MSM_RESULT RSLT_BLS_G2_MSM_FLAG)
       (* PHASE_BLS_PAIRING_CHECK_DATA DATA_BLS_PAIRING_CHECK_FLAG)
       (* PHASE_BLS_PAIRING_CHECK_RESULT RSLT_BLS_PAIRING_CHECK_FLAG)
       (* PHASE_BLS_MAP_FP_TO_G1_DATA DATA_BLS_MAP_FP_TO_G1_FLAG)
       (* PHASE_BLS_MAP_FP_TO_G1_RESULT RSLT_BLS_MAP_FP_TO_G1_FLAG)
       (* PHASE_BLS_MAP_FP2_TO_G2_DATA DATA_BLS_MAP_FP2_TO_G2_FLAG)
       (* PHASE_BLS_MAP_FP2_TO_G2_RESULT RSLT_BLS_MAP_FP2_TO_G2_FLAG)))

(defconstraint index-constancy-phase ()
    (counter-constancy INDEX PHASE)) ;; NOTE: PHASE is said to be index-constant

(defconstraint setting-phase ()
    (eq! PHASE (phase_sum)))

    
   
   
   
