(module blsdata)

(defun (index_max_sum)
    (+ (* INDEX_MAX_DATA_POINT_EVALUATION DATA_POINT_EVALUATION_FLAG)
       (* INDEX_MAX_DATA_G1_ADD DATA_BLS_G1_ADD_FLAG)
       (* INDEX_MAX_DATA_G2_ADD DATA_BLS_G2_ADD_FLAG)
       (* INDEX_MAX_DATA_MAP_FP_TO_G1 DATA_BLS_MAP_FP_TO_G1_FLAG)
       (* INDEX_MAX_DATA_MAP_FP2_TO_G2 DATA_BLS_MAP_FP2_TO_G2_FLAG)
       (* INDEX_MAX_RSLT_POINT_EVALUATION RSLT_POINT_EVALUATION_FLAG)
       (* INDEX_MAX_RSLT_G1_ADD RSLT_BLS_G1_ADD_FLAG)
       (* INDEX_MAX_RSLT_G1_MSM RSLT_BLS_G1_MSM_FLAG)
       (* INDEX_MAX_RSLT_G2_ADD RSLT_BLS_G2_ADD_FLAG)
       (* INDEX_MAX_RSLT_G2_MSM RSLT_BLS_G2_MSM_FLAG)
       (* INDEX_MAX_RSLT_PAIRING_CHECK RSLT_BLS_PAIRING_CHECK_FLAG)
       (* INDEX_MAX_RSLT_MAP_FP_TO_G1 RSLT_BLS_MAP_FP_TO_G1_FLAG)
       (* INDEX_MAX_RSLT_MAP_FP2_TO_G2 RSLT_BLS_MAP_FP2_TO_G2_FLAG)))

(defconstraint index-constancy-index-max ()
    (counter-constancy INDEX INDEX_MAX))
    
(defconstraint set-index-max ()
  (eq! (* 16 INDEX_MAX)
       (+ (* 16 (index_max_sum))
          (* DATA_BLS_G1_MSM_FLAG (- TOTAL_SIZE 16))
          (* DATA_BLS_G2_MSM_FLAG (- TOTAL_SIZE 16))
          (* DATA_BLS_PAIRING_CHECK_FLAG (- TOTAL_SIZE 16)))))
   
   
