(module rlptxn)

(defconstraint phase-size-decrease (:guard IS_AUTHORIZATION_LIST)
 (if-not-zero (rlptxn---authorization-list---row-contains-tuple-data)
 (eq! (rlptxn---authorization-list---list-RLP-length-countdown)
      (- (prev (rlptxn---authorization-list---list-RLP-length-countdown))
         (* LC cmp/LIMB_SIZE))
 )))

(defconstraint tuple-size-decrease (:guard IS_AUTHORIZATION_LIST)
 (if-not-zero (rlptxn---authorization-list---not-first-row-tuple)
 (eq! (rlptxn---authorization-list---item-RLP-length-countdown)
      (- (prev (rlptxn---authorization-list---item-RLP-length-countdown))
         (* LC cmp/LIMB_SIZE))
 )))

(defconstraint tuple-constancy  (:guard IS_AUTHORIZATION_LIST)
  (if-not-zero (rlptxn---authorization-list---not-first-row-tuple)
  (begin
    (did-inc! (rlptxn---authorization-list---tuple-index) 0)
    (did-inc! (rlptxn---authorization-list---chain-id-hi) 0)
    (did-inc! (rlptxn---authorization-list---chain-id-lo) 0)
    (did-inc! (rlptxn---authorization-list---address-hi)  0)
    (did-inc! (rlptxn---authorization-list---address-lo)  0)
    (did-inc! (rlptxn---authorization-list---nonce)       0)
    (did-inc! (rlptxn---authorization-list---y)           0)
    (did-inc! (rlptxn---authorization-list---r-hi)        0)
    (did-inc! (rlptxn---authorization-list---r-lo)        0)
    (did-inc! (rlptxn---authorization-list---s-hi)        0)

)))
