(module rlptxn)

(defun (rlptxn---authorization-list---first-CMP-row)              (prev TXN))
(defun (rlptxn---authorization-list---again-CMP-row)              (* (prev CMP) CMP))
(defun (rlptxn---authorization-list---row-contains-tuple-data)    (* CMP (- 1 (prev TXN))))
(defun (rlptxn---authorization-list---first-row-tuple-processing) (* (prev IS_AUTHORIZATION_LIST)
                                                                     (- (rlptxn---authorization-list---tuple-index)
                                                                        (prev (rlptxn---authorization-list---tuple-index)))))
(defun (rlptxn---authorization-list---not-first-row-tuple)        (* (rlptxn---authorization-list---row-contains-tuple-data)
                                                                     (- 1 (rlptxn---authorization-list---first-row-tuple-processing))))
(defun (rlptxn---authorization-list---list-RLP-length-countdown)  cmp/AUX_1)
(defun (rlptxn---authorization-list---item-RLP-length-countdown)  cmp/AUX_2)
(defun (rlptxn---authorization-list---tuple-index)                cmp/AUX_CCC_1)
(defun (rlptxn---authorization-list---chain-id-hi)                cmp/AUX_8)
(defun (rlptxn---authorization-list---chain-id-lo)                cmp/AUX_3)
(defun (rlptxn---authorization-list---address-hi)                 cmp/AUX_CCC_4)
(defun (rlptxn---authorization-list---address-lo)                 cmp/AUX_CCC_5)
(defun (rlptxn---authorization-list---nonce)                      cmp/AUX_CCC_2)
(defun (rlptxn---authorization-list---y)                          cmp/AUX_CCC_3)
(defun (rlptxn---authorization-list---r-hi)                       cmp/AUX_4)
(defun (rlptxn---authorization-list---r-lo)                       cmp/AUX_5)
(defun (rlptxn---authorization-list---s-hi)                       cmp/AUX_6)
(defun (rlptxn---authorization-list---s-lo)                       cmp/AUX_7)
(defun (rlptxn---authorization-list---end-of-phase)               (- 1 (~ (- (rlptxn---authorization-list---tuple-index)
                                                                              LENGTH_OF_DELEGATION_LIST))))
