export const MAX_FORCED_TRANSACTION_GAS_LIMIT = 300_000n;
export const MAX_INPUT_LENGTH_LIMIT = 4096n;
export const HARDHAT_CHAIN_ID = 31337n;
export const LINEA_MAINNET_CHAIN_ID = 59144n;
export const FORCED_TRANSACTION_FEE = 1_000n;
export const L2_BLOCK_TIME_SECONDS = 1n;
