import { ethers } from "ethers";
import { HASH_ZERO } from "./general.js";

const keccak256Packed = (value: string) => ethers.keccak256(ethers.solidityPacked(["string"], [value]));

// Linea XP Token roles
export const MINTER_ROLE = keccak256Packed("MINTER_ROLE");
export const TRANSFER_ROLE = keccak256Packed("TRANSFER_ROLE");

// TimeLock roles
export const TIMELOCK_ADMIN_ROLE = keccak256Packed("TIMELOCK_ADMIN_ROLE");
export const PROPOSER_ROLE = keccak256Packed("PROPOSER_ROLE");
export const EXECUTOR_ROLE = keccak256Packed("EXECUTOR_ROLE");
export const CANCELLER_ROLE = keccak256Packed("CANCELLER_ROLE");

// Roles hashes
export const DEFAULT_ADMIN_ROLE = HASH_ZERO;
export const FUNCTION_EXECUTOR_ROLE = keccak256Packed("FUNCTION_EXECUTOR_ROLE");
export const RATE_LIMIT_SETTER_ROLE = keccak256Packed("RATE_LIMIT_SETTER_ROLE");
export const USED_RATE_LIMIT_RESETTER_ROLE = keccak256Packed("USED_RATE_LIMIT_RESETTER_ROLE");
export const L1_L2_MESSAGE_SETTER_ROLE = keccak256Packed("L1_L2_MESSAGE_SETTER_ROLE");
export const PAUSE_ALL_ROLE = keccak256Packed("PAUSE_ALL_ROLE");
export const UNPAUSE_ALL_ROLE = keccak256Packed("UNPAUSE_ALL_ROLE");
export const PAUSE_L1_L2_ROLE = keccak256Packed("PAUSE_L1_L2_ROLE");
export const UNPAUSE_L1_L2_ROLE = keccak256Packed("UNPAUSE_L1_L2_ROLE");
export const PAUSE_L2_L1_ROLE = keccak256Packed("PAUSE_L2_L1_ROLE");
export const UNPAUSE_L2_L1_ROLE = keccak256Packed("UNPAUSE_L2_L1_ROLE");
export const PAUSE_STATE_DATA_SUBMISSION_ROLE = keccak256Packed("PAUSE_STATE_DATA_SUBMISSION_ROLE");
export const UNPAUSE_STATE_DATA_SUBMISSION_ROLE = keccak256Packed("UNPAUSE_STATE_DATA_SUBMISSION_ROLE");
export const PAUSE_FINALIZATION_ROLE = keccak256Packed("PAUSE_FINALIZATION_ROLE");
export const UNPAUSE_FINALIZATION_ROLE = keccak256Packed("UNPAUSE_FINALIZATION_ROLE");
export const MINIMUM_FEE_SETTER_ROLE = keccak256Packed("MINIMUM_FEE_SETTER_ROLE");
export const OPERATOR_ROLE = keccak256Packed("OPERATOR_ROLE");
export const VERIFIER_SETTER_ROLE = keccak256Packed("VERIFIER_SETTER_ROLE");
export const VERIFIER_UNSETTER_ROLE = keccak256Packed("VERIFIER_UNSETTER_ROLE");
export const L1_MERKLE_ROOTS_SETTER_ROLE = keccak256Packed("L1_MERKLE_ROOTS_SETTER_ROLE");
export const L2_MERKLE_ROOTS_SETTER_ROLE = keccak256Packed("L2_MERKLE_ROOTS_SETTER_ROLE");
export const SECURITY_COUNCIL_ROLE = keccak256Packed("SECURITY_COUNCIL_ROLE");
export const BAD_STARTING_HASH = keccak256Packed("BAD_STARTING_HASH");

// TokenBridge roles
export const PAUSE_INITIATE_TOKEN_BRIDGING_ROLE = keccak256Packed("PAUSE_INITIATE_TOKEN_BRIDGING_ROLE");
export const PAUSE_COMPLETE_TOKEN_BRIDGING_ROLE = keccak256Packed("PAUSE_COMPLETE_TOKEN_BRIDGING_ROLE");
export const UNPAUSE_INITIATE_TOKEN_BRIDGING_ROLE = keccak256Packed("UNPAUSE_INITIATE_TOKEN_BRIDGING_ROLE");
export const UNPAUSE_COMPLETE_TOKEN_BRIDGING_ROLE = keccak256Packed("UNPAUSE_COMPLETE_TOKEN_BRIDGING_ROLE");
export const SET_RESERVED_TOKEN_ROLE = keccak256Packed("SET_RESERVED_TOKEN_ROLE");
export const REMOVE_RESERVED_TOKEN_ROLE = keccak256Packed("REMOVE_RESERVED_TOKEN_ROLE");
export const SET_CUSTOM_CONTRACT_ROLE = keccak256Packed("SET_CUSTOM_CONTRACT_ROLE");
export const SET_MESSAGE_SERVICE_ROLE = keccak256Packed("SET_MESSAGE_SERVICE_ROLE");

export const SET_YIELD_MANAGER_ROLE = keccak256Packed("SET_YIELD_MANAGER_ROLE");
export const YIELD_PROVIDER_STAKING_ROLE = keccak256Packed("YIELD_PROVIDER_STAKING_ROLE");

// YieldManager related pause roles
export const PAUSE_NATIVE_YIELD_STAKING_ROLE = keccak256Packed("PAUSE_NATIVE_YIELD_STAKING_ROLE");
export const UNPAUSE_NATIVE_YIELD_STAKING_ROLE = keccak256Packed("UNPAUSE_NATIVE_YIELD_STAKING_ROLE");
export const PAUSE_NATIVE_YIELD_UNSTAKING_ROLE = keccak256Packed("PAUSE_NATIVE_YIELD_UNSTAKING_ROLE");
export const UNPAUSE_NATIVE_YIELD_UNSTAKING_ROLE = keccak256Packed("UNPAUSE_NATIVE_YIELD_UNSTAKING_ROLE");
export const PAUSE_NATIVE_YIELD_PERMISSIONLESS_ACTIONS_ROLE = keccak256Packed(
  "PAUSE_NATIVE_YIELD_PERMISSIONLESS_ACTIONS_ROLE",
);
export const UNPAUSE_NATIVE_YIELD_PERMISSIONLESS_ACTIONS_ROLE = keccak256Packed(
  "UNPAUSE_NATIVE_YIELD_PERMISSIONLESS_ACTIONS_ROLE",
);
export const PAUSE_NATIVE_YIELD_REPORTING_ROLE = keccak256Packed("PAUSE_NATIVE_YIELD_REPORTING_ROLE");
export const UNPAUSE_NATIVE_YIELD_REPORTING_ROLE = keccak256Packed("UNPAUSE_NATIVE_YIELD_REPORTING_ROLE");
