/*
 * Copyright ConsenSys AG.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
 * an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

package net.consensys.linea.zktracer.module.alu.ext;

import java.math.BigInteger;
import java.util.List;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import lombok.Builder;
import lombok.Singular;
import net.consensys.linea.zktracer.bytes.UnsignedByte;

@JsonPropertyOrder({
  "ACC_A_0",
  "ACC_A_1",
  "ACC_A_2",
  "ACC_A_3",
  "ACC_B_0",
  "ACC_B_1",
  "ACC_B_2",
  "ACC_B_3",
  "ACC_C_0",
  "ACC_C_1",
  "ACC_C_2",
  "ACC_C_3",
  "ACC_DELTA_0",
  "ACC_DELTA_1",
  "ACC_DELTA_2",
  "ACC_DELTA_3",
  "ACC_H_0",
  "ACC_H_1",
  "ACC_H_2",
  "ACC_H_3",
  "ACC_H_4",
  "ACC_H_5",
  "ACC_I_0",
  "ACC_I_1",
  "ACC_I_2",
  "ACC_I_3",
  "ACC_I_4",
  "ACC_I_5",
  "ACC_I_6",
  "ACC_J_0",
  "ACC_J_1",
  "ACC_J_2",
  "ACC_J_3",
  "ACC_J_4",
  "ACC_J_5",
  "ACC_J_6",
  "ACC_J_7",
  "ACC_Q_0",
  "ACC_Q_1",
  "ACC_Q_2",
  "ACC_Q_3",
  "ACC_Q_4",
  "ACC_Q_5",
  "ACC_Q_6",
  "ACC_Q_7",
  "ACC_R_0",
  "ACC_R_1",
  "ACC_R_2",
  "ACC_R_3",
  "ARG_1_HI",
  "ARG_1_LO",
  "ARG_2_HI",
  "ARG_2_LO",
  "ARG_3_HI",
  "ARG_3_LO",
  "BIT_1",
  "BIT_2",
  "BIT_3",
  "BYTE_A_0",
  "BYTE_A_1",
  "BYTE_A_2",
  "BYTE_A_3",
  "BYTE_B_0",
  "BYTE_B_1",
  "BYTE_B_2",
  "BYTE_B_3",
  "BYTE_C_0",
  "BYTE_C_1",
  "BYTE_C_2",
  "BYTE_C_3",
  "BYTE_DELTA_0",
  "BYTE_DELTA_1",
  "BYTE_DELTA_2",
  "BYTE_DELTA_3",
  "BYTE_H_0",
  "BYTE_H_1",
  "BYTE_H_2",
  "BYTE_H_3",
  "BYTE_H_4",
  "BYTE_H_5",
  "BYTE_I_0",
  "BYTE_I_1",
  "BYTE_I_2",
  "BYTE_I_3",
  "BYTE_I_4",
  "BYTE_I_5",
  "BYTE_I_6",
  "BYTE_J_0",
  "BYTE_J_1",
  "BYTE_J_2",
  "BYTE_J_3",
  "BYTE_J_4",
  "BYTE_J_5",
  "BYTE_J_6",
  "BYTE_J_7",
  "BYTE_Q_0",
  "BYTE_Q_1",
  "BYTE_Q_2",
  "BYTE_Q_3",
  "BYTE_Q_4",
  "BYTE_Q_5",
  "BYTE_Q_6",
  "BYTE_Q_7",
  "BYTE_R_0",
  "BYTE_R_1",
  "BYTE_R_2",
  "BYTE_R_3",
  "CMP",
  "CT",
  "INST",
  "OF_H",
  "OF_I",
  "OF_J",
  "OF_RES",
  "OLI",
  "RES_HI",
  "RES_LO",
  "STAMP",
})
@Builder
record Trace(
    @Singular @JsonProperty("ACC_A_0") List<BigInteger> accA0Args,
    @Singular @JsonProperty("ACC_A_1") List<BigInteger> accA1Args,
    @Singular @JsonProperty("ACC_A_2") List<BigInteger> accA2Args,
    @Singular @JsonProperty("ACC_A_3") List<BigInteger> accA3Args,
    @Singular @JsonProperty("ACC_B_0") List<BigInteger> accB0Args,
    @Singular @JsonProperty("ACC_B_1") List<BigInteger> accB1Args,
    @Singular @JsonProperty("ACC_B_2") List<BigInteger> accB2Args,
    @Singular @JsonProperty("ACC_B_3") List<BigInteger> accB3Args,
    @Singular @JsonProperty("ACC_C_0") List<BigInteger> accC0Args,
    @Singular @JsonProperty("ACC_C_1") List<BigInteger> accC1Args,
    @Singular @JsonProperty("ACC_C_2") List<BigInteger> accC2Args,
    @Singular @JsonProperty("ACC_C_3") List<BigInteger> accC3Args,
    @Singular @JsonProperty("ACC_DELTA_0") List<BigInteger> accDelta0Args,
    @Singular @JsonProperty("ACC_DELTA_1") List<BigInteger> accDelta1Args,
    @Singular @JsonProperty("ACC_DELTA_2") List<BigInteger> accDelta2Args,
    @Singular @JsonProperty("ACC_DELTA_3") List<BigInteger> accDelta3Args,
    @Singular @JsonProperty("ACC_H_0") List<BigInteger> accH0Args,
    @Singular @JsonProperty("ACC_H_1") List<BigInteger> accH1Args,
    @Singular @JsonProperty("ACC_H_2") List<BigInteger> accH2Args,
    @Singular @JsonProperty("ACC_H_3") List<BigInteger> accH3Args,
    @Singular @JsonProperty("ACC_H_4") List<BigInteger> accH4Args,
    @Singular @JsonProperty("ACC_H_5") List<BigInteger> accH5Args,
    @Singular @JsonProperty("ACC_I_0") List<BigInteger> accI0Args,
    @Singular @JsonProperty("ACC_I_1") List<BigInteger> accI1Args,
    @Singular @JsonProperty("ACC_I_2") List<BigInteger> accI2Args,
    @Singular @JsonProperty("ACC_I_3") List<BigInteger> accI3Args,
    @Singular @JsonProperty("ACC_I_4") List<BigInteger> accI4Args,
    @Singular @JsonProperty("ACC_I_5") List<BigInteger> accI5Args,
    @Singular @JsonProperty("ACC_I_6") List<BigInteger> accI6Args,
    @Singular @JsonProperty("ACC_J_0") List<BigInteger> accJ0Args,
    @Singular @JsonProperty("ACC_J_1") List<BigInteger> accJ1Args,
    @Singular @JsonProperty("ACC_J_2") List<BigInteger> accJ2Args,
    @Singular @JsonProperty("ACC_J_3") List<BigInteger> accJ3Args,
    @Singular @JsonProperty("ACC_J_4") List<BigInteger> accJ4Args,
    @Singular @JsonProperty("ACC_J_5") List<BigInteger> accJ5Args,
    @Singular @JsonProperty("ACC_J_6") List<BigInteger> accJ6Args,
    @Singular @JsonProperty("ACC_J_7") List<BigInteger> accJ7Args,
    @Singular @JsonProperty("ACC_Q_0") List<BigInteger> accQ0Args,
    @Singular @JsonProperty("ACC_Q_1") List<BigInteger> accQ1Args,
    @Singular @JsonProperty("ACC_Q_2") List<BigInteger> accQ2Args,
    @Singular @JsonProperty("ACC_Q_3") List<BigInteger> accQ3Args,
    @Singular @JsonProperty("ACC_Q_4") List<BigInteger> accQ4Args,
    @Singular @JsonProperty("ACC_Q_5") List<BigInteger> accQ5Args,
    @Singular @JsonProperty("ACC_Q_6") List<BigInteger> accQ6Args,
    @Singular @JsonProperty("ACC_Q_7") List<BigInteger> accQ7Args,
    @Singular @JsonProperty("ACC_R_0") List<BigInteger> accR0Args,
    @Singular @JsonProperty("ACC_R_1") List<BigInteger> accR1Args,
    @Singular @JsonProperty("ACC_R_2") List<BigInteger> accR2Args,
    @Singular @JsonProperty("ACC_R_3") List<BigInteger> accR3Args,
    @Singular @JsonProperty("ARG_1_HI") List<BigInteger> arg1HiArgs,
    @Singular @JsonProperty("ARG_1_LO") List<BigInteger> arg1LoArgs,
    @Singular @JsonProperty("ARG_2_HI") List<BigInteger> arg2HiArgs,
    @Singular @JsonProperty("ARG_2_LO") List<BigInteger> arg2LoArgs,
    @Singular @JsonProperty("ARG_3_HI") List<BigInteger> arg3HiArgs,
    @Singular @JsonProperty("ARG_3_LO") List<BigInteger> arg3LoArgs,
    @Singular @JsonProperty("BIT_1") List<Boolean> bit1Args,
    @Singular @JsonProperty("BIT_2") List<Boolean> bit2Args,
    @Singular @JsonProperty("BIT_3") List<Boolean> bit3Args,
    @Singular @JsonProperty("BYTE_A_0") List<UnsignedByte> byteA0Args,
    @Singular @JsonProperty("BYTE_A_1") List<UnsignedByte> byteA1Args,
    @Singular @JsonProperty("BYTE_A_2") List<UnsignedByte> byteA2Args,
    @Singular @JsonProperty("BYTE_A_3") List<UnsignedByte> byteA3Args,
    @Singular @JsonProperty("BYTE_B_0") List<UnsignedByte> byteB0Args,
    @Singular @JsonProperty("BYTE_B_1") List<UnsignedByte> byteB1Args,
    @Singular @JsonProperty("BYTE_B_2") List<UnsignedByte> byteB2Args,
    @Singular @JsonProperty("BYTE_B_3") List<UnsignedByte> byteB3Args,
    @Singular @JsonProperty("BYTE_C_0") List<UnsignedByte> byteC0Args,
    @Singular @JsonProperty("BYTE_C_1") List<UnsignedByte> byteC1Args,
    @Singular @JsonProperty("BYTE_C_2") List<UnsignedByte> byteC2Args,
    @Singular @JsonProperty("BYTE_C_3") List<UnsignedByte> byteC3Args,
    @Singular @JsonProperty("BYTE_DELTA_0") List<UnsignedByte> byteDelta0Args,
    @Singular @JsonProperty("BYTE_DELTA_1") List<UnsignedByte> byteDelta1Args,
    @Singular @JsonProperty("BYTE_DELTA_2") List<UnsignedByte> byteDelta2Args,
    @Singular @JsonProperty("BYTE_DELTA_3") List<UnsignedByte> byteDelta3Args,
    @Singular @JsonProperty("BYTE_H_0") List<UnsignedByte> byteH0Args,
    @Singular @JsonProperty("BYTE_H_1") List<UnsignedByte> byteH1Args,
    @Singular @JsonProperty("BYTE_H_2") List<UnsignedByte> byteH2Args,
    @Singular @JsonProperty("BYTE_H_3") List<UnsignedByte> byteH3Args,
    @Singular @JsonProperty("BYTE_H_4") List<UnsignedByte> byteH4Args,
    @Singular @JsonProperty("BYTE_H_5") List<UnsignedByte> byteH5Args,
    @Singular @JsonProperty("BYTE_I_0") List<UnsignedByte> byteI0Args,
    @Singular @JsonProperty("BYTE_I_1") List<UnsignedByte> byteI1Args,
    @Singular @JsonProperty("BYTE_I_2") List<UnsignedByte> byteI2Args,
    @Singular @JsonProperty("BYTE_I_3") List<UnsignedByte> byteI3Args,
    @Singular @JsonProperty("BYTE_I_4") List<UnsignedByte> byteI4Args,
    @Singular @JsonProperty("BYTE_I_5") List<UnsignedByte> byteI5Args,
    @Singular @JsonProperty("BYTE_I_6") List<UnsignedByte> byteI6Args,
    @Singular @JsonProperty("BYTE_J_0") List<UnsignedByte> byteJ0Args,
    @Singular @JsonProperty("BYTE_J_1") List<UnsignedByte> byteJ1Args,
    @Singular @JsonProperty("BYTE_J_2") List<UnsignedByte> byteJ2Args,
    @Singular @JsonProperty("BYTE_J_3") List<UnsignedByte> byteJ3Args,
    @Singular @JsonProperty("BYTE_J_4") List<UnsignedByte> byteJ4Args,
    @Singular @JsonProperty("BYTE_J_5") List<UnsignedByte> byteJ5Args,
    @Singular @JsonProperty("BYTE_J_6") List<UnsignedByte> byteJ6Args,
    @Singular @JsonProperty("BYTE_J_7") List<UnsignedByte> byteJ7Args,
    @Singular @JsonProperty("BYTE_Q_0") List<UnsignedByte> byteQ0Args,
    @Singular @JsonProperty("BYTE_Q_1") List<UnsignedByte> byteQ1Args,
    @Singular @JsonProperty("BYTE_Q_2") List<UnsignedByte> byteQ2Args,
    @Singular @JsonProperty("BYTE_Q_3") List<UnsignedByte> byteQ3Args,
    @Singular @JsonProperty("BYTE_Q_4") List<UnsignedByte> byteQ4Args,
    @Singular @JsonProperty("BYTE_Q_5") List<UnsignedByte> byteQ5Args,
    @Singular @JsonProperty("BYTE_Q_6") List<UnsignedByte> byteQ6Args,
    @Singular @JsonProperty("BYTE_Q_7") List<UnsignedByte> byteQ7Args,
    @Singular @JsonProperty("BYTE_R_0") List<UnsignedByte> byteR0Args,
    @Singular @JsonProperty("BYTE_R_1") List<UnsignedByte> byteR1Args,
    @Singular @JsonProperty("BYTE_R_2") List<UnsignedByte> byteR2Args,
    @Singular @JsonProperty("BYTE_R_3") List<UnsignedByte> byteR3Args,
    @Singular @JsonProperty("CMP") List<Boolean> cmpArgs,
    @Singular @JsonProperty("CT") List<Integer> ctArgs,
    @Singular @JsonProperty("INST") List<UnsignedByte> instArgs,
    @Singular @JsonProperty("OF_H") List<Boolean> ofHArgs,
    @Singular @JsonProperty("OF_I") List<Boolean> ofIArgs,
    @Singular @JsonProperty("OF_J") List<Boolean> ofJArgs,
    @Singular @JsonProperty("OF_RES") List<Boolean> ofResArgs,
    @Singular @JsonProperty("OLI") List<Boolean> oliArgs,
    @Singular @JsonProperty("RES_HI") List<BigInteger> resHiArgs,
    @Singular @JsonProperty("RES_LO") List<BigInteger> resLoArgs,
    @Singular @JsonProperty("STAMP") List<Integer> extStampArgs) {}
