export const DEFAULT_MESSAGE_SUBMISSION_TIMEOUT = 300000;
export const DEFAULT_LISTENER_INTERVAL = 4000;
export const DEFAULT_MAX_BLOCKS_TO_FETCH_LOGS = 1000;
export const DEFAULT_MAX_FETCH_MESSAGES_FROM_DB = 1000;
export const DEFAULT_MAX_NONCE_DIFF = 10000;
export const DEFAULT_MAX_FEE_PER_GAS = 100000000000;
export const DEFAULT_GAS_ESTIMATION_PERCENTILE = 20;
export const DEFAULT_GAS_LIMIT = 0;
export const DEFAULT_LISTENER_BLOCK_CONFIRMATIONS = 4;
export const DEFAULT_PROFIT_MARGIN = 1.0;
export const DEFAULT_MAX_NUMBER_OF_RETRIES = 100;
export const DEFAULT_RETRY_DELAY_IN_SECONDS = 30;
export const DEFAULT_ONLY_EOA_TARGET = false;
export const DEFAULT_RATE_LIMIT_MARGIN = 0.95;
export const DEFAULT_MAX_CLAIM_GAS_LIMIT = 100_000;

export const PROFIT_MARGIN_MULTIPLIER = 100;

export const MESSAGE_UNKNOWN_STATUS = 0;
export const MESSAGE_ANCHORED_STATUS = 1;
export const MESSAGE_CLAIMED_STATUS = 2;

export const MESSAGE_SENT_EVENT_SIGNATURE = "0xe856c2b8bd4eb0027ce32eeaf595c21b0b6b4644b326e5b7bd80a1cf8db72e6c";
