(module blake2fmodexpdata)

(defconst
  MODEXP_MAX_BYTE_SIZE      1024
  INDEX_MAX_MODEXP          63
  INDEX_MAX_MODEXP_BASE     INDEX_MAX_MODEXP
  INDEX_MAX_MODEXP_EXPONENT INDEX_MAX_MODEXP
  INDEX_MAX_MODEXP_MODULUS  INDEX_MAX_MODEXP
  INDEX_MAX_MODEXP_RESULT   INDEX_MAX_MODEXP
  INDEX_MAX_BLAKE_DATA      12
  INDEX_MAX_BLAKE_PARAMS    1
  INDEX_MAX_BLAKE_RESULT    3)


