(module blake2f_modexp_data)

(defconst 
  PHASE_MODEXP_BASE         1
  PHASE_MODEXP_EXPONENT     2
  PHASE_MODEXP_MODULUS      3
  PHASE_MODEXP_RESULT       4
  PHASE_BLAKE_DATA          5
  PHASE_BLAKE_PARAMS        6
  PHASE_BLAKE_RESULT        7
  INDEX_MAX_MODEXP_BASE     31
  INDEX_MAX_MODEXP_EXPONENT 31
  INDEX_MAX_MODEXP_MODULUS  31
  INDEX_MAX_MODEXP_RESULT   31
  INDEX_MAX_BLAKE_DATA      12
  INDEX_MAX_BLAKE_PARAMS    1
  INDEX_MAX_BLAKE_RESULT    3)

