(module shakira)

(defconst 
  INDEX_MAX_SHA2_DATA     11
  INDEX_MAX_SHA2_RESULT   1
  INDEX_MAX_RIPEMD_DATA   3
  INDEX_MAX_RIPEMD_RESULT 1
  INDEX_MAX_KECCAK_DATA   0
  INDEX_MAX_KECCAK_RESULT 1)


