(module romlex)

(defcolumns
  (CODE_FRAGMENT_INDEX :i32)
  (CODE_FRAGMENT_INDEX_INFTY :i32)
  (CODE_SIZE :i32)
  (ADDRESS_HI :i32)
  (ADDRESS_LO :i128)
  (DEPLOYMENT_NUMBER :i16)
  (DEPLOYMENT_STATUS :binary@prove)
  (DELEGATION_NUMBER :i16)
  (COULD_BE_DELEGATION_CODE :binary@prove)
  (ACTUALLY_DELEGATION_CODE :binary@prove)
  (LEADING_THREE_BYTES :i24)
  (LEAD_DELEGATION_BYTES :i32)
  (TAIL_DELEGATION_BYTES :i128)
  (DELEGATION_ADDRESS_HI :i32)
  (DELEGATION_ADDRESS_LO :i128)
  (CODE_HASH_HI :i128 :display :hex)
  (CODE_HASH_LO :i128 :display :hex))

(defalias
  CFI CODE_FRAGMENT_INDEX)


