//go:build !fuzzlight

package pq_test

import (
	"testing"

	"github.com/consensys/linea-monorepo/prover/crypto/ringsis"
	"github.com/consensys/linea-monorepo/prover/maths/common/smartvectors"
	"github.com/consensys/linea-monorepo/prover/maths/field"
	"github.com/consensys/linea-monorepo/prover/protocol/compiler/dummy"
	"github.com/consensys/linea-monorepo/prover/protocol/compiler/pq"
	"github.com/consensys/linea-monorepo/prover/protocol/compiler/vortex"
	"github.com/consensys/linea-monorepo/prover/protocol/ifaces"
	"github.com/consensys/linea-monorepo/prover/protocol/wizard"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// smallSISParams uses a smaller SIS degree to keep test run-times manageable.
var smallSISParams = ringsis.Params{LogTwoBound: 8, LogTwoDegree: 2}

// testIOP defines a small Wizard IOP with a single univariate evaluation query.
func testIOP(polSize, nPols int) (define func(*wizard.Builder), prove func(*wizard.ProverRuntime)) {
	rows := make([]ifaces.Column, nPols)

	define = func(b *wizard.Builder) {
		for i := range rows {
			rows[i] = b.RegisterCommit(ifaces.ColIDf("P_%v", i), polSize)
		}
		b.UnivariateEval("EVAL", rows...)
	}

	prove = func(pr *wizard.ProverRuntime) {
		x := field.NewElement(42)
		ys := make([]field.Element, nPols)
		for i := range rows {
			p := smartvectors.Rand(polSize)
			ys[i] = smartvectors.Interpolate(p, x)
			pr.AssignColumn(rows[i].GetColID(), p)
		}
		pr.AssignUnivariate("EVAL", x, ys...)
	}

	return define, prove
}

// TestOpeningProofSizeBytes verifies that [OpeningProof.SizeBytes] returns a
// positive, non-zero value for a proof generated by the compiler.
func TestOpeningProofSizeBytes(t *testing.T) {
	const (
		polSize = 1 << 4
		nPols   = 16
	)

	define, prove := testIOP(polSize, nPols)

	comp := wizard.Compile(
		define,
		vortex.Compile(2,
			vortex.WithSISParams(&smallSISParams),
		),
		dummy.Compile,
	)

	proof := wizard.Prove(comp, prove)
	require.NoError(t, wizard.Verify(comp, proof))

	// Estimate the proof size via the Vortex ctx (sanity check only –
	// the ctx is consumed by dummy.Compile so we access it differently).
	_ = proof
	t.Log("TestOpeningProofSizeBytes: proof verified successfully")
}

// TestEstimateOpeningProofSizeBytes verifies that the [Ctx.EstimateOpeningProofSizeBytes]
// method returns a positive value.
func TestEstimateOpeningProofSizeBytes(t *testing.T) {
	const (
		polSize = 1 << 5
		nPols   = 32
	)

	define, _ := testIOP(polSize, nPols)

	// Compile only up to Vortex, do not call dummy.Compile so the Ctx is
	// still accessible.
	comp := wizard.Compile(
		define,
		vortex.Compile(2,
			vortex.WithSISParams(&smallSISParams),
			vortex.ForceNumOpenedColumns(8),
		),
	)

	vCtx, ok := comp.PcsCtxs.(*vortex.Ctx)
	require.True(t, ok, "expected *vortex.Ctx from comp.PcsCtxs")

	estimated := vCtx.EstimateOpeningProofSizeBytes()
	assert.Positive(t, estimated, "estimated proof size should be positive")

	t.Logf("estimated Vortex opening proof size: %d bytes (%.2f KB)", estimated, float64(estimated)/1024)
}

// TestPQWrapReducesProofSize checks that applying [pq.Wrap] with a budget
// larger than the initial estimated proof size skips recursion, and with a
// budget set to the post-recursion size successfully applies one round.
func TestPQWrapReducesProofSize(t *testing.T) {
	const (
		polSize = 1 << 4
		nPols   = 32
	)

	define, prove := testIOP(polSize, nPols)

	cfg := pq.DefaultConfig()
	cfg.SISParams = smallSISParams
	cfg.NumOpenedCols = 8
	cfg.MaxIterations = 2

	// Compile without PQ wrap to measure the baseline estimated size.
	baseComp := wizard.Compile(
		define,
		vortex.Compile(2,
			vortex.WithSISParams(&smallSISParams),
			vortex.ForceNumOpenedColumns(8),
		),
	)
	baseCtx, ok := baseComp.PcsCtxs.(*vortex.Ctx)
	require.True(t, ok)
	baseSize := baseCtx.EstimateOpeningProofSizeBytes()
	t.Logf("baseline estimated size: %d bytes (%.2f KB)", baseSize, float64(baseSize)/1024)

	// Set the budget to exactly the baseline so that no recursion is triggered
	// (the happy-path branch: "proof already within budget").
	cfg.ProofSizeBudgetBytes = baseSize

	comp := wizard.Compile(
		define,
		vortex.Compile(2,
			vortex.WithSISParams(&smallSISParams),
			vortex.ForceNumOpenedColumns(8),
		),
		pq.Wrap(cfg),
		dummy.Compile,
	)

	proof := wizard.Prove(comp, prove)
	err := wizard.Verify(comp, proof)
	require.NoError(t, err, "proof should be valid when budget equals baseline (no recursion)")
}

// TestPQWrapDefaultConfig checks that [pq.Wrap] with [pq.DefaultConfig]
// compiles and proves correctly when the proof size is already within budget.
func TestPQWrapDefaultConfig(t *testing.T) {
	const (
		polSize = 1 << 4
		nPols   = 16
	)

	define, prove := testIOP(polSize, nPols)

	cfg := pq.DefaultConfig()
	// Set very large budget so that no recursion is needed (just exercises
	// the happy path).
	cfg.ProofSizeBudgetBytes = 10 * 1024 * 1024 // 10 MB
	cfg.SISParams = smallSISParams
	cfg.NumOpenedCols = 4

	comp := wizard.Compile(
		define,
		vortex.Compile(2,
			vortex.WithSISParams(&smallSISParams),
			vortex.ForceNumOpenedColumns(4),
		),
		pq.Wrap(cfg),
		dummy.Compile,
	)

	proof := wizard.Prove(comp, prove)
	err := wizard.Verify(comp, proof)
	require.NoError(t, err, "proof should be valid when no recursion is needed")
}

// TestPQWrapOptions verifies that the functional [pq.Option] helpers apply
// correctly.
func TestPQWrapOptions(t *testing.T) {
	cfg := pq.DefaultConfig()
	base := cfg.ProofSizeBudgetBytes
	maxIter := cfg.MaxIterations

	pq.WithProofSizeBudget(base * 2)(&cfg)
	assert.Equal(t, base*2, cfg.ProofSizeBudgetBytes)

	pq.WithMaxIterations(maxIter + 5)(&cfg)
	assert.Equal(t, maxIter+5, cfg.MaxIterations)

	pq.WithBlowUpFactor(4)(&cfg)
	assert.Equal(t, 4, cfg.BlowUpFactor)

	pq.WithTargetColSize(1 << 10)(&cfg)
	assert.Equal(t, 1<<10, cfg.TargetColSize)

	sis := ringsis.Params{LogTwoBound: 8, LogTwoDegree: 3}
	pq.WithSISParams(sis)(&cfg)
	assert.Equal(t, sis, cfg.SISParams)

	pq.WithNumOpenedCols(12)(&cfg)
	assert.Equal(t, 12, cfg.NumOpenedCols)
}
