// Code generated by codegen. DO NOT EDIT.
package serde

import (
	"github.com/consensys/gnark-crypto/ecc/bls12-377/fr"
	"github.com/consensys/linea-monorepo/prover/maths/common/smartvectors"
	"github.com/consensys/linea-monorepo/prover/protocol/accessors"
	"github.com/consensys/linea-monorepo/prover/protocol/coin"
	"github.com/consensys/linea-monorepo/prover/protocol/column"
	"github.com/consensys/linea-monorepo/prover/protocol/column/verifiercol"
	"github.com/consensys/linea-monorepo/prover/protocol/compiler/cleanup"
	"github.com/consensys/linea-monorepo/prover/protocol/compiler/dummy"
	"github.com/consensys/linea-monorepo/prover/protocol/compiler/globalcs"
	"github.com/consensys/linea-monorepo/prover/protocol/compiler/horner"
	"github.com/consensys/linea-monorepo/prover/protocol/compiler/innerproduct"
	"github.com/consensys/linea-monorepo/prover/protocol/compiler/logderivativesum"
	"github.com/consensys/linea-monorepo/prover/protocol/compiler/mpts"
	"github.com/consensys/linea-monorepo/prover/protocol/compiler/permutation"
	"github.com/consensys/linea-monorepo/prover/protocol/compiler/plonkinwizard"
	"github.com/consensys/linea-monorepo/prover/protocol/compiler/poseidon2"
	"github.com/consensys/linea-monorepo/prover/protocol/compiler/recursion"
	"github.com/consensys/linea-monorepo/prover/protocol/compiler/selfrecursion"
	"github.com/consensys/linea-monorepo/prover/protocol/compiler/splitextension"
	"github.com/consensys/linea-monorepo/prover/protocol/compiler/stitchsplit"
	"github.com/consensys/linea-monorepo/prover/protocol/compiler/univariates"
	"github.com/consensys/linea-monorepo/prover/protocol/compiler/vortex"
	"github.com/consensys/linea-monorepo/prover/protocol/dedicated"
	"github.com/consensys/linea-monorepo/prover/protocol/dedicated/bigrange"
	"github.com/consensys/linea-monorepo/prover/protocol/dedicated/byte32cmp"
	"github.com/consensys/linea-monorepo/prover/protocol/dedicated/emulated"
	"github.com/consensys/linea-monorepo/prover/protocol/dedicated/expr_handle"
	"github.com/consensys/linea-monorepo/prover/protocol/dedicated/functionals"
	"github.com/consensys/linea-monorepo/prover/protocol/dedicated/merkle"
	dposeidon2 "github.com/consensys/linea-monorepo/prover/protocol/dedicated/poseidon2"
	"github.com/consensys/linea-monorepo/prover/protocol/dedicated/reedsolomon"
	"github.com/consensys/linea-monorepo/prover/protocol/dedicated/selector"
	"github.com/consensys/linea-monorepo/prover/protocol/distributed"
	"github.com/consensys/linea-monorepo/prover/protocol/ifaces"
	"github.com/consensys/linea-monorepo/prover/protocol/limbs"
	"github.com/consensys/linea-monorepo/prover/protocol/plonkinternal"
	"github.com/consensys/linea-monorepo/prover/protocol/query"
	"github.com/consensys/linea-monorepo/prover/protocol/variables"
	"github.com/consensys/linea-monorepo/prover/symbolic"
	"github.com/consensys/linea-monorepo/prover/zkevm/prover/bls"
	"github.com/consensys/linea-monorepo/prover/zkevm/prover/common"
	"github.com/consensys/linea-monorepo/prover/zkevm/prover/ecarith"
	"github.com/consensys/linea-monorepo/prover/zkevm/prover/ecdsa"
	"github.com/consensys/linea-monorepo/prover/zkevm/prover/ecpair"
	"github.com/consensys/linea-monorepo/prover/zkevm/prover/hash/importpad"
	gen_acc "github.com/consensys/linea-monorepo/prover/zkevm/prover/hash/keccak/acc_module"
	keccak "github.com/consensys/linea-monorepo/prover/zkevm/prover/hash/keccak/glue"
	"github.com/consensys/linea-monorepo/prover/zkevm/prover/hash/packing"
	zkded "github.com/consensys/linea-monorepo/prover/zkevm/prover/hash/packing/dedicated"
	"github.com/consensys/linea-monorepo/prover/zkevm/prover/hash/packing/dedicated/spaghettifier"
	"github.com/consensys/linea-monorepo/prover/zkevm/prover/hash/sha2"
	"github.com/consensys/linea-monorepo/prover/zkevm/prover/modexp"
	"github.com/consensys/linea-monorepo/prover/zkevm/prover/p256verify"
	"reflect"
)

// IDToType maps a uint16 ID to the concrete reflect.Type.
// This is O(1) access for Deserialization.
var IDToType = [...]reflect.Type{
	reflect.TypeOf(accessors.FromCoinAccessor{}),                           // ID: 0
	reflect.TypeOf(accessors.FromConstAccessor{}),                          // ID: 1
	reflect.TypeOf(accessors.FromExprAccessor{}),                           // ID: 2
	reflect.TypeOf(accessors.FromGrandProductAccessor{}),                   // ID: 3
	reflect.TypeOf(accessors.FromHornerAccessorFinalValue{}),               // ID: 4
	reflect.TypeOf(accessors.FromIntVecCoinPositionAccessor{}),             // ID: 5
	reflect.TypeOf(accessors.FromLocalOpeningYAccessor{}),                  // ID: 6
	reflect.TypeOf(accessors.FromLogDerivSumAccessor{}),                    // ID: 7
	reflect.TypeOf(accessors.FromPublicColumn{}),                           // ID: 8
	reflect.TypeOf(accessors.FromUnivXAccessor{}),                          // ID: 9
	reflect.TypeOf(bigrange.BigRangeProverAction{}),                        // ID: 10
	reflect.TypeOf(bls.MultiAddCircuitG1{}),                                // ID: 11
	reflect.TypeOf(bls.MultiAddCircuitG2{}),                                // ID: 12
	reflect.TypeOf(bls.MultiCheckableG1NonCurve{}),                         // ID: 13
	reflect.TypeOf(bls.MultiCheckableG1NonGroup{}),                         // ID: 14
	reflect.TypeOf(bls.MultiCheckableG2NonCurve{}),                         // ID: 15
	reflect.TypeOf(bls.MultiCheckableG2NonGroup{}),                         // ID: 16
	reflect.TypeOf(bls.MultiMapCircuitG1{}),                                // ID: 17
	reflect.TypeOf(bls.MultiMapCircuitG2{}),                                // ID: 18
	reflect.TypeOf(bls.MultiMillerLoopFinalExpCircuit{}),                   // ID: 19
	reflect.TypeOf(bls.MultiMillerLoopMulCircuit{}),                        // ID: 20
	reflect.TypeOf(bls.MultiMulCircuitG1{}),                                // ID: 21
	reflect.TypeOf(bls.MultiMulCircuitG2{}),                                // ID: 22
	reflect.TypeOf(bls.MultiPointEvalCircuit{}),                            // ID: 23
	reflect.TypeOf(bls.MultiPointEvalFailureCircuit{}),                     // ID: 24
	reflect.TypeOf(bool(false)),                                            // ID: 25
	reflect.TypeOf(byte32cmp.Bytes32CmpProverAction{}),                     // ID: 26
	reflect.TypeOf(byte32cmp.DecompositionCtx{}),                           // ID: 27
	reflect.TypeOf(byte32cmp.MultiLimbAdd{}),                               // ID: 28
	reflect.TypeOf(byte32cmp.MultiLimbCmp{}),                               // ID: 29
	reflect.TypeOf(byte32cmp.OneLimbCmpCtx{}),                              // ID: 30
	reflect.TypeOf(cleanup.CleanupProverAction{}),                          // ID: 31
	reflect.TypeOf(coin.Info{}),                                            // ID: 32
	reflect.TypeOf(coin.Name("")),                                          // ID: 33
	reflect.TypeOf(column.FakeColumn{}),                                    // ID: 34
	reflect.TypeOf(column.Natural{}),                                       // ID: 35
	reflect.TypeOf(column.Shifted{}),                                       // ID: 36
	reflect.TypeOf(common.HashingCtx{}),                                    // ID: 37
	reflect.TypeOf(dedicated.IsZeroCtx{}),                                  // ID: 38
	reflect.TypeOf(dedicated.StackedColumn{}),                              // ID: 39
	reflect.TypeOf(distributed.AssignLPPQueries{}),                         // ID: 40
	reflect.TypeOf(distributed.CheckNxHash{}),                              // ID: 41
	reflect.TypeOf(distributed.ConglomerationHierarchicalVerifierAction{}), // ID: 42
	reflect.TypeOf(distributed.LPPSegmentBoundaryCalculator{}),             // ID: 43
	reflect.TypeOf(distributed.LppWitnessAssignment{}),                     // ID: 44
	reflect.TypeOf(distributed.ModuleGLAssignGL{}),                         // ID: 45
	reflect.TypeOf(distributed.ModuleGLAssignSendReceiveGlobal{}),          // ID: 46
	reflect.TypeOf(distributed.ModuleGLCheckSendReceiveGlobal{}),           // ID: 47
	reflect.TypeOf(distributed.SetInitialFSHash{}),                         // ID: 48
	reflect.TypeOf(distributed.StandardModuleDiscoverer{}),                 // ID: 49
	reflect.TypeOf(dposeidon2.LinearHashProverAction{}),                    // ID: 50
	reflect.TypeOf(dummy.DummyProverAction{}),                              // ID: 51
	reflect.TypeOf(dummy.DummyVerifierAction{}),                            // ID: 52
	reflect.TypeOf(ecarith.MultiECAddCircuit{}),                            // ID: 53
	reflect.TypeOf(ecarith.MultiECMulCircuit{}),                            // ID: 54
	reflect.TypeOf(ecdsa.MultiEcRecoverCircuit{}),                          // ID: 55
	reflect.TypeOf(ecpair.MultiG2GroupcheckCircuit{}),                      // ID: 56
	reflect.TypeOf(ecpair.MultiMillerLoopFinalExpCircuit{}),                // ID: 57
	reflect.TypeOf(ecpair.MultiMillerLoopMulCircuit{}),                     // ID: 58
	reflect.TypeOf(emulated.ProverActionFn{}),                              // ID: 59
	reflect.TypeOf(expr_handle.ExprHandleProverAction{}),                   // ID: 60
	reflect.TypeOf(fr.Element{}),                                           // ID: 61
	reflect.TypeOf(functionals.CoeffEvalProverAction{}),                    // ID: 62
	reflect.TypeOf(functionals.EvalBivariateProverAction{}),                // ID: 63
	reflect.TypeOf(functionals.FoldOuterProverAction{}),                    // ID: 64
	reflect.TypeOf(functionals.FoldOuterVerifierAction{}),                  // ID: 65
	reflect.TypeOf(functionals.FoldProverAction{}),                         // ID: 66
	reflect.TypeOf(functionals.FoldVerifierAction{}),                       // ID: 67
	reflect.TypeOf(functionals.InterpolationProverAction{}),                // ID: 68
	reflect.TypeOf(functionals.XYPow1MinNAccessor{}),                       // ID: 69
	reflect.TypeOf(gen_acc.GenericDataAccumulator{}),                       // ID: 70
	reflect.TypeOf(gen_acc.GenericInfoAccumulator{}),                       // ID: 71
	reflect.TypeOf(globalcs.EvaluationProver{}),                            // ID: 72
	reflect.TypeOf(globalcs.EvaluationVerifier{}),                          // ID: 73
	reflect.TypeOf(globalcs.QuotientCtx{}),                                 // ID: 74
	reflect.TypeOf(horner.AssignHornerCtx{}),                               // ID: 75
	reflect.TypeOf(horner.AssignHornerIP{}),                                // ID: 76
	reflect.TypeOf(horner.AssignHornerQuery{}),                             // ID: 77
	reflect.TypeOf(horner.CheckHornerQuery{}),                              // ID: 78
	reflect.TypeOf(horner.CheckHornerResult{}),                             // ID: 79
	reflect.TypeOf(ifaces.ColID("")),                                       // ID: 80
	reflect.TypeOf(ifaces.QueryID("")),                                     // ID: 81
	reflect.TypeOf(importpad.Importation{}),                                // ID: 82
	reflect.TypeOf(importpad.KeccakPadder{}),                               // ID: 83
	reflect.TypeOf(importpad.Sha2Padder{}),                                 // ID: 84
	reflect.TypeOf(innerproduct.ProverTask{}),                              // ID: 85
	reflect.TypeOf(innerproduct.VerifierForSize{}),                         // ID: 86
	reflect.TypeOf(int(0)),                                                 // ID: 87
	reflect.TypeOf(int16(0)),                                               // ID: 88
	reflect.TypeOf(int32(0)),                                               // ID: 89
	reflect.TypeOf(int64(0)),                                               // ID: 90
	reflect.TypeOf(int8(0)),                                                // ID: 91
	reflect.TypeOf(keccak.KeccakSingleProvider{}),                          // ID: 92
	reflect.TypeOf(keccak.ShakiraProverAction{}),                           // ID: 93
	reflect.TypeOf(limbs.LimbsBigEndian{}),                                 // ID: 94
	reflect.TypeOf(limbs.LimbsLittleEndian{}),                              // ID: 95
	reflect.TypeOf(logderivativesum.AssignLogDerivativeSumProverAction{}),  // ID: 96
	reflect.TypeOf(logderivativesum.CheckLogDerivativeSumMustBeZero{}),     // ID: 97
	reflect.TypeOf(logderivativesum.FinalEvaluationCheck{}),                // ID: 98
	reflect.TypeOf(logderivativesum.ProverTaskAtRound{}),                   // ID: 99
	reflect.TypeOf(merkle.MerkleProofProverAction{}),                       // ID: 100
	reflect.TypeOf(modexp.Modexp{}),                                        // ID: 101
	reflect.TypeOf(modexp.Module{}),                                        // ID: 102
	reflect.TypeOf(mpts.QuotientAccumulation{}),                            // ID: 103
	reflect.TypeOf(mpts.RandomPointEvaluation{}),                           // ID: 104
	reflect.TypeOf(mpts.ShadowRowProverAction{}),                           // ID: 105
	reflect.TypeOf(mpts.VerifierAction{}),                                  // ID: 106
	reflect.TypeOf(p256verify.MultiP256VerifyInstanceCircuit{}),            // ID: 107
	reflect.TypeOf(packing.Packing{}),                                      // ID: 108
	reflect.TypeOf(permutation.AssignPermutationGrandProduct{}),            // ID: 109
	reflect.TypeOf(permutation.CheckGrandProductIsOne{}),                   // ID: 110
	reflect.TypeOf(permutation.FinalProductCheck{}),                        // ID: 111
	reflect.TypeOf(permutation.ProverTaskAtRound{}),                        // ID: 112
	reflect.TypeOf(plonkinternal.CheckingActivators{}),                     // ID: 113
	reflect.TypeOf(plonkinternal.InitialBBSProverAction{}),                 // ID: 114
	reflect.TypeOf(plonkinternal.LROCommitProverAction{}),                  // ID: 115
	reflect.TypeOf(plonkinternal.PlonkNoCommitProverAction{}),              // ID: 116
	reflect.TypeOf(plonkinwizard.AssignSelOpening{}),                       // ID: 117
	reflect.TypeOf(plonkinwizard.CheckActivatorAndMask{}),                  // ID: 118
	reflect.TypeOf(plonkinwizard.CircAssignment{}),                         // ID: 119
	reflect.TypeOf(poseidon2.Poseidon2Context{}),                           // ID: 120
	reflect.TypeOf(query.FixedPermutation{}),                               // ID: 121
	reflect.TypeOf(query.GlobalConstraint{}),                               // ID: 122
	reflect.TypeOf(query.GrandProductParams{}),                             // ID: 123
	reflect.TypeOf(query.GrandProduct{}),                                   // ID: 124
	reflect.TypeOf(query.Horner{}),                                         // ID: 125
	reflect.TypeOf(query.Inclusion{}),                                      // ID: 126
	reflect.TypeOf(query.InnerProductParams{}),                             // ID: 127
	reflect.TypeOf(query.InnerProduct{}),                                   // ID: 128
	reflect.TypeOf(query.LocalConstraint{}),                                // ID: 129
	reflect.TypeOf(query.LocalOpeningParams{}),                             // ID: 130
	reflect.TypeOf(query.LocalOpening{}),                                   // ID: 131
	reflect.TypeOf(query.LogDerivSumParams{}),                              // ID: 132
	reflect.TypeOf(query.LogDerivativeSum{}),                               // ID: 133
	reflect.TypeOf(query.Permutation{}),                                    // ID: 134
	reflect.TypeOf(query.PlonkInWizard{}),                                  // ID: 135
	reflect.TypeOf(query.Poseidon2{}),                                      // ID: 136
	reflect.TypeOf(query.Projection{}),                                     // ID: 137
	reflect.TypeOf(query.Range{}),                                          // ID: 138
	reflect.TypeOf(query.UnivariateEvalParams{}),                           // ID: 139
	reflect.TypeOf(query.UnivariateEval{}),                                 // ID: 140
	reflect.TypeOf(recursion.AssignVortexOpenedCols{}),                     // ID: 141
	reflect.TypeOf(recursion.AssignVortexUAlpha{}),                         // ID: 142
	reflect.TypeOf(recursion.ConsistencyCheck{}),                           // ID: 143
	reflect.TypeOf(recursion.RecursionCircuit{}),                           // ID: 144
	reflect.TypeOf(reedsolomon.ReedSolomonProverAction{}),                  // ID: 145
	reflect.TypeOf(reedsolomon.ReedSolomonVerifierAction{}),                // ID: 146
	reflect.TypeOf(selector.SubsampleProverAction{}),                       // ID: 147
	reflect.TypeOf(selector.SubsampleVerifierAction{}),                     // ID: 148
	reflect.TypeOf(selfrecursion.ColSelectionProverAction{}),               // ID: 149
	reflect.TypeOf(selfrecursion.CollapsingProverAction{}),                 // ID: 150
	reflect.TypeOf(selfrecursion.CollapsingVerifierAction{}),               // ID: 151
	reflect.TypeOf(selfrecursion.ConsistencyYsUalphaVerifierAction{}),      // ID: 152
	reflect.TypeOf(selfrecursion.FoldPhaseProverAction{}),                  // ID: 153
	reflect.TypeOf(selfrecursion.FoldPhaseVerifierAction{}),                // ID: 154
	reflect.TypeOf(selfrecursion.LinearHashMerkleProverAction{}),           // ID: 155
	reflect.TypeOf(selfrecursion.PreimageLimbsProverAction{}),              // ID: 156
	reflect.TypeOf(sha2.SHA2Circuit{}),                                     // ID: 157
	reflect.TypeOf(smartvectors.Constant{}),                                // ID: 158
	reflect.TypeOf(smartvectors.PaddedCircularWindow{}),                    // ID: 159
	reflect.TypeOf(smartvectors.Regular{}),                                 // ID: 160
	reflect.TypeOf(spaghettifier.Spaghettification{}),                      // ID: 161
	reflect.TypeOf(splitextension.AssignSplitColumnProverAction{}),         // ID: 162
	reflect.TypeOf(splitextension.AssignUnivProverAction{}),                // ID: 163
	reflect.TypeOf(splitextension.VerifierCtx{}),                           // ID: 164
	reflect.TypeOf(stitchsplit.AssignLocalPointProverAction{}),             // ID: 165
	reflect.TypeOf(stitchsplit.ProveRoundProverAction{}),                   // ID: 166
	reflect.TypeOf(stitchsplit.QueryVerifierAction{}),                      // ID: 167
	reflect.TypeOf(stitchsplit.SplitProverAction{}),                        // ID: 168
	reflect.TypeOf(stitchsplit.StitchColumnsProverAction{}),                // ID: 169
	reflect.TypeOf(stitchsplit.StitchSubColumnsProverAction{}),             // ID: 170
	reflect.TypeOf(string("")),                                             // ID: 171
	reflect.TypeOf(symbolic.Constant{}),                                    // ID: 172
	reflect.TypeOf(symbolic.LinComb{}),                                     // ID: 173
	reflect.TypeOf(symbolic.PolyEval{}),                                    // ID: 174
	reflect.TypeOf(symbolic.Product{}),                                     // ID: 175
	reflect.TypeOf(symbolic.StringVar("")),                                 // ID: 176
	reflect.TypeOf(symbolic.Variable{}),                                    // ID: 177
	reflect.TypeOf(uint(0)),                                                // ID: 178
	reflect.TypeOf(uint16(0)),                                              // ID: 179
	reflect.TypeOf(uint32(0)),                                              // ID: 180
	reflect.TypeOf(uint64(0)),                                              // ID: 181
	reflect.TypeOf(uint8(0)),                                               // ID: 182
	reflect.TypeOf(univariates.NaturalizeProverAction{}),                   // ID: 183
	reflect.TypeOf(univariates.NaturalizeVerifierAction{}),                 // ID: 184
	reflect.TypeOf(variables.PeriodicSample{}),                             // ID: 185
	reflect.TypeOf(variables.X{}),                                          // ID: 186
	reflect.TypeOf(verifiercol.ConstCol{}),                                 // ID: 187
	reflect.TypeOf(verifiercol.ExpandedProofOrVerifyingKeyColWithZero{}),   // ID: 188
	reflect.TypeOf(verifiercol.FromAccessors{}),                            // ID: 189
	reflect.TypeOf(verifiercol.FromYs{}),                                   // ID: 190
	reflect.TypeOf(verifiercol.RepeatedAccessor{}),                         // ID: 191
	reflect.TypeOf(vortex.ColumnAssignmentProverAction{}),                  // ID: 192
	reflect.TypeOf(vortex.Ctx{}),                                           // ID: 193
	reflect.TypeOf(vortex.ExplicitPolynomialEval{}),                        // ID: 194
	reflect.TypeOf(vortex.LinearCombinationComputationProverAction{}),      // ID: 195
	reflect.TypeOf(vortex.OpenSelectedColumnsProverAction{}),               // ID: 196
	reflect.TypeOf(vortex.ReassignPrecomputedRootAction{}),                 // ID: 197
	reflect.TypeOf(vortex.ShadowRowProverAction{}),                         // ID: 198
	reflect.TypeOf(vortex.VortexVerifierAction{}),                          // ID: 199
	reflect.TypeOf(zkded.AccumulateUpToMaxCtx{}),                           // ID: 200
	reflect.TypeOf(zkded.AssignPIPProverAction{}),                          // ID: 201
	reflect.TypeOf(zkded.LengthConsistencyCtx{}),                           // ID: 202
}

// TypeToID maps a reflect.Type to a uint16 ID.
// This is O(1) access for Serialization.
var TypeToID = map[reflect.Type]uint16{
	reflect.TypeOf(accessors.FromCoinAccessor{}):                           0,
	reflect.TypeOf(accessors.FromConstAccessor{}):                          1,
	reflect.TypeOf(accessors.FromExprAccessor{}):                           2,
	reflect.TypeOf(accessors.FromGrandProductAccessor{}):                   3,
	reflect.TypeOf(accessors.FromHornerAccessorFinalValue{}):               4,
	reflect.TypeOf(accessors.FromIntVecCoinPositionAccessor{}):             5,
	reflect.TypeOf(accessors.FromLocalOpeningYAccessor{}):                  6,
	reflect.TypeOf(accessors.FromLogDerivSumAccessor{}):                    7,
	reflect.TypeOf(accessors.FromPublicColumn{}):                           8,
	reflect.TypeOf(accessors.FromUnivXAccessor{}):                          9,
	reflect.TypeOf(bigrange.BigRangeProverAction{}):                        10,
	reflect.TypeOf(bls.MultiAddCircuitG1{}):                                11,
	reflect.TypeOf(bls.MultiAddCircuitG2{}):                                12,
	reflect.TypeOf(bls.MultiCheckableG1NonCurve{}):                         13,
	reflect.TypeOf(bls.MultiCheckableG1NonGroup{}):                         14,
	reflect.TypeOf(bls.MultiCheckableG2NonCurve{}):                         15,
	reflect.TypeOf(bls.MultiCheckableG2NonGroup{}):                         16,
	reflect.TypeOf(bls.MultiMapCircuitG1{}):                                17,
	reflect.TypeOf(bls.MultiMapCircuitG2{}):                                18,
	reflect.TypeOf(bls.MultiMillerLoopFinalExpCircuit{}):                   19,
	reflect.TypeOf(bls.MultiMillerLoopMulCircuit{}):                        20,
	reflect.TypeOf(bls.MultiMulCircuitG1{}):                                21,
	reflect.TypeOf(bls.MultiMulCircuitG2{}):                                22,
	reflect.TypeOf(bls.MultiPointEvalCircuit{}):                            23,
	reflect.TypeOf(bls.MultiPointEvalFailureCircuit{}):                     24,
	reflect.TypeOf(bool(false)):                                            25,
	reflect.TypeOf(byte32cmp.Bytes32CmpProverAction{}):                     26,
	reflect.TypeOf(byte32cmp.DecompositionCtx{}):                           27,
	reflect.TypeOf(byte32cmp.MultiLimbAdd{}):                               28,
	reflect.TypeOf(byte32cmp.MultiLimbCmp{}):                               29,
	reflect.TypeOf(byte32cmp.OneLimbCmpCtx{}):                              30,
	reflect.TypeOf(cleanup.CleanupProverAction{}):                          31,
	reflect.TypeOf(coin.Info{}):                                            32,
	reflect.TypeOf(coin.Name("")):                                          33,
	reflect.TypeOf(column.FakeColumn{}):                                    34,
	reflect.TypeOf(column.Natural{}):                                       35,
	reflect.TypeOf(column.Shifted{}):                                       36,
	reflect.TypeOf(common.HashingCtx{}):                                    37,
	reflect.TypeOf(dedicated.IsZeroCtx{}):                                  38,
	reflect.TypeOf(dedicated.StackedColumn{}):                              39,
	reflect.TypeOf(distributed.AssignLPPQueries{}):                         40,
	reflect.TypeOf(distributed.CheckNxHash{}):                              41,
	reflect.TypeOf(distributed.ConglomerationHierarchicalVerifierAction{}): 42,
	reflect.TypeOf(distributed.LPPSegmentBoundaryCalculator{}):             43,
	reflect.TypeOf(distributed.LppWitnessAssignment{}):                     44,
	reflect.TypeOf(distributed.ModuleGLAssignGL{}):                         45,
	reflect.TypeOf(distributed.ModuleGLAssignSendReceiveGlobal{}):          46,
	reflect.TypeOf(distributed.ModuleGLCheckSendReceiveGlobal{}):           47,
	reflect.TypeOf(distributed.SetInitialFSHash{}):                         48,
	reflect.TypeOf(distributed.StandardModuleDiscoverer{}):                 49,
	reflect.TypeOf(dposeidon2.LinearHashProverAction{}):                    50,
	reflect.TypeOf(dummy.DummyProverAction{}):                              51,
	reflect.TypeOf(dummy.DummyVerifierAction{}):                            52,
	reflect.TypeOf(ecarith.MultiECAddCircuit{}):                            53,
	reflect.TypeOf(ecarith.MultiECMulCircuit{}):                            54,
	reflect.TypeOf(ecdsa.MultiEcRecoverCircuit{}):                          55,
	reflect.TypeOf(ecpair.MultiG2GroupcheckCircuit{}):                      56,
	reflect.TypeOf(ecpair.MultiMillerLoopFinalExpCircuit{}):                57,
	reflect.TypeOf(ecpair.MultiMillerLoopMulCircuit{}):                     58,
	reflect.TypeOf(emulated.ProverActionFn{}):                              59,
	reflect.TypeOf(expr_handle.ExprHandleProverAction{}):                   60,
	reflect.TypeOf(fr.Element{}):                                           61,
	reflect.TypeOf(functionals.CoeffEvalProverAction{}):                    62,
	reflect.TypeOf(functionals.EvalBivariateProverAction{}):                63,
	reflect.TypeOf(functionals.FoldOuterProverAction{}):                    64,
	reflect.TypeOf(functionals.FoldOuterVerifierAction{}):                  65,
	reflect.TypeOf(functionals.FoldProverAction{}):                         66,
	reflect.TypeOf(functionals.FoldVerifierAction{}):                       67,
	reflect.TypeOf(functionals.InterpolationProverAction{}):                68,
	reflect.TypeOf(functionals.XYPow1MinNAccessor{}):                       69,
	reflect.TypeOf(gen_acc.GenericDataAccumulator{}):                       70,
	reflect.TypeOf(gen_acc.GenericInfoAccumulator{}):                       71,
	reflect.TypeOf(globalcs.EvaluationProver{}):                            72,
	reflect.TypeOf(globalcs.EvaluationVerifier{}):                          73,
	reflect.TypeOf(globalcs.QuotientCtx{}):                                 74,
	reflect.TypeOf(horner.AssignHornerCtx{}):                               75,
	reflect.TypeOf(horner.AssignHornerIP{}):                                76,
	reflect.TypeOf(horner.AssignHornerQuery{}):                             77,
	reflect.TypeOf(horner.CheckHornerQuery{}):                              78,
	reflect.TypeOf(horner.CheckHornerResult{}):                             79,
	reflect.TypeOf(ifaces.ColID("")):                                       80,
	reflect.TypeOf(ifaces.QueryID("")):                                     81,
	reflect.TypeOf(importpad.Importation{}):                                82,
	reflect.TypeOf(importpad.KeccakPadder{}):                               83,
	reflect.TypeOf(importpad.Sha2Padder{}):                                 84,
	reflect.TypeOf(innerproduct.ProverTask{}):                              85,
	reflect.TypeOf(innerproduct.VerifierForSize{}):                         86,
	reflect.TypeOf(int(0)):                                                 87,
	reflect.TypeOf(int16(0)):                                               88,
	reflect.TypeOf(int32(0)):                                               89,
	reflect.TypeOf(int64(0)):                                               90,
	reflect.TypeOf(int8(0)):                                                91,
	reflect.TypeOf(keccak.KeccakSingleProvider{}):                          92,
	reflect.TypeOf(keccak.ShakiraProverAction{}):                           93,
	reflect.TypeOf(limbs.LimbsBigEndian{}):                                 94,
	reflect.TypeOf(limbs.LimbsLittleEndian{}):                              95,
	reflect.TypeOf(logderivativesum.AssignLogDerivativeSumProverAction{}):  96,
	reflect.TypeOf(logderivativesum.CheckLogDerivativeSumMustBeZero{}):     97,
	reflect.TypeOf(logderivativesum.FinalEvaluationCheck{}):                98,
	reflect.TypeOf(logderivativesum.ProverTaskAtRound{}):                   99,
	reflect.TypeOf(merkle.MerkleProofProverAction{}):                       100,
	reflect.TypeOf(modexp.Modexp{}):                                        101,
	reflect.TypeOf(modexp.Module{}):                                        102,
	reflect.TypeOf(mpts.QuotientAccumulation{}):                            103,
	reflect.TypeOf(mpts.RandomPointEvaluation{}):                           104,
	reflect.TypeOf(mpts.ShadowRowProverAction{}):                           105,
	reflect.TypeOf(mpts.VerifierAction{}):                                  106,
	reflect.TypeOf(p256verify.MultiP256VerifyInstanceCircuit{}):            107,
	reflect.TypeOf(packing.Packing{}):                                      108,
	reflect.TypeOf(permutation.AssignPermutationGrandProduct{}):            109,
	reflect.TypeOf(permutation.CheckGrandProductIsOne{}):                   110,
	reflect.TypeOf(permutation.FinalProductCheck{}):                        111,
	reflect.TypeOf(permutation.ProverTaskAtRound{}):                        112,
	reflect.TypeOf(plonkinternal.CheckingActivators{}):                     113,
	reflect.TypeOf(plonkinternal.InitialBBSProverAction{}):                 114,
	reflect.TypeOf(plonkinternal.LROCommitProverAction{}):                  115,
	reflect.TypeOf(plonkinternal.PlonkNoCommitProverAction{}):              116,
	reflect.TypeOf(plonkinwizard.AssignSelOpening{}):                       117,
	reflect.TypeOf(plonkinwizard.CheckActivatorAndMask{}):                  118,
	reflect.TypeOf(plonkinwizard.CircAssignment{}):                         119,
	reflect.TypeOf(poseidon2.Poseidon2Context{}):                           120,
	reflect.TypeOf(query.FixedPermutation{}):                               121,
	reflect.TypeOf(query.GlobalConstraint{}):                               122,
	reflect.TypeOf(query.GrandProductParams{}):                             123,
	reflect.TypeOf(query.GrandProduct{}):                                   124,
	reflect.TypeOf(query.Horner{}):                                         125,
	reflect.TypeOf(query.Inclusion{}):                                      126,
	reflect.TypeOf(query.InnerProductParams{}):                             127,
	reflect.TypeOf(query.InnerProduct{}):                                   128,
	reflect.TypeOf(query.LocalConstraint{}):                                129,
	reflect.TypeOf(query.LocalOpeningParams{}):                             130,
	reflect.TypeOf(query.LocalOpening{}):                                   131,
	reflect.TypeOf(query.LogDerivSumParams{}):                              132,
	reflect.TypeOf(query.LogDerivativeSum{}):                               133,
	reflect.TypeOf(query.Permutation{}):                                    134,
	reflect.TypeOf(query.PlonkInWizard{}):                                  135,
	reflect.TypeOf(query.Poseidon2{}):                                      136,
	reflect.TypeOf(query.Projection{}):                                     137,
	reflect.TypeOf(query.Range{}):                                          138,
	reflect.TypeOf(query.UnivariateEvalParams{}):                           139,
	reflect.TypeOf(query.UnivariateEval{}):                                 140,
	reflect.TypeOf(recursion.AssignVortexOpenedCols{}):                     141,
	reflect.TypeOf(recursion.AssignVortexUAlpha{}):                         142,
	reflect.TypeOf(recursion.ConsistencyCheck{}):                           143,
	reflect.TypeOf(recursion.RecursionCircuit{}):                           144,
	reflect.TypeOf(reedsolomon.ReedSolomonProverAction{}):                  145,
	reflect.TypeOf(reedsolomon.ReedSolomonVerifierAction{}):                146,
	reflect.TypeOf(selector.SubsampleProverAction{}):                       147,
	reflect.TypeOf(selector.SubsampleVerifierAction{}):                     148,
	reflect.TypeOf(selfrecursion.ColSelectionProverAction{}):               149,
	reflect.TypeOf(selfrecursion.CollapsingProverAction{}):                 150,
	reflect.TypeOf(selfrecursion.CollapsingVerifierAction{}):               151,
	reflect.TypeOf(selfrecursion.ConsistencyYsUalphaVerifierAction{}):      152,
	reflect.TypeOf(selfrecursion.FoldPhaseProverAction{}):                  153,
	reflect.TypeOf(selfrecursion.FoldPhaseVerifierAction{}):                154,
	reflect.TypeOf(selfrecursion.LinearHashMerkleProverAction{}):           155,
	reflect.TypeOf(selfrecursion.PreimageLimbsProverAction{}):              156,
	reflect.TypeOf(sha2.SHA2Circuit{}):                                     157,
	reflect.TypeOf(smartvectors.Constant{}):                                158,
	reflect.TypeOf(smartvectors.PaddedCircularWindow{}):                    159,
	reflect.TypeOf(smartvectors.Regular{}):                                 160,
	reflect.TypeOf(spaghettifier.Spaghettification{}):                      161,
	reflect.TypeOf(splitextension.AssignSplitColumnProverAction{}):         162,
	reflect.TypeOf(splitextension.AssignUnivProverAction{}):                163,
	reflect.TypeOf(splitextension.VerifierCtx{}):                           164,
	reflect.TypeOf(stitchsplit.AssignLocalPointProverAction{}):             165,
	reflect.TypeOf(stitchsplit.ProveRoundProverAction{}):                   166,
	reflect.TypeOf(stitchsplit.QueryVerifierAction{}):                      167,
	reflect.TypeOf(stitchsplit.SplitProverAction{}):                        168,
	reflect.TypeOf(stitchsplit.StitchColumnsProverAction{}):                169,
	reflect.TypeOf(stitchsplit.StitchSubColumnsProverAction{}):             170,
	reflect.TypeOf(string("")):                                             171,
	reflect.TypeOf(symbolic.Constant{}):                                    172,
	reflect.TypeOf(symbolic.LinComb{}):                                     173,
	reflect.TypeOf(symbolic.PolyEval{}):                                    174,
	reflect.TypeOf(symbolic.Product{}):                                     175,
	reflect.TypeOf(symbolic.StringVar("")):                                 176,
	reflect.TypeOf(symbolic.Variable{}):                                    177,
	reflect.TypeOf(uint(0)):                                                178,
	reflect.TypeOf(uint16(0)):                                              179,
	reflect.TypeOf(uint32(0)):                                              180,
	reflect.TypeOf(uint64(0)):                                              181,
	reflect.TypeOf(uint8(0)):                                               182,
	reflect.TypeOf(univariates.NaturalizeProverAction{}):                   183,
	reflect.TypeOf(univariates.NaturalizeVerifierAction{}):                 184,
	reflect.TypeOf(variables.PeriodicSample{}):                             185,
	reflect.TypeOf(variables.X{}):                                          186,
	reflect.TypeOf(verifiercol.ConstCol{}):                                 187,
	reflect.TypeOf(verifiercol.ExpandedProofOrVerifyingKeyColWithZero{}):   188,
	reflect.TypeOf(verifiercol.FromAccessors{}):                            189,
	reflect.TypeOf(verifiercol.FromYs{}):                                   190,
	reflect.TypeOf(verifiercol.RepeatedAccessor{}):                         191,
	reflect.TypeOf(vortex.ColumnAssignmentProverAction{}):                  192,
	reflect.TypeOf(vortex.Ctx{}):                                           193,
	reflect.TypeOf(vortex.ExplicitPolynomialEval{}):                        194,
	reflect.TypeOf(vortex.LinearCombinationComputationProverAction{}):      195,
	reflect.TypeOf(vortex.OpenSelectedColumnsProverAction{}):               196,
	reflect.TypeOf(vortex.ReassignPrecomputedRootAction{}):                 197,
	reflect.TypeOf(vortex.ShadowRowProverAction{}):                         198,
	reflect.TypeOf(vortex.VortexVerifierAction{}):                          199,
	reflect.TypeOf(zkded.AccumulateUpToMaxCtx{}):                           200,
	reflect.TypeOf(zkded.AssignPIPProverAction{}):                          201,
	reflect.TypeOf(zkded.LengthConsistencyCtx{}):                           202,
}
