(module shakira)

(defconst 
  PHASE_SHA2_DATA         1
  PHASE_SHA2_RESULT       2
  PHASE_RIPEMD_DATA       3
  PHASE_RIPEMD_RESULT     4
  PHASE_KECCAK_DATA       5
  PHASE_KECCAK_RESULT     6
  INDEX_MAX_SHA2_DATA     11
  INDEX_MAX_SHA2_RESULT   1
  INDEX_MAX_RIPEMD_DATA   3
  INDEX_MAX_RIPEMD_RESULT 1
  INDEX_MAX_KECCAK_DATA   0
  INDEX_MAX_KECCAK_RESULT 1)

