(module rlptxrcpt)

(defconst
  SUBPHASE_ID_WEIGHT_IS_PREFIX   6
  SUBPHASE_ID_WEIGHT_IS_OT       12
  SUBPHASE_ID_WEIGHT_IS_OD       24
  SUBPHASE_ID_WEIGHT_DEPTH       48
  SUBPHASE_ID_WEIGHT_INDEX_LOCAL 96)


