module.exports = {
  preset: "ts-jest",
  testEnvironment: "node",
  rootDir: ".",
  testRegex: ".test.ts$",
  globalSetup: "<rootDir>/test/global-setup.ts",
  globalTeardown: "<rootDir>/test/global-teardown.ts",
  verbose: true,
  collectCoverage: true,
  coverageProvider: "v8",
  collectCoverageFrom: [
    "dist/commands/**/*.js",
    "dist/utils/common/custom-flags.js",
    "dist/utils/common/validation.js",
    "dist/utils/eth-transfer/**/*.js",
    "dist/utils/submit-invoice/custom-flags.js",
    "dist/utils/submit-invoice/time.js",
    "dist/utils/synctx/**/*.js",
  ],
  coverageReporters: ["html", "lcov", "text"],
  testPathIgnorePatterns: [],
  coveragePathIgnorePatterns: [],
};
