(module rlptxn)

(defun (upcoming-phase-transition-type-0)
    (force-bin (+
        (* IS_RLP_PREFIX                (next IS_NONCE                   ))
        ;; (* IS_CHAIN_ID                  (next IS_CHAIN_ID                ))
        (* IS_NONCE                     (next IS_GAS_PRICE               ))
        (* IS_GAS_PRICE                 (next IS_GAS_LIMIT               ))
        ;; (* IS_MAX_PRIORITY_FEE_PER_GAS  (next IS_MAX_PRIORITY_FEE_PER_GAS))
        ;; (* IS_MAX_FEE_PER_GAS           (next IS_MAX_FEE_PER_GAS         ))
        (* IS_GAS_LIMIT                 (next IS_TO                      ))
        (* IS_TO                        (next IS_VALUE                   ))
        (* IS_VALUE                     (next IS_DATA                    ))
        (* IS_DATA                      (next IS_BETA                    ))
        ;; (* IS_ACCESS_LIST               (next IS_ACCESS_LIST             ))
        (* IS_BETA                      (next IS_R                       ))
        ;; (* IS_Y                         (next IS_Y                       ))
        (* IS_R                         (next IS_S                       ))
        (* IS_S                         (next IS_RLP_PREFIX              ))
    )))

(defun (will-remain-in-same-phase-type-0)
    (force-bin (+
        (* IS_RLP_PREFIX                (next IS_RLP_PREFIX              ))
        ;; (* IS_CHAIN_ID                  (next IS_CHAIN_ID                ))
        (* IS_NONCE                     (next IS_NONCE                   ))
        (* IS_GAS_PRICE                 (next IS_GAS_PRICE               ))
        ;; (* IS_MAX_PRIORITY_FEE_PER_GAS  (next IS_MAX_PRIORITY_FEE_PER_GAS))
        ;; (* IS_MAX_FEE_PER_GAS           (next IS_MAX_FEE_PER_GAS         ))
        (* IS_GAS_LIMIT                 (next IS_GAS_LIMIT               ))
        (* IS_TO                        (next IS_TO                      ))
        (* IS_VALUE                     (next IS_VALUE                   ))
        (* IS_DATA                      (next IS_DATA                    ))
        ;; (* IS_ACCESS_LIST               (next IS_ACCESS_LIST             ))
        (* IS_BETA                      (next IS_BETA                    ))
        ;; (* IS_Y                         (next IS_Y                       ))
        (* IS_R                         (next IS_R                       ))
        (* IS_S                         (next IS_S                       ))
    )))

(defun (upcoming-phase-transition-type-1)
    (force-bin (+
        (* IS_RLP_PREFIX                (next IS_CHAIN_ID                ))
        (* IS_CHAIN_ID                  (next IS_NONCE                   ))
        (* IS_NONCE                     (next IS_GAS_PRICE               ))
        (* IS_GAS_PRICE                 (next IS_GAS_LIMIT               ))
        ;; (* IS_MAX_PRIORITY_FEE_PER_GAS  (next IS_MAX_PRIORITY_FEE_PER_GAS))
        ;; (* IS_MAX_FEE_PER_GAS           (next IS_MAX_FEE_PER_GAS         ))
        (* IS_GAS_LIMIT                 (next IS_TO                      ))
        (* IS_TO                        (next IS_VALUE                   ))
        (* IS_VALUE                     (next IS_DATA                    ))
        (* IS_DATA                      (next IS_ACCESS_LIST             ))
        (* IS_ACCESS_LIST               (next IS_Y                       ))
        ;; (* IS_BETA                      (next IS_BETA                 ))
        (* IS_Y                         (next IS_R                       ))
        (* IS_R                         (next IS_S                       ))
        (* IS_S                         (next IS_RLP_PREFIX              ))
    )))

(defun (will-remain-in-same-phase-type-1)
    (force-bin (+
        (* IS_RLP_PREFIX                (next IS_RLP_PREFIX              ))
        (* IS_CHAIN_ID                  (next IS_CHAIN_ID                ))
        (* IS_NONCE                     (next IS_NONCE                   ))
        (* IS_GAS_PRICE                 (next IS_GAS_PRICE               ))
        ;; (* IS_MAX_PRIORITY_FEE_PER_GAS  (next IS_MAX_PRIORITY_FEE_PER_GAS))
        ;; (* IS_MAX_FEE_PER_GAS           (next IS_MAX_FEE_PER_GAS         ))
        (* IS_GAS_LIMIT                 (next IS_GAS_LIMIT               ))
        (* IS_TO                        (next IS_TO                      ))
        (* IS_VALUE                     (next IS_VALUE                   ))
        (* IS_DATA                      (next IS_DATA                    ))
        (* IS_ACCESS_LIST               (next IS_ACCESS_LIST             ))
        ;; (* IS_BETA                      (next IS_BETA                    ))
        (* IS_Y                         (next IS_Y                       ))
        (* IS_R                         (next IS_R                       ))
        (* IS_S                         (next IS_S                       ))
    )))

(defun (upcoming-phase-transition-type-2)
    (force-bin (+
        (* IS_RLP_PREFIX                (next IS_CHAIN_ID                ))
        (* IS_CHAIN_ID                  (next IS_NONCE                   ))
        (* IS_NONCE                     (next IS_MAX_PRIORITY_FEE_PER_GAS))
        ;; (* IS_GAS_PRICE                 (next IS_GAS_LIMITs               ))
        (* IS_MAX_PRIORITY_FEE_PER_GAS  (next IS_MAX_FEE_PER_GAS         ))
        (* IS_MAX_FEE_PER_GAS           (next IS_GAS_LIMIT               ))
        (* IS_GAS_LIMIT                 (next IS_TO                      ))
        (* IS_TO                        (next IS_VALUE                   ))
        (* IS_VALUE                     (next IS_DATA                    ))
        (* IS_DATA                      (next IS_ACCESS_LIST             ))
        (* IS_ACCESS_LIST               (next IS_Y                       ))
        ;; (* IS_BETA                      (next IS_BETA                 ))
        (* IS_Y                         (next IS_R                       ))
        (* IS_R                         (next IS_S                       ))
        (* IS_S                         (next IS_RLP_PREFIX              ))
    )))

(defun (will-remain-in-same-phase-type-2)
    (force-bin (+
        (* IS_RLP_PREFIX                (next IS_RLP_PREFIX              ))
        (* IS_CHAIN_ID                  (next IS_CHAIN_ID                ))
        (* IS_NONCE                     (next IS_NONCE                   ))
        ;; (* IS_GAS_PRICE                 (next IS_GAS_PRICE               ))
        (* IS_MAX_PRIORITY_FEE_PER_GAS  (next IS_MAX_PRIORITY_FEE_PER_GAS))
        (* IS_MAX_FEE_PER_GAS           (next IS_MAX_FEE_PER_GAS         ))
        (* IS_GAS_LIMIT                 (next IS_GAS_LIMIT               ))
        (* IS_TO                        (next IS_TO                      ))
        (* IS_VALUE                     (next IS_VALUE                   ))
        (* IS_DATA                      (next IS_DATA                    ))
        (* IS_ACCESS_LIST               (next IS_ACCESS_LIST             ))
        ;; (* IS_BETA                      (next IS_BETA                    ))
        (* IS_Y                         (next IS_Y                       ))
        (* IS_R                         (next IS_R                       ))
        (* IS_S                         (next IS_S                       ))
    )))

;; this shorthand isn't defined in the spec AFAICT
(defun (upcoming-phase-transition) 
        (force-bin (+ (* (upcoming-phase-transition-type-0) TYPE_0) 
                      (* (upcoming-phase-transition-type-1) TYPE_1) 
                      (* (upcoming-phase-transition-type-2) TYPE_2))))

(defconstraint type-0-phases ()
    (if-not-zero TYPE_0 (eq! (+ (upcoming-phase-transition-type-0) (will-remain-in-same-phase-type-0)) 1)))

(defconstraint type-1-phases ()
    (if-not-zero TYPE_1 (eq! (+ (upcoming-phase-transition-type-1) (will-remain-in-same-phase-type-1)) 1)))

(defconstraint type-2-phases ()
    (if-not-zero TYPE_2 (eq! (+ (upcoming-phase-transition-type-2) (will-remain-in-same-phase-type-2)) 1)))
