/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IZkEvmV2, IZkEvmV2Interface } from "../../../rollup/interfaces/IZkEvmV2.js";

  const _abi = [
  {
    "inputs": [],
    "name": "InvalidProof",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "string",
        "name": "errorReason",
        "type": "string"
      }
    ],
    "name": "InvalidProofOrProofVerificationRanOutOfGas",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InvalidProofType",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "ProofIsEmpty",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "StartingRootHashDoesNotMatch",
    "type": "error"
  }
] as const;

  export class IZkEvmV2__factory {
    static readonly abi = _abi;
    static createInterface(): IZkEvmV2Interface {
      return new Interface(_abi) as IZkEvmV2Interface;
    }
    static connect(address: string, runner?: ContractRunner | null): IZkEvmV2 {
      return new Contract(address, _abi, runner) as unknown as IZkEvmV2;
    }
  }
  