services:
  prover-v3:
    extends:
      file: compose-spec-l2-services.yml
      service: prover-v3
    environment:
      GOMAXPROCS: 16
      CONFIG_FILE: "/opt/linea/prover/config.toml"
      GOMEMLIMIT: "110GiB"
      WORKER_ID: prover-i1 # keep this prover- to mimic prod env prover-aggregation-91
    volumes:
      - ../tmp/local/:/data/
      - logs:/logs
      - ./config/prover/v3/prover-config-partial.toml:/opt/linea/prover/config.toml:ro
      - ../prover/prover-assets:/opt/linea/prover/prover-assets:ro

  coordinator:
    extends:
      file: compose-spec-l2-services.yml
      service: coordinator
    environment:
      CONFIG_OVERRIDE_OPTS: >-
        -Dconfig.override.type2-state-proof-provider.disabled=${LINEA_COORDINATOR_DISABLE_TYPE2_STATE_PROOF_PROVIDER:-true}
        -Dconfig.override.l1-submission.blob.signer.type=${LINEA_COORDINATOR_SIGNER_TYPE:-web3j}
        -Dconfig.override.l1-submission.aggregation.signer.type=${LINEA_COORDINATOR_SIGNER_TYPE:-web3j}
        -Dconfig.override.message-anchoring.signer.type=${LINEA_COORDINATOR_SIGNER_TYPE:-web3j}
        -Dconfig.override.l1-submission.data-availability=${LINEA_COORDINATOR_DATA_AVAILABILITY:-ROLLUP}
        -Dconfig.override.conflation.blocks-limit=10
        -Dconfig.override.conflation.conflation-deadline="PT30M"
        -Dconfig.override.conflation.blob-compression.batches-limit=2
        -Dconfig.override.conflation.proof-aggregation.deadline="PT30M"
        ${LINEA_SHOMEI_TAG:+-Dconfig.override.state-manager.version=$LINEA_SHOMEI_TAG}

