include:
  - compose-tracing-v2.yml

services:
  web3signer:
    extends:
      file: compose-spec-l2-services.yml
      service: web3signer

  shomei-frontend:
    extends:
      file: compose-spec-l2-services.yml
      service: shomei-frontend

  postman:
    extends:
      file: compose-spec-l2-services.yml
      service: postman

  transaction-exclusion-api:
    extends:
      file: compose-spec-l2-services.yml
      service: transaction-exclusion-api

  l2-node-besu-leader:
    extends:
      file: compose-spec-l2-services.yml
      service: l2-node-besu-leader
    image: consensys/linea-besu-package-with-fleet:${BESU_PACKAGE_TAG:-beta-v4.4-rc7.4-20260210173356-7d711e6}

  l2-node-besu-follower:
    extends:
      file: compose-spec-l2-services.yml
      service: l2-node-besu-follower
    image: consensys/linea-besu-package-with-fleet:${BESU_PACKAGE_TAG:-beta-v4.4-rc7.4-20260210173356-7d711e6}
