#!/bin/sh
# L2 genesis init for the linea-stack public quickstart.
#
# Renders genesis-maru.json + genesis-besu.json from their .template files by
# substituting:
#   - %FORK_TIME%                    — boot-time UNIX timestamp + 60s
#   - __L2_MESSAGE_SERVICE_ADDRESS__ — precomputed by account-setup
#   - __L2_DEPLOYER_ADDRESS__        — generated by account-setup
#
# Idempotent guard lives in the docker-compose entrypoint (l2-genesis-init), not
# in this file. Re-running this script unconditionally would change the fork
# timestamp and break any existing on-disk chaindata.
set -e

echo "[l2-genesis-init] rendering Maru + Besu L2 genesis"
date
cd /initialization

PRECOMPUTED="/shared/addresses-precomputed.json"
if [ ! -f "$PRECOMPUTED" ]; then
  echo "[l2-genesis-init] FATAL: $PRECOMPUTED not found — account-setup must run first" >&2
  exit 1
fi

L2_MS_ADDR=$(sed -nE 's/.*"L2MessageService":[[:space:]]*"(0x[a-fA-F0-9]{40})".*/\1/p' "$PRECOMPUTED" | head -1)
L2_DEPLOYER_ADDR=$(sed -nE 's/.*"l2DeployerAddress":[[:space:]]*"(0x[a-fA-F0-9]{40})".*/\1/p' "$PRECOMPUTED" | head -1)

if ! echo "$L2_MS_ADDR" | grep -qE '^0x[a-fA-F0-9]{40}$'; then
  echo "[l2-genesis-init] FATAL: could not extract L2MessageService address from $PRECOMPUTED" >&2
  echo "[l2-genesis-init] (got: '$L2_MS_ADDR')" >&2
  exit 1
fi
if ! echo "$L2_DEPLOYER_ADDR" | grep -qE '^0x[a-fA-F0-9]{40}$'; then
  echo "[l2-genesis-init] FATAL: could not extract l2DeployerAddress from $PRECOMPUTED" >&2
  echo "[l2-genesis-init] (got: '$L2_DEPLOYER_ADDR')" >&2
  exit 1
fi

echo "[l2-genesis-init] L2_MESSAGE_SERVICE_ADDRESS=$L2_MS_ADDR"
echo "[l2-genesis-init] L2_DEPLOYER_ADDRESS=$L2_DEPLOYER_ADDR"

cp -T "genesis-maru.json.template" "genesis-maru.json"
cp -T "genesis-besu.json.template" "genesis-besu.json"

fork_timestamp=$(($(date +%s) + 60))
echo "[l2-genesis-init] FORK_TIME=$fork_timestamp"
sed -i "s/%FORK_TIME%/$fork_timestamp/g" genesis-maru.json
sed -i "s/%FORK_TIME%/$fork_timestamp/g" genesis-besu.json
sed -i "s|__L2_MESSAGE_SERVICE_ADDRESS__|$L2_MS_ADDR|g" genesis-besu.json
sed -i "s|__L2_DEPLOYER_ADDRESS__|$L2_DEPLOYER_ADDR|g" genesis-besu.json

if grep -qE "__L2_(MESSAGE_SERVICE|DEPLOYER)_ADDRESS__" genesis-besu.json; then
  echo "[l2-genesis-init] FATAL: L2 address placeholder still present after substitution" >&2
  exit 1
fi

echo "$fork_timestamp" > /initialization/fork-timestamp.txt
echo "[l2-genesis-init] done"
