/*
 * Copyright ConsenSys Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
 * an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

package net.consensys.linea.zktracer.module.limits;

public enum CountingModuleName {
  PRECOMPILE_ECPAIRING_G2_MEMBERSHIP_CALLS,
  PRECOMPILE_ECRECOVER_EFFECTIVE_CALLS,
  PRECOMPILE_ECMUL_EFFECTIVE_CALLS,
  PRECOMPILE_ECADD_EFFECTIVE_CALLS,
  PRECOMPILE_ECPAIRING_MILLER_LOOPS,
  PRECOMPILE_ECPAIRING_FINAL_EXPONENTIATIONS,
  PRECOMPILE_BLAKE_EFFECTIVE_CALLS,
  PRECOMPILE_MODEXP_EFFECTIVE_CALLS,
  POINT_EVAL,
  BLS,
  PRECOMPILE_BLS_POINT_EVALUATION_EFFECTIVE_CALLS,
  PRECOMPILE_POINT_EVALUATION_FAILURE_EFFECTIVE_CALLS,
  PRECOMPILE_BLS_G1_ADD_EFFECTIVE_CALLS,
  PRECOMPILE_BLS_G1_MSM_EFFECTIVE_CALLS,
  PRECOMPILE_BLS_G2_ADD_EFFECTIVE_CALLS,
  PRECOMPILE_BLS_G2_MSM_EFFECTIVE_CALLS,
  PRECOMPILE_BLS_PAIRING_CHECK_MILLER_LOOPS,
  PRECOMPILE_BLS_FINAL_EXPONENTIATIONS,
  PRECOMPILE_BLS_MAP_FP_TO_G1_EFFECTIVE_CALLS,
  PRECOMPILE_BLS_MAP_FP2_TO_G2_EFFECTIVE_CALLS,
  PRECOMPILE_BLS_C1_MEMBERSHIP_CHECKS,
  PRECOMPILE_BLS_C2_MEMBERSHIP_CALLS,
  PRECOMPILE_BLS_G1_MEMBERSHIP_CALLS,
  PRECOMPILE_BLS_G2_MEMBERSHIP_CALLS,
  BLOCK_L2_L1_LOGS,
  BLOCK_TRANSACTIONS,
  BLOCK_KECCAK,
  PRECOMPILE_BLAKE_ROUNDS,
  PRECOMPILE_RIPEMD_BLOCKS,
  PRECOMPILE_SHA2_BLOCKS,
  MODEXP,
  RIP,
  BLAKE,
  BLS_DATA,
  BLS_REFERENCE_TABLE,
  RLP_UTILS,
  POWER_REFERENCE_TABLE
}
