/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ITestExternalCalls__factory } from './ITestExternalCalls__factory.js';
export { TestExternalCalls__factory } from './TestExternalCalls__factory.js';