package net.consensys.linea.traces

sealed interface TracingModule {
  val name: String
}

enum class TracingModuleV2 : TracingModule {
  // EMV Module limits
  ADD,
  BIN,
  BLAKE_MODEXP_DATA,
  BLOCK_DATA,
  BLOCK_HASH,
  EC_DATA,
  EUC,
  EXP,
  EXT,
  GAS,
  HUB,
  LOG_DATA,
  LOG_INFO,
  MMIO,
  MMU,
  MOD,
  MUL,
  MXP,
  OOB,
  RLP_ADDR,
  RLP_TXN,
  RLP_TXN_RCPT,
  ROM,
  ROM_LEX,
  SHAKIRA_DATA,
  SHF,
  STP,
  TRM,
  TXN_DATA,
  WCP,

  // Reference table limits
  BIN_REFERENCE_TABLE,
  SHF_REFERENCE_TABLE,
  INSTRUCTION_DECODER,

  // Precompiles call limits
  PRECOMPILE_ECRECOVER_EFFECTIVE_CALLS,
  PRECOMPILE_SHA2_BLOCKS,
  PRECOMPILE_RIPEMD_BLOCKS,
  PRECOMPILE_MODEXP_EFFECTIVE_CALLS,
  PRECOMPILE_ECADD_EFFECTIVE_CALLS,
  PRECOMPILE_ECMUL_EFFECTIVE_CALLS,
  PRECOMPILE_ECPAIRING_FINAL_EXPONENTIATIONS,
  PRECOMPILE_ECPAIRING_G2_MEMBERSHIP_CALLS,
  PRECOMPILE_ECPAIRING_MILLER_LOOPS,
  PRECOMPILE_BLAKE_EFFECTIVE_CALLS,
  PRECOMPILE_BLAKE_ROUNDS,

  // Precompiles introduced from beta-v4.0-rc6-CANCUN
  PRECOMPILE_BLS_POINT_EVALUATION_EFFECTIVE_CALLS,
  PRECOMPILE_POINT_EVALUATION_FAILURE_EFFECTIVE_CALLS,
  PRECOMPILE_BLS_G1_ADD_EFFECTIVE_CALLS,
  PRECOMPILE_BLS_G1_MSM_EFFECTIVE_CALLS,
  PRECOMPILE_BLS_G2_ADD_EFFECTIVE_CALLS,
  PRECOMPILE_BLS_G2_MSM_EFFECTIVE_CALLS,
  PRECOMPILE_BLS_PAIRING_CHECK_MILLER_LOOPS,
  PRECOMPILE_BLS_FINAL_EXPONENTIATIONS,
  PRECOMPILE_BLS_MAP_FP_TO_G1_EFFECTIVE_CALLS,
  PRECOMPILE_BLS_MAP_FP2_TO_G2_EFFECTIVE_CALLS,
  PRECOMPILE_BLS_C1_MEMBERSHIP_CHECKS,
  PRECOMPILE_BLS_C2_MEMBERSHIP_CALLS,
  PRECOMPILE_BLS_G1_MEMBERSHIP_CALLS,
  PRECOMPILE_BLS_G2_MEMBERSHIP_CALLS,

  // Block-specific limits
  BLOCK_KECCAK,
  BLOCK_L1_SIZE,
  BLOCK_L2_L1_LOGS,
  BLOCK_TRANSACTIONS,

  // Introduced by limitless proof
  BLS,
  RIP,
  MODEXP,
  BLAKE,
  POINT_EVAL,

  // Introduced from beta-v4.0-rc6-CANCUN and present on Cancun
  BLS_DATA,
  RLP_UTILS,
  POWER_REFERENCE_TABLE,
  BLS_REFERENCE_TABLE,
  ;

  companion object {
    val evmModules: Set<TracingModuleV2> = setOf(
      ADD,
      BIN,
      BLAKE_MODEXP_DATA,
      BLOCK_DATA,
      BLOCK_HASH,
      EC_DATA,
      EUC,
      EXP,
      EXT,
      GAS,
      HUB,
      LOG_DATA,
      LOG_INFO,
      MMIO,
      MMU,
      MOD,
      MUL,
      MXP,
      OOB,
      RLP_ADDR,
      RLP_TXN,
      RLP_TXN_RCPT,
      ROM,
      ROM_LEX,
      SHAKIRA_DATA,
      SHF,
      STP,
      TRM,
      TXN_DATA,
      WCP,
      BLS,
      RIP,
      MODEXP,
      BLAKE,
      POINT_EVAL,
      BLS_DATA,
      RLP_UTILS,
    )
  }
}
