(module txnData)

(defcolumns 
  ABS_TX_NUM_MAX
  ABS_TX_NUM
  BTC_NUM_MAX
  BTC_NUM
  REL_TX_NUM_MAX
  REL_TX_NUM
  CT
  FROM_HI
  FROM_LO
  NONCE
  INITIAL_BALANCE
  VALUE
  TO_HI
  TO_LO
  (IS_DEP :boolean)
  GAS_LIMIT
  INITIAL_GAS
  GAS_PRICE
  BASEFEE
  COINBASE_HI
  COINBASE_LO
  CALL_DATA_SIZE
  INIT_CODE_SIZE
  (TYPE0 :boolean)
  (TYPE1 :boolean)
  (TYPE2 :boolean)
  (REQUIRES_EVM_EXECUTION :boolean)
  LEFTOVER_GAS
  REFUND_COUNTER
  REFUND_AMOUNT
  CUMULATIVE_CONSUMED_GAS
  (STATUS_CODE :boolean)
  PHASE_RLP_TXN
  PHASE_RLP_TXNRCPT
  CODE_FRAGMENT_INDEX
  OUTGOING_HI
  OUTGOING_LO
  OUTGOING_RLP_TXNRCPT
  WCP_ARG_ONE_LO
  WCP_ARG_TWO_LO
  (WCP_RES_LO :boolean)
  WCP_INST)

(defalias 
  ABS_MAX ABS_TX_NUM_MAX
  ABS     ABS_TX_NUM
  BTC_MAX BTC_NUM_MAX
  BTC     BTC_NUM
  REL_MAX REL_TX_NUM_MAX
  REL     REL_TX_NUM
  REQ_EVM REQUIRES_EVM_EXECUTION
  CUM_GAS CUMULATIVE_CONSUMED_GAS
  CFI     CODE_FRAGMENT_INDEX
  REF_CNT REFUND_COUNTER
  REF_AMT REFUND_AMOUNT
  IGAS    INITIAL_GAS
  IBAL    INITIAL_BALANCE
  GLIM    GAS_LIMIT
  GPRC    GAS_PRICE)


