(module txnData)

(defconst 
  NB_ROWS_TYPE_0                7
  NB_ROWS_TYPE_1                8
  NB_ROWS_TYPE_2                8
  ;;
  COMMON_RLP_TXN_PHASE_NUMBER_0 RLP_TXN_PHASE_RLP_PREFIX_VALUE
  COMMON_RLP_TXN_PHASE_NUMBER_1 RLP_TXN_PHASE_TO_VALUE
  COMMON_RLP_TXN_PHASE_NUMBER_2 RLP_TXN_PHASE_NONCE_VALUE
  COMMON_RLP_TXN_PHASE_NUMBER_3 RLP_TXN_PHASE_VALUE_VALUE
  COMMON_RLP_TXN_PHASE_NUMBER_4 RLP_TXN_PHASE_DATA_VALUE
  COMMON_RLP_TXN_PHASE_NUMBER_5 RLP_TXN_PHASE_GAS_LIMIT_VALUE
  TYPE_0_RLP_TXN_PHASE_NUMBER_6 RLP_TXN_PHASE_GAS_PRICE_VALUE
  TYPE_1_RLP_TXN_PHASE_NUMBER_6 RLP_TXN_PHASE_GAS_PRICE_VALUE
  TYPE_1_RLP_TXN_PHASE_NUMBER_7 RLP_TXN_PHASE_ACCESS_LIST_VALUE
  TYPE_2_RLP_TXN_PHASE_NUMBER_6 RLP_TXN_PHASE_MAX_FEE_PER_GAS_VALUE
  TYPE_2_RLP_TXN_PHASE_NUMBER_7 RLP_TXN_PHASE_ACCESS_LIST_VALUE)


