(module oob)

(defcolumns
  (STAMP :i32)
  (CT :i3)
  (CT_MAX :i3)
  (DATA :i128 :array [9]) ;; XXXXXX 9 -> 10
  (OOB_INST :i16)
  (IS_JUMP :binary@prove)
  (IS_JUMPI :binary@prove)
  (IS_RDC :binary@prove)
  (IS_CDL :binary@prove)
  (IS_XCALL :binary@prove)
  (IS_CALL :binary@prove)
  ;; (IS_XCREATE :binary@prove) ;; XXXXXX
  (IS_CREATE :binary@prove)
  (IS_SSTORE :binary@prove)
  (IS_DEPLOYMENT :binary@prove)
  (IS_ECRECOVER :binary@prove)
  (IS_SHA2 :binary@prove)
  (IS_RIPEMD :binary@prove)
  (IS_IDENTITY :binary@prove)
  (IS_ECADD :binary@prove)
  (IS_ECMUL :binary@prove)
  (IS_ECPAIRING :binary@prove)
  (IS_BLAKE2F_CDS :binary@prove)
  (IS_BLAKE2F_PARAMS :binary@prove)
  (IS_MODEXP_CDS :binary@prove)
  (IS_MODEXP_XBS :binary@prove)
  (IS_MODEXP_LEAD :binary@prove)
  (IS_MODEXP_PRICING :binary@prove)
  (IS_MODEXP_EXTRACT :binary@prove)
  (WCP_FLAG :binary@prove)
  (ADD_FLAG :binary@prove)
  (MOD_FLAG :binary@prove)
  (OUTGOING_INST :byte :display :opcode)
  (OUTGOING_DATA :i128 :array [4])
  (OUTGOING_RES_LO :i128))


