package field

// This file is NOT autogenerated

import (
	"math"
	"sync"
)

func ToInt(e *Element) int {
	n := e.Uint64()
	if !e.IsUint64() || n > math.MaxInt {
		panic("out of range")
	}
	return int(n) // #nosec G115 -- Checked for overflow
}

// Define a memory pool
type SlicePool struct {
	pool *sync.Pool
}

func (p *SlicePool) Put(slice *[]Element) {
	// Reset the slice in-place
	*slice = (*slice)[:0]
	// Store the pointer itself in the pool
	p.pool.Put(slice)
}

// Adjust Get to return a slice from a pointer
func (p *SlicePool) Get() []Element {
	s := p.pool.Get().(*[]Element)
	return *s
}

// Create a new memory pool for field elements
func NewSlicePool(size int) *SlicePool {
	return &SlicePool{
		pool: &sync.Pool{
			New: func() interface{} {
				s := make([]Element, 0, size)
				return &s
			},
		},
	}
}
