(module blsdata)

(defun (map-fp2-to-g2-hypothesis)
  (* DATA_BLS_MAP_FP2_TO_G2_FLAG (first_row_of_new_first_input)))

(defconstraint internal-checks-map-fp2-to-g2 (:guard (map-fp2-to-g2-hypothesis))
  (let ((e_Im_3 LIMB)
        (e_Im_2 (shift LIMB 1))
        (e_Im_1 (shift LIMB 2))
        (e_Im_0 (shift LIMB 3))
        (e_Re_3 (shift LIMB 4))
        (e_Re_2 (shift LIMB 5))
        (e_Re_1 (shift LIMB 6))
        (e_Re_0 (shift LIMB 7))
        (e_Im_is_in_range WCP_RES)
        (e_Re_is_in_range (shift WCP_RES 4))
        (internal_checks_passed (- 1 MINT_BIT)))
       (begin (wcpGeneralizedCallToLT 0 e_Im_3 e_Im_2 e_Im_1 e_Im_0 BLS_PRIME_3 BLS_PRIME_2 BLS_PRIME_1 BLS_PRIME_0)
              (wcpGeneralizedCallToLT 4 e_Re_3 e_Re_2 e_Re_1 e_Re_0 BLS_PRIME_3 BLS_PRIME_2 BLS_PRIME_1 BLS_PRIME_0)
              (eq! internal_checks_passed (* e_Im_is_in_range e_Re_is_in_range))
       )))