(module blsdata)

(defun (map-fp-to-g1-hypothesis)
  (* DATA_BLS_MAP_FP_TO_G1_FLAG (first_row_of_new_first_input)))

(defconstraint internal-checks-map-fp-to-g1 (:guard (map-fp-to-g1-hypothesis))
  (let ((e_3 LIMB)
        (e_2 (shift LIMB 1))
        (e_1 (shift LIMB 2))
        (e_0 (shift LIMB 3))
        (e_is_in_range WCP_RES)
        (internal_checks_passed (- 1 MINT_BIT)))
       (begin (wcpGeneralizedCallToLT 0 e_3 e_2 e_1 e_0 BLS_PRIME_3 BLS_PRIME_2 BLS_PRIME_1 BLS_PRIME_0)
              (eq! internal_checks_passed (* e_is_in_range))
       )))
