(module oob)

(defcolumns
  (STAMP :i32)
  (CT :i3)
  (CT_MAX :i3)
  (DATA :i128 :array [10])
  (OOB_INST :i16)
  (IS_JUMP :binary@prove)
  (IS_JUMPI :binary@prove)
  (IS_RDC :binary@prove)
  (IS_CDL :binary@prove)
  (IS_XCALL :binary@prove)
  (IS_CALL :binary@prove)
  (IS_XCREATE :binary@prove)
  (IS_CREATE :binary@prove)
  (IS_SSTORE :binary@prove)
  (IS_DEPLOYMENT :binary@prove)
  (IS_ECRECOVER :binary@prove)
  (IS_SHA2 :binary@prove)
  (IS_RIPEMD :binary@prove)
  (IS_IDENTITY :binary@prove)
  (IS_ECADD :binary@prove)
  (IS_ECMUL :binary@prove)
  (IS_ECPAIRING :binary@prove)
  (IS_BLAKE2F_CDS :binary@prove)
  (IS_BLAKE2F_PARAMS :binary@prove)
  (IS_MODEXP_CDS :binary@prove)
  (IS_MODEXP_XBS :binary@prove)
  (IS_MODEXP_LEAD :binary@prove)
  (IS_MODEXP_PRICING :binary@prove)
  (IS_MODEXP_EXTRACT :binary@prove)
  (IS_POINT_EVALUATION :binary@prove)
  (IS_BLS_G1_ADD :binary@prove)
  (IS_BLS_G1_MSM :binary@prove)
  (IS_BLS_G2_ADD :binary@prove)
  (IS_BLS_G2_MSM :binary@prove)
  (IS_BLS_PAIRING_CHECK :binary@prove) 
  (IS_BLS_MAP_FP_TO_G1 :binary@prove)
  (IS_BLS_MAP_FP2_TO_G2 :binary@prove)
  (IS_P256_VERIFY :binary@prove)
  (WCP_FLAG :binary@prove)
  (ADD_FLAG :binary@prove)
  (MOD_FLAG :binary@prove)
  (BLS_REF_TABLE_FLAG :binary@prove)
  (OUTGOING_INST :i16 :display :opcode)
  (OUTGOING_DATA :i128 :array [4])
  (OUTGOING_RES_LO :i128))


