/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BytesLike, FunctionFragment, Interface, EventFragment, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener } from "../../../common.js"
  

  export interface IShnarfDataAcceptorBaseInterface extends Interface {
    

    getEvent(nameOrSignatureOrTopic: "DataSubmittedV3"): EventFragment;

    

    
  }

  
    export namespace DataSubmittedV3Event {
      export type InputTuple = [parentShnarf: BytesLike, shnarf: BytesLike, finalStateRootHash: BytesLike];
      export type OutputTuple = [parentShnarf: string, shnarf: string, finalStateRootHash: string];
      export interface OutputObject {parentShnarf: string, shnarf: string, finalStateRootHash: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface IShnarfDataAcceptorBase extends BaseContract {
    
    connect(runner?: ContractRunner | null): IShnarfDataAcceptorBase;
    waitForDeployment(): Promise<this>;

    interface: IShnarfDataAcceptorBaseInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    

    getEvent(key: 'DataSubmittedV3'): TypedContractEvent<DataSubmittedV3Event.InputTuple, DataSubmittedV3Event.OutputTuple, DataSubmittedV3Event.OutputObject>;

    filters: {
      
      'DataSubmittedV3(bytes32,bytes32,bytes32)': TypedContractEvent<DataSubmittedV3Event.InputTuple, DataSubmittedV3Event.OutputTuple, DataSubmittedV3Event.OutputObject>;
      DataSubmittedV3: TypedContractEvent<DataSubmittedV3Event.InputTuple, DataSubmittedV3Event.OutputTuple, DataSubmittedV3Event.OutputObject>;
    
    };
  }