export const LineaRollupAbi = [
  {
    inputs: [
      { name: "_from", type: "address" },
      { name: "_to", type: "address" },
      { name: "_fee", type: "uint256" },
      { name: "_value", type: "uint256" },
      { name: "_feeRecipient", type: "address" },
      { name: "_calldata", type: "bytes" },
      { name: "_nonce", type: "uint256" },
    ],
    name: "claimMessage",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          { name: "proof", type: "bytes32[]" },
          { name: "messageNumber", type: "uint256" },
          { name: "leafIndex", type: "uint32" },
          { name: "from", type: "address" },
          { name: "to", type: "address" },
          { name: "fee", type: "uint256" },
          { name: "value", type: "uint256" },
          { name: "feeRecipient", type: "address" },
          { name: "merkleRoot", type: "bytes32" },
          { name: "data", type: "bytes" },
        ],
        name: "_params",
        type: "tuple",
      },
    ],
    name: "claimMessageWithProof",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ name: "_messageHash", type: "bytes32" }],
    name: "inboxL2L1MessageStatus",
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "limitInWei",
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "currentPeriodAmountInWei",
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ name: "_merkleRoot", type: "bytes32" }],
    name: "l2MerkleRootsDepths",
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: "_from", type: "address" },
      { indexed: true, name: "_to", type: "address" },
      { indexed: false, name: "_fee", type: "uint256" },
      { indexed: false, name: "_value", type: "uint256" },
      { indexed: false, name: "_nonce", type: "uint256" },
      { indexed: false, name: "_calldata", type: "bytes" },
      { indexed: true, name: "_messageHash", type: "bytes32" },
    ],
    name: "MessageSent",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [{ indexed: true, name: "_messageHash", type: "bytes32" }],
    name: "MessageClaimed",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [{ indexed: true, name: "l2Block", type: "uint256" }],
    name: "L2MessagingBlocksAnchored",
    type: "event",
  },
  {
    inputs: [],
    name: "RateLimitExceeded",
    type: "error",
  },
] as const;

export const L2MessageServiceAbi = [
  {
    inputs: [
      { name: "_from", type: "address" },
      { name: "_to", type: "address" },
      { name: "_fee", type: "uint256" },
      { name: "_value", type: "uint256" },
      { name: "_feeRecipient", type: "address" },
      { name: "_calldata", type: "bytes" },
      { name: "_nonce", type: "uint256" },
    ],
    name: "claimMessage",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ name: "_messageHash", type: "bytes32" }],
    name: "inboxL1L2MessageStatus",
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "limitInWei",
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "currentPeriodAmountInWei",
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: "_from", type: "address" },
      { indexed: true, name: "_to", type: "address" },
      { indexed: false, name: "_fee", type: "uint256" },
      { indexed: false, name: "_value", type: "uint256" },
      { indexed: false, name: "_nonce", type: "uint256" },
      { indexed: false, name: "_calldata", type: "bytes" },
      { indexed: true, name: "_messageHash", type: "bytes32" },
    ],
    name: "MessageSent",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [{ indexed: true, name: "_messageHash", type: "bytes32" }],
    name: "MessageClaimed",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [{ indexed: true, name: "version", type: "uint256" }],
    name: "ServiceVersionMigrated",
    type: "event",
  },
  {
    inputs: [],
    name: "RateLimitExceeded",
    type: "error",
  },
] as const;
