/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface LineaSequencerUptimeFeedInterface extends Interface {
    getFunction(nameOrSignature: "DEFAULT_ADMIN_ROLE" | "FEED_UPDATER_ROLE" | "acceptOwnership" | "addAccess" | "checkEnabled" | "decimals" | "description" | "disableAccessCheck" | "enableAccessCheck" | "getAnswer" | "getRoleAdmin" | "getRoundData" | "getTimestamp" | "grantRole" | "hasAccess" | "hasRole" | "l1Sender" | "latestAnswer" | "latestRound" | "latestRoundData" | "latestTimestamp" | "owner" | "removeAccess" | "renounceRole" | "revokeRole" | "supportsInterface" | "transferL1Sender" | "transferOwnership" | "typeAndVersion" | "updateStatus" | "version"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "AddedAccess" | "AnswerUpdated" | "CheckAccessDisabled" | "CheckAccessEnabled" | "L1SenderTransferred" | "NewRound" | "OwnershipTransferRequested" | "OwnershipTransferred" | "RemovedAccess" | "RoleAdminChanged" | "RoleGranted" | "RoleRevoked" | "RoundUpdated" | "UpdateIgnored"): EventFragment;

    encodeFunctionData(functionFragment: 'DEFAULT_ADMIN_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'FEED_UPDATER_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'acceptOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'addAccess', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'checkEnabled', values?: undefined): string;
encodeFunctionData(functionFragment: 'decimals', values?: undefined): string;
encodeFunctionData(functionFragment: 'description', values?: undefined): string;
encodeFunctionData(functionFragment: 'disableAccessCheck', values?: undefined): string;
encodeFunctionData(functionFragment: 'enableAccessCheck', values?: undefined): string;
encodeFunctionData(functionFragment: 'getAnswer', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getRoleAdmin', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'getRoundData', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getTimestamp', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'grantRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'hasAccess', values: [AddressLike, BytesLike]): string;
encodeFunctionData(functionFragment: 'hasRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'l1Sender', values?: undefined): string;
encodeFunctionData(functionFragment: 'latestAnswer', values?: undefined): string;
encodeFunctionData(functionFragment: 'latestRound', values?: undefined): string;
encodeFunctionData(functionFragment: 'latestRoundData', values?: undefined): string;
encodeFunctionData(functionFragment: 'latestTimestamp', values?: undefined): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'removeAccess', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'renounceRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'revokeRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'supportsInterface', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'transferL1Sender', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'typeAndVersion', values?: undefined): string;
encodeFunctionData(functionFragment: 'updateStatus', values: [boolean, BigNumberish]): string;
encodeFunctionData(functionFragment: 'version', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'DEFAULT_ADMIN_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'FEED_UPDATER_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'acceptOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'addAccess', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'checkEnabled', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'decimals', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'description', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'disableAccessCheck', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'enableAccessCheck', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAnswer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getRoleAdmin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getRoundData', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getTimestamp', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'grantRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hasAccess', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hasRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'l1Sender', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'latestAnswer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'latestRound', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'latestRoundData', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'latestTimestamp', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'removeAccess', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'revokeRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'supportsInterface', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferL1Sender', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'typeAndVersion', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateStatus', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'version', data: BytesLike): Result;
  }

  
    export namespace AddedAccessEvent {
      export type InputTuple = [user: AddressLike];
      export type OutputTuple = [user: string];
      export interface OutputObject {user: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace AnswerUpdatedEvent {
      export type InputTuple = [current: BigNumberish, roundId: BigNumberish, updatedAt: BigNumberish];
      export type OutputTuple = [current: bigint, roundId: bigint, updatedAt: bigint];
      export interface OutputObject {current: bigint, roundId: bigint, updatedAt: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace CheckAccessDisabledEvent {
      export type InputTuple = [];
      export type OutputTuple = [];
      export interface OutputObject {};
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace CheckAccessEnabledEvent {
      export type InputTuple = [];
      export type OutputTuple = [];
      export interface OutputObject {};
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace L1SenderTransferredEvent {
      export type InputTuple = [from: AddressLike, to: AddressLike];
      export type OutputTuple = [from: string, to: string];
      export interface OutputObject {from: string, to: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace NewRoundEvent {
      export type InputTuple = [roundId: BigNumberish, startedBy: AddressLike, startedAt: BigNumberish];
      export type OutputTuple = [roundId: bigint, startedBy: string, startedAt: bigint];
      export interface OutputObject {roundId: bigint, startedBy: string, startedAt: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferRequestedEvent {
      export type InputTuple = [from: AddressLike, to: AddressLike];
      export type OutputTuple = [from: string, to: string];
      export interface OutputObject {from: string, to: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [from: AddressLike, to: AddressLike];
      export type OutputTuple = [from: string, to: string];
      export interface OutputObject {from: string, to: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RemovedAccessEvent {
      export type InputTuple = [user: AddressLike];
      export type OutputTuple = [user: string];
      export interface OutputObject {user: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleAdminChangedEvent {
      export type InputTuple = [role: BytesLike, previousAdminRole: BytesLike, newAdminRole: BytesLike];
      export type OutputTuple = [role: string, previousAdminRole: string, newAdminRole: string];
      export interface OutputObject {role: string, previousAdminRole: string, newAdminRole: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleGrantedEvent {
      export type InputTuple = [role: BytesLike, account: AddressLike, sender: AddressLike];
      export type OutputTuple = [role: string, account: string, sender: string];
      export interface OutputObject {role: string, account: string, sender: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleRevokedEvent {
      export type InputTuple = [role: BytesLike, account: AddressLike, sender: AddressLike];
      export type OutputTuple = [role: string, account: string, sender: string];
      export interface OutputObject {role: string, account: string, sender: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoundUpdatedEvent {
      export type InputTuple = [status: BigNumberish, updatedAt: BigNumberish];
      export type OutputTuple = [status: bigint, updatedAt: bigint];
      export interface OutputObject {status: bigint, updatedAt: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace UpdateIgnoredEvent {
      export type InputTuple = [latestStatus: boolean, latestTimestamp: BigNumberish, incomingStatus: boolean, incomingTimestamp: BigNumberish];
      export type OutputTuple = [latestStatus: boolean, latestTimestamp: bigint, incomingStatus: boolean, incomingTimestamp: bigint];
      export interface OutputObject {latestStatus: boolean, latestTimestamp: bigint, incomingStatus: boolean, incomingTimestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface LineaSequencerUptimeFeed extends BaseContract {
    
    connect(runner?: ContractRunner | null): LineaSequencerUptimeFeed;
    waitForDeployment(): Promise<this>;

    interface: LineaSequencerUptimeFeedInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    DEFAULT_ADMIN_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    FEED_UPDATER_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    acceptOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    addAccess: TypedContractMethod<
      [_user: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    checkEnabled: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    decimals: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    description: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    disableAccessCheck: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    enableAccessCheck: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    getAnswer: TypedContractMethod<
      [roundId: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    getRoleAdmin: TypedContractMethod<
      [role: BytesLike, ],
      [string],
      'view'
    >
    

    
    getRoundData: TypedContractMethod<
      [_roundId: BigNumberish, ],
      [[bigint, bigint, bigint, bigint, bigint] & {roundId: bigint, answer: bigint, startedAt: bigint, updatedAt: bigint, answeredInRound: bigint }],
      'view'
    >
    

    
    getTimestamp: TypedContractMethod<
      [roundId: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    grantRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    hasAccess: TypedContractMethod<
      [_user: AddressLike, _calldata: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    hasRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    l1Sender: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    latestAnswer: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    latestRound: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    latestRoundData: TypedContractMethod<
      [],
      [[bigint, bigint, bigint, bigint, bigint] & {roundId: bigint, answer: bigint, startedAt: bigint, updatedAt: bigint, answeredInRound: bigint }],
      'view'
    >
    

    
    latestTimestamp: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    removeAccess: TypedContractMethod<
      [_user: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    renounceRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    revokeRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    supportsInterface: TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    transferL1Sender: TypedContractMethod<
      [newSender: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    transferOwnership: TypedContractMethod<
      [to: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    typeAndVersion: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    updateStatus: TypedContractMethod<
      [status: boolean, timestamp: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    version: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'DEFAULT_ADMIN_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'FEED_UPDATER_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'acceptOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'addAccess'): TypedContractMethod<
      [_user: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'checkEnabled'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'decimals'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'description'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'disableAccessCheck'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'enableAccessCheck'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getAnswer'): TypedContractMethod<
      [roundId: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getRoleAdmin'): TypedContractMethod<
      [role: BytesLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getRoundData'): TypedContractMethod<
      [_roundId: BigNumberish, ],
      [[bigint, bigint, bigint, bigint, bigint] & {roundId: bigint, answer: bigint, startedAt: bigint, updatedAt: bigint, answeredInRound: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'getTimestamp'): TypedContractMethod<
      [roundId: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'grantRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'hasAccess'): TypedContractMethod<
      [_user: AddressLike, _calldata: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'hasRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'l1Sender'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'latestAnswer'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'latestRound'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'latestRoundData'): TypedContractMethod<
      [],
      [[bigint, bigint, bigint, bigint, bigint] & {roundId: bigint, answer: bigint, startedAt: bigint, updatedAt: bigint, answeredInRound: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'latestTimestamp'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'removeAccess'): TypedContractMethod<
      [_user: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'renounceRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'revokeRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'supportsInterface'): TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'transferL1Sender'): TypedContractMethod<
      [newSender: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [to: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'typeAndVersion'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'updateStatus'): TypedContractMethod<
      [status: boolean, timestamp: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'version'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;

    getEvent(key: 'AddedAccess'): TypedContractEvent<AddedAccessEvent.InputTuple, AddedAccessEvent.OutputTuple, AddedAccessEvent.OutputObject>;
getEvent(key: 'AnswerUpdated'): TypedContractEvent<AnswerUpdatedEvent.InputTuple, AnswerUpdatedEvent.OutputTuple, AnswerUpdatedEvent.OutputObject>;
getEvent(key: 'CheckAccessDisabled'): TypedContractEvent<CheckAccessDisabledEvent.InputTuple, CheckAccessDisabledEvent.OutputTuple, CheckAccessDisabledEvent.OutputObject>;
getEvent(key: 'CheckAccessEnabled'): TypedContractEvent<CheckAccessEnabledEvent.InputTuple, CheckAccessEnabledEvent.OutputTuple, CheckAccessEnabledEvent.OutputObject>;
getEvent(key: 'L1SenderTransferred'): TypedContractEvent<L1SenderTransferredEvent.InputTuple, L1SenderTransferredEvent.OutputTuple, L1SenderTransferredEvent.OutputObject>;
getEvent(key: 'NewRound'): TypedContractEvent<NewRoundEvent.InputTuple, NewRoundEvent.OutputTuple, NewRoundEvent.OutputObject>;
getEvent(key: 'OwnershipTransferRequested'): TypedContractEvent<OwnershipTransferRequestedEvent.InputTuple, OwnershipTransferRequestedEvent.OutputTuple, OwnershipTransferRequestedEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'RemovedAccess'): TypedContractEvent<RemovedAccessEvent.InputTuple, RemovedAccessEvent.OutputTuple, RemovedAccessEvent.OutputObject>;
getEvent(key: 'RoleAdminChanged'): TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
getEvent(key: 'RoleGranted'): TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
getEvent(key: 'RoleRevoked'): TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
getEvent(key: 'RoundUpdated'): TypedContractEvent<RoundUpdatedEvent.InputTuple, RoundUpdatedEvent.OutputTuple, RoundUpdatedEvent.OutputObject>;
getEvent(key: 'UpdateIgnored'): TypedContractEvent<UpdateIgnoredEvent.InputTuple, UpdateIgnoredEvent.OutputTuple, UpdateIgnoredEvent.OutputObject>;

    filters: {
      
      'AddedAccess(address)': TypedContractEvent<AddedAccessEvent.InputTuple, AddedAccessEvent.OutputTuple, AddedAccessEvent.OutputObject>;
      AddedAccess: TypedContractEvent<AddedAccessEvent.InputTuple, AddedAccessEvent.OutputTuple, AddedAccessEvent.OutputObject>;
    

      'AnswerUpdated(int256,uint256,uint256)': TypedContractEvent<AnswerUpdatedEvent.InputTuple, AnswerUpdatedEvent.OutputTuple, AnswerUpdatedEvent.OutputObject>;
      AnswerUpdated: TypedContractEvent<AnswerUpdatedEvent.InputTuple, AnswerUpdatedEvent.OutputTuple, AnswerUpdatedEvent.OutputObject>;
    

      'CheckAccessDisabled()': TypedContractEvent<CheckAccessDisabledEvent.InputTuple, CheckAccessDisabledEvent.OutputTuple, CheckAccessDisabledEvent.OutputObject>;
      CheckAccessDisabled: TypedContractEvent<CheckAccessDisabledEvent.InputTuple, CheckAccessDisabledEvent.OutputTuple, CheckAccessDisabledEvent.OutputObject>;
    

      'CheckAccessEnabled()': TypedContractEvent<CheckAccessEnabledEvent.InputTuple, CheckAccessEnabledEvent.OutputTuple, CheckAccessEnabledEvent.OutputObject>;
      CheckAccessEnabled: TypedContractEvent<CheckAccessEnabledEvent.InputTuple, CheckAccessEnabledEvent.OutputTuple, CheckAccessEnabledEvent.OutputObject>;
    

      'L1SenderTransferred(address,address)': TypedContractEvent<L1SenderTransferredEvent.InputTuple, L1SenderTransferredEvent.OutputTuple, L1SenderTransferredEvent.OutputObject>;
      L1SenderTransferred: TypedContractEvent<L1SenderTransferredEvent.InputTuple, L1SenderTransferredEvent.OutputTuple, L1SenderTransferredEvent.OutputObject>;
    

      'NewRound(uint256,address,uint256)': TypedContractEvent<NewRoundEvent.InputTuple, NewRoundEvent.OutputTuple, NewRoundEvent.OutputObject>;
      NewRound: TypedContractEvent<NewRoundEvent.InputTuple, NewRoundEvent.OutputTuple, NewRoundEvent.OutputObject>;
    

      'OwnershipTransferRequested(address,address)': TypedContractEvent<OwnershipTransferRequestedEvent.InputTuple, OwnershipTransferRequestedEvent.OutputTuple, OwnershipTransferRequestedEvent.OutputObject>;
      OwnershipTransferRequested: TypedContractEvent<OwnershipTransferRequestedEvent.InputTuple, OwnershipTransferRequestedEvent.OutputTuple, OwnershipTransferRequestedEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'RemovedAccess(address)': TypedContractEvent<RemovedAccessEvent.InputTuple, RemovedAccessEvent.OutputTuple, RemovedAccessEvent.OutputObject>;
      RemovedAccess: TypedContractEvent<RemovedAccessEvent.InputTuple, RemovedAccessEvent.OutputTuple, RemovedAccessEvent.OutputObject>;
    

      'RoleAdminChanged(bytes32,bytes32,bytes32)': TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
      RoleAdminChanged: TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
    

      'RoleGranted(bytes32,address,address)': TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
      RoleGranted: TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
    

      'RoleRevoked(bytes32,address,address)': TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
      RoleRevoked: TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
    

      'RoundUpdated(int256,uint64)': TypedContractEvent<RoundUpdatedEvent.InputTuple, RoundUpdatedEvent.OutputTuple, RoundUpdatedEvent.OutputObject>;
      RoundUpdated: TypedContractEvent<RoundUpdatedEvent.InputTuple, RoundUpdatedEvent.OutputTuple, RoundUpdatedEvent.OutputObject>;
    

      'UpdateIgnored(bool,uint64,bool,uint64)': TypedContractEvent<UpdateIgnoredEvent.InputTuple, UpdateIgnoredEvent.OutputTuple, UpdateIgnoredEvent.OutputObject>;
      UpdateIgnored: TypedContractEvent<UpdateIgnoredEvent.InputTuple, UpdateIgnoredEvent.OutputTuple, UpdateIgnoredEvent.OutputObject>;
    
    };
  }