package poseidon2

import (
	"github.com/consensys/linea-monorepo/prover/crypto/poseidon2"
	"github.com/consensys/linea-monorepo/prover/maths/common/smartvectors"
	"github.com/consensys/linea-monorepo/prover/maths/field"
	"github.com/consensys/linea-monorepo/prover/protocol/ifaces"
	"github.com/consensys/linea-monorepo/prover/protocol/query"
	"github.com/consensys/linea-monorepo/prover/protocol/wizard"
	sym "github.com/consensys/linea-monorepo/prover/symbolic"
	"github.com/consensys/linea-monorepo/prover/utils"
	"github.com/consensys/linea-monorepo/prover/utils/parallel"
)

// Poseidon2Context is a compilation context storing all the artefacts generated by
// the compilation of Poseidon2 query. Those are: the columns created to emulate the
// evaluation of the Poseidon2 compilation function.
//
// The context also implements the [wizard.ProverAction] interface.
type Poseidon2Context struct {

	// CompiledQueries stores the Poseidon2 queries that have been compiled.
	CompiledQueries []*query.Poseidon2

	// StackedOldState stores all the old states of the Poseidon2 computation. For
	// all unique triplets (oldState, blocks, newStates).
	StackedOldStates [8]ifaces.Column
	// StackedBlocks stores all the blocks of the Poseidon2 computation. For all
	// unique triplets (oldState, blocks, newStates).
	StackedBlocks [8]ifaces.Column
	// StackedNewStates stores all the new states of the Poseidon2 computation. For
	// all unique triplets (oldState, blocks, newStates).
	StackedNewStates [8]ifaces.Column
	// MatMulM4Tmp stores all the intermediate results of the Poseidon2 matMulM4InPlace computation.
	// Refer to the t01, t23, t0123, t01123, t01233 values of all input chunks:
	// https://github.com/Consensys/gnark-crypto/blob/master/field/koalabear/poseidon2/poseidon2.go#L178
	MatMulM4Tmp [20][]ifaces.Column
	// MatMulM4 stores all the round outputs of the Poseidon2 matMulM4InPlace computation.
	MatMulM4 [16][]ifaces.Column
	// T stores the partial sum of MatMulM4.
	// T[j] = sum_{i = 0,1,2,3} MatMulM4[4*i+j], for j = 0,1,2,3
	T [4][]ifaces.Column
	// MatMulExternal stores all the round outputs of the Poseidon2 matMulExternalInPlace computation.
	// MatMulExternal[4i+j] = MatMulM4[4i+j] + T[j], for i, j = 0,1,2,3
	MatMulExternal [16][]ifaces.Column
	// AddRoundKey stores all the round outputs of the Poseidon2 addRoundKeyInPlace computation.
	// AddRoundKey[i] = MatMulExternal[i] + RoundKeys[round][i]
	AddRoundKey [16][]ifaces.Column
	// SBox stores all the round outputs of the Poseidon2 sBox computation.
	// SBox[i]=AddRoundKey[i] ^3
	SBox [16][]ifaces.Column
	// SBox stores all the SBox sum in the Poseidon2 matMulInternalInPlace computation.
	// sum = ∑ SBox[i]
	SBoxSum []ifaces.Column
	// MatMulInternal stores all the round outputs of the Poseidon2 matMulInternalInPlace computation.
	// mul by diag16:
	// [-2, 1, 2, 1/2, 3, 4, -1/2, -3, -4, 1/2^8, 1/8, 1/2^24, -1/2^8, -1/8, -1/16, -1/2^24]
	MatMulInternal [16][]ifaces.Column
}

// CompilePoseidon2 compiles all the Poseidon2 queries in the [comp] object. The compiler
// works by creating its own module responsible for checking each unique Poseidon2
// query statements, taking into account the padding.
func CompilePoseidon2(comp *wizard.CompiledIOP) {
	_ = defineContext(comp)
}

// defineMatMulExternalInPlace
func defineMatMulExternalInPlace(comp *wizard.CompiledIOP, ctx *Poseidon2Context, round, totalSize int, input []ifaces.Column, roundID int) []ifaces.Column {
	matMulM4Tmp := [20]ifaces.Column{}
	matMulM4 := [16]ifaces.Column{}
	t := [4]ifaces.Column{}
	matMulExternal := [16]ifaces.Column{}

	// MatMulExternalInPlace
	// Declare temporary columns for the matrix multiplication.
	for col := 0; col < 20; col++ {
		matMulM4Tmp[col] = comp.InsertCommit(round, ifaces.ColIDf("Poseidon2_ROUND_%v_MatMulM4Tmp_%v_%v_%v", roundID, comp.SelfRecursionCount, uniqueID(comp), col), totalSize)
		ctx.MatMulM4Tmp[col] = append(ctx.MatMulM4Tmp[col], matMulM4Tmp[col])
	}
	for col := 0; col < 16; col++ {
		matMulM4[col] = comp.InsertCommit(round, ifaces.ColIDf("Poseidon2_ROUND_%v_MatMulM4_%v_%v_%v", roundID, comp.SelfRecursionCount, uniqueID(comp), col), totalSize)
		ctx.MatMulM4[col] = append(ctx.MatMulM4[col], matMulM4[col])
	}
	for col := 0; col < 4; col++ {
		t[col] = comp.InsertCommit(round, ifaces.ColIDf("Poseidon2_ROUND_%v_T_%v_%v_%v", roundID, comp.SelfRecursionCount, uniqueID(comp), col), totalSize)
		ctx.T[col] = append(ctx.T[col], t[col])
	}
	for col := 0; col < 16; col++ {
		matMulExternal[col] = comp.InsertCommit(round, ifaces.ColIDf("Poseidon2_ROUND_%v_MatMulExternal_%v_%v_%v", roundID, comp.SelfRecursionCount, uniqueID(comp), col), totalSize)
		ctx.MatMulExternal[col] = append(ctx.MatMulExternal[col], matMulExternal[col])
	}
	// Insert constraints for the matrix multiplication.
	for chunk := 0; chunk < 4; chunk++ {
		comp.InsertGlobal(round, ifaces.QueryIDf("Poseidon2_ROUND_%v_MatMulM4Tmp_COMPUTATION_%v_%v_%v", roundID, comp.SelfRecursionCount, uniqueID(comp), 5*chunk), sym.Sub(matMulM4Tmp[5*chunk], sym.Add(input[4*chunk], input[4*chunk+1])))
		comp.InsertGlobal(round, ifaces.QueryIDf("Poseidon2_ROUND_%v_MatMulM4Tmp_COMPUTATION_%v_%v_%v", roundID, comp.SelfRecursionCount, uniqueID(comp), 5*chunk+1), sym.Sub(matMulM4Tmp[5*chunk+1], sym.Add(input[4*chunk+2], input[4*chunk+3])))
		comp.InsertGlobal(round, ifaces.QueryIDf("Poseidon2_ROUND_%v_MatMulM4Tmp_COMPUTATION_%v_%v_%v", roundID, comp.SelfRecursionCount, uniqueID(comp), 5*chunk+2), sym.Sub(matMulM4Tmp[5*chunk+2], sym.Add(matMulM4Tmp[5*chunk], matMulM4Tmp[5*chunk+1])))
		comp.InsertGlobal(round, ifaces.QueryIDf("Poseidon2_ROUND_%v_MatMulM4Tmp_COMPUTATION_%v_%v_%v", roundID, comp.SelfRecursionCount, uniqueID(comp), 5*chunk+3), sym.Sub(matMulM4Tmp[5*chunk+3], sym.Add(matMulM4Tmp[5*chunk+2], input[4*chunk+1])))
		comp.InsertGlobal(round, ifaces.QueryIDf("Poseidon2_ROUND_%v_MatMulM4Tmp_COMPUTATION_%v_%v_%v", roundID, comp.SelfRecursionCount, uniqueID(comp), 5*chunk+4), sym.Sub(matMulM4Tmp[5*chunk+4], sym.Add(matMulM4Tmp[5*chunk+2], input[4*chunk+3])))

		comp.InsertGlobal(round, ifaces.QueryIDf("Poseidon2_ROUND_%v_MatMulM4_COMPUTATION_%v_%v_%v", roundID, comp.SelfRecursionCount, uniqueID(comp), 4*chunk), sym.Sub(matMulM4[4*chunk], sym.Add(matMulM4Tmp[5*chunk], matMulM4Tmp[5*chunk+3])))
		comp.InsertGlobal(round, ifaces.QueryIDf("Poseidon2_ROUND_%v_MatMulM4_COMPUTATION_%v_%v_%v", roundID, comp.SelfRecursionCount, uniqueID(comp), 4*chunk+1), sym.Sub(matMulM4[4*chunk+1], sym.Add(input[4*chunk+2], input[4*chunk+2], matMulM4Tmp[5*chunk+3])))
		comp.InsertGlobal(round, ifaces.QueryIDf("Poseidon2_ROUND_%v_MatMulM4_COMPUTATION_%v_%v_%v", roundID, comp.SelfRecursionCount, uniqueID(comp), 4*chunk+2), sym.Sub(matMulM4[4*chunk+2], sym.Add(matMulM4Tmp[5*chunk+1], matMulM4Tmp[5*chunk+4])))
		comp.InsertGlobal(round, ifaces.QueryIDf("Poseidon2_ROUND_%v_MatMulM4_COMPUTATION_%v_%v_%v", roundID, comp.SelfRecursionCount, uniqueID(comp), 4*chunk+3), sym.Sub(matMulM4[4*chunk+3], sym.Add(input[4*chunk], input[4*chunk], matMulM4Tmp[5*chunk+4])))
	}
	for i := 0; i < 4; i++ {
		comp.InsertGlobal(round, ifaces.QueryIDf("Poseidon2_ROUND_%v_T_COMPUTATION_%v_%v_%v", roundID, comp.SelfRecursionCount, uniqueID(comp), i), sym.Sub(t[i], sym.Add(matMulM4[i], matMulM4[i+4], matMulM4[i+8], matMulM4[i+12])))
	}
	for i := 0; i < 16; i++ {
		comp.InsertGlobal(round, ifaces.QueryIDf("Poseidon2_ROUND_%v_MatMulExternal_COMPUTATION_%v_%v_%v", roundID, comp.SelfRecursionCount, uniqueID(comp), i), sym.Sub(matMulExternal[i], sym.Add(matMulM4[i], t[i%4])))
	}
	return matMulExternal[:]
}

// defineRoundInternal abstracts the logic for a partial Poseidon2 round.
func defineRoundInternal(comp *wizard.CompiledIOP, ctx *Poseidon2Context, round, totalSize int, input []ifaces.Column, roundID int) []ifaces.Column {
	matMulInternal := [16]ifaces.Column{}
	sBoxSum := comp.InsertCommit(round, ifaces.ColIDf("Poseidon2_ROUND_%v_SBoxSum_%v_%v", roundID, comp.SelfRecursionCount, uniqueID(comp)), totalSize)
	ctx.SBoxSum = append(ctx.SBoxSum, sBoxSum)

	// MatMulInternalInPlace
	comp.InsertGlobal(round, ifaces.QueryIDf("Poseidon2_ROUND_%v_SBoxSum_COMPUTATION_%v_%v", roundID, comp.SelfRecursionCount, uniqueID(comp)),
		sym.Sub(sBoxSum, sym.Add(input[0], input[1], input[2], input[3], input[4], input[5], input[6], input[7], input[8], input[9], input[10], input[11], input[12], input[13], input[14], input[15])))

	for col := 0; col < 16; col++ {
		matMulInternal[col] = comp.InsertCommit(round, ifaces.ColIDf("Poseidon2_ROUND_%v_MatMulInternal_%v_%v_%v", roundID, comp.SelfRecursionCount, uniqueID(comp), col), totalSize)
		ctx.MatMulInternal[col] = append(ctx.MatMulInternal[col], matMulInternal[col])
	}

	// mul by diag16:
	// [-2, 1, 2, 1/2,
	//  3, 4, -1/2, -3,
	// -4, 1/2^8, 1/2^3, 1/2^24,
	// -1/2^8, -1/2^3, -1/2^4, -1/2^24]
	// matMulInternal[0] = sBoxSum - 2 * input[0]
	comp.InsertGlobal(round, ifaces.QueryIDf("Poseidon2_ROUND_%v_MatMulInternal_COMPUTATION_%v_%v_%v", roundID, comp.SelfRecursionCount, uniqueID(comp), 0),
		sym.Sub(matMulInternal[0], sym.Sub(sBoxSum, sym.Mul(sym.NewConstant(2), input[0]))))
	// matMulInternal[1] = sBoxSum + input[1]
	comp.InsertGlobal(round, ifaces.QueryIDf("Poseidon2_ROUND_%v_MatMulInternal_COMPUTATION_%v_%v_%v", roundID, comp.SelfRecursionCount, uniqueID(comp), 1),
		sym.Sub(matMulInternal[1], sym.Add(sBoxSum, input[1])))
	// matMulInternal[2] = sBoxSum + 2 * input[2]
	comp.InsertGlobal(round, ifaces.QueryIDf("Poseidon2_ROUND_%v_MatMulInternal_COMPUTATION_%v_%v_%v", roundID, comp.SelfRecursionCount, uniqueID(comp), 2),
		sym.Sub(matMulInternal[2], sym.Add(sBoxSum, sym.Mul(sym.NewConstant(-2), input[2]))))
	// matMulInternal[3] = sBoxSum + 1/2 * input[3]
	comp.InsertGlobal(round, ifaces.QueryIDf("Poseidon2_ROUND_%v_MatMulInternal_COMPUTATION_%v_%v_%v", roundID, comp.SelfRecursionCount, uniqueID(comp), 3),
		sym.Sub(matMulInternal[3], sym.Add(sBoxSum, sym.Mul(sym.NewConstant(1<<(32-1)), input[3]))))
	// matMulInternal[4] = sBoxSum + 3 * input[4]
	comp.InsertGlobal(round, ifaces.QueryIDf("Poseidon2_ROUND_%v_MatMulInternal_COMPUTATION_%v_%v_%v", roundID, comp.SelfRecursionCount, uniqueID(comp), 4),
		sym.Sub(matMulInternal[4], sym.Add(sBoxSum, sym.Mul(sym.NewConstant(3), input[4]))))
	// matMulInternal[5] = sBoxSum + 4 * input[5]
	comp.InsertGlobal(round, ifaces.QueryIDf("Poseidon2_ROUND_%v_MatMulInternal_COMPUTATION_%v_%v_%v", roundID, comp.SelfRecursionCount, uniqueID(comp), 5),
		sym.Sub(matMulInternal[5], sym.Add(sBoxSum, sym.Mul(sym.NewConstant(4), input[5]))))
	// matMulInternal[6] = sBoxSum - 1/2 * input[6]
	comp.InsertGlobal(round, ifaces.QueryIDf("Poseidon2_ROUND_%v_MatMulInternal_COMPUTATION_%v_%v_%v", roundID, comp.SelfRecursionCount, uniqueID(comp), 6),
		sym.Sub(matMulInternal[6], sym.Sub(sBoxSum, sym.Mul(sym.NewConstant(1<<(32-1)), input[6]))))
	// matMulInternal[7] = sBoxSum - 3 * input[7]
	comp.InsertGlobal(round, ifaces.QueryIDf("Poseidon2_ROUND_%v_MatMulInternal_COMPUTATION_%v_%v_%v", roundID, comp.SelfRecursionCount, uniqueID(comp), 7),
		sym.Sub(matMulInternal[7], sym.Sub(sBoxSum, sym.Mul(sym.NewConstant(3), input[7]))))
	// matMulInternal[8] = sBoxSum - 4 * input[8]
	comp.InsertGlobal(round, ifaces.QueryIDf("Poseidon2_ROUND_%v_MatMulInternal_COMPUTATION_%v_%v_%v", roundID, comp.SelfRecursionCount, uniqueID(comp), 8),
		sym.Sub(matMulInternal[8], sym.Sub(sBoxSum, sym.Mul(sym.NewConstant(4), input[8]))))
	// matMulInternal[9] = sBoxSum + 1/2^8 * input[9]
	comp.InsertGlobal(round, ifaces.QueryIDf("Poseidon2_ROUND_%v_MatMulInternal_COMPUTATION_%v_%v_%v", roundID, comp.SelfRecursionCount, uniqueID(comp), 9),
		sym.Sub(matMulInternal[9], sym.Add(sBoxSum, sym.Mul(sym.NewConstant(1<<(32-8)), input[9]))))
	// matMulInternal[10] = sBoxSum + 1/2^3 * input[10]
	comp.InsertGlobal(round, ifaces.QueryIDf("Poseidon2_ROUND_%v_MatMulInternal_COMPUTATION_%v_%v_%v", roundID, comp.SelfRecursionCount, uniqueID(comp), 10),
		sym.Sub(matMulInternal[10], sym.Add(sBoxSum, sym.Mul(sym.NewConstant(1<<(32-3)), input[10]))))
	// matMulInternal[11] = sBoxSum + 1/2^24 * input[11]
	comp.InsertGlobal(round, ifaces.QueryIDf("Poseidon2_ROUND_%v_MatMulInternal_COMPUTATION_%v_%v_%v", roundID, comp.SelfRecursionCount, uniqueID(comp), 11),
		sym.Sub(matMulInternal[11], sym.Add(sBoxSum, sym.Mul(sym.NewConstant(1<<(32-24)), input[11]))))
	// matMulInternal[12] = sBoxSum - 1/2^8 * input[12]
	comp.InsertGlobal(round, ifaces.QueryIDf("Poseidon2_ROUND_%v_MatMulInternal_COMPUTATION_%v_%v_%v", roundID, comp.SelfRecursionCount, uniqueID(comp), 12),
		sym.Sub(matMulInternal[12], sym.Sub(sBoxSum, sym.Mul(sym.NewConstant(1<<(32-8)), input[12]))))
	// matMulInternal[13] = sBoxSum - 1/2^3 * input[13]
	comp.InsertGlobal(round, ifaces.QueryIDf("Poseidon2_ROUND_%v_MatMulInternal_COMPUTATION_%v_%v_%v", roundID, comp.SelfRecursionCount, uniqueID(comp), 13),
		sym.Sub(matMulInternal[13], sym.Sub(sBoxSum, sym.Mul(sym.NewConstant(1<<(32-3)), input[13]))))
	// matMulInternal[14] = sBoxSum - 1/2^4 * input[14]
	comp.InsertGlobal(round, ifaces.QueryIDf("Poseidon2_ROUND_%v_MatMulInternal_COMPUTATION_%v_%v_%v", roundID, comp.SelfRecursionCount, uniqueID(comp), 14),
		sym.Sub(matMulInternal[14], sym.Sub(sBoxSum, sym.Mul(sym.NewConstant(1<<(32-4)), input[14]))))
	// matMulInternal[15] = sBoxSum - 1/2^24 * input[15]
	comp.InsertGlobal(round, ifaces.QueryIDf("Poseidon2_ROUND_%v_MatMulInternal_COMPUTATION_%v_%v_%v", roundID, comp.SelfRecursionCount, uniqueID(comp), 15),
		sym.Sub(matMulInternal[15], sym.Sub(sBoxSum, sym.Mul(sym.NewConstant(1<<(32-24)), input[15]))))
	return matMulInternal[:]
}

// defineAddRoundKey abstracts the logic for AddRoundKey
func defineAddRoundKey(comp *wizard.CompiledIOP, ctx *Poseidon2Context, round, totalSize int, input []ifaces.Column, roundID int) []ifaces.Column {
	addRoundKey := [16]ifaces.Column{}

	for col := 0; col < 16; col++ {
		addRoundKey[col] = comp.InsertCommit(round, ifaces.ColIDf("Poseidon2_ROUND_%v_AddRoundKey_%v_%v_%v", roundID, comp.SelfRecursionCount, uniqueID(comp), col), totalSize)
		ctx.AddRoundKey[col] = append(ctx.AddRoundKey[col], addRoundKey[col])
		comp.InsertGlobal(round, ifaces.QueryIDf("Poseidon2_ROUND_%v_AddRoundKey_COMPUTATION_%v_%v_%v", roundID, comp.SelfRecursionCount, uniqueID(comp), col),
			sym.Sub(addRoundKey[col], sym.Add(input[col], poseidon2.RoundKeys[roundID-1][col])))
	}
	// Add Round Key
	for col := 0; col < len(poseidon2.RoundKeys[roundID-1]); col++ {
		addRoundKey[col] = comp.InsertCommit(round, ifaces.ColIDf("Poseidon2_ROUND_%v_AddRoundKey_%v_%v_%v", roundID, comp.SelfRecursionCount, uniqueID(comp), col), totalSize)
		ctx.AddRoundKey[col] = append(ctx.AddRoundKey[col], addRoundKey[col])
		comp.InsertGlobal(round, ifaces.QueryIDf("Poseidon2_ROUND_%v_AddRoundKey_COMPUTATION_%v_%v_%v", roundID, comp.SelfRecursionCount, uniqueID(comp), col),
			sym.Sub(addRoundKey[col], sym.Add(input[col], poseidon2.RoundKeys[roundID-1][col]))) // Adjust the roundID because the initial round starts from 1, while the round key starts from 0.
	}

	for col := len(poseidon2.RoundKeys[roundID-1]); col < 16; col++ {
		addRoundKey[col] = comp.InsertCommit(round, ifaces.ColIDf("Poseidon2_ROUND_%v_AddRoundKey_%v_%v_%v", roundID, comp.SelfRecursionCount, uniqueID(comp), col), totalSize)
		ctx.AddRoundKey[col] = append(ctx.AddRoundKey[col], addRoundKey[col])
		comp.InsertGlobal(round, ifaces.QueryIDf("Poseidon2_ROUND_%v_AddRoundKey_COMPUTATION_%v_%v_%v", roundID, comp.SelfRecursionCount, uniqueID(comp), col),
			sym.Sub(addRoundKey[col], input[col]))
	}

	return addRoundKey[:] // The output of this round becomes the input for the next one.
}

// defineSBox abstracts the logic for SBox
func defineSBox(comp *wizard.CompiledIOP, ctx *Poseidon2Context, round, totalSize, index int, input []ifaces.Column, roundID int) ifaces.Column {
	var sBox ifaces.Column

	// S-Box
	sBox = comp.InsertCommit(round, ifaces.ColIDf("Poseidon2_ROUND_%v_SBox_%v_%v_%v", roundID, comp.SelfRecursionCount, uniqueID(comp), index), totalSize)
	ctx.SBox[index] = append(ctx.SBox[index], sBox)
	comp.InsertGlobal(round, ifaces.QueryIDf("Poseidon2_ROUND_%v_SBox_COMPUTATION_%v_%v_%v", roundID, comp.SelfRecursionCount, uniqueID(comp), index),
		sym.Sub(sBox, sym.Mul(sym.Square(input[index]), input[index])))

	return sBox // The output of this round becomes the input for the next one.
}

// defineContext generates the constraints for the Poseidon2 computation and returns
// the compilation context. The function also registers the relevant prover
// actions to assign the generated columns.
//
// The function works by:
//
//   - scanning the [comp] object, looking for uncompiled Poseidon2 queries and collecting
//     their inputs.
//   - declaring the [StackedBlocks], [StackedOldStates] and [StackedNewStates] which
//     are used to stack all the unique triplets provided in the inputs.
//   - declaring the [SumPow4s] and [RoundResults] for all Poseidon2 rounds and the
//     constraints enforcing their correctness.
func defineContext(comp *wizard.CompiledIOP) *Poseidon2Context {

	var (
		ctx        = &Poseidon2Context{}
		round      = 0
		allQueries = comp.QueriesNoParams.AllUnignoredKeys()
		totalSize  = 0
	)

	for _, qName := range allQueries {
		if q_, ok := comp.QueriesNoParams.Data(qName).(query.Poseidon2); ok {
			comp.QueriesNoParams.MarkAsIgnored(qName)
			round = max(round, comp.QueriesNoParams.Round(qName))
			totalSize += q_.Blocks[0].Size()
			ctx.CompiledQueries = append(ctx.CompiledQueries, &q_)
		}
	}

	// The compilation has nothing to do if no Poseidon2 queries were found
	if len(ctx.CompiledQueries) == 0 {
		return nil
	}

	totalSize = utils.NextPowerOfTwo(totalSize)

	for i := 0; i < 8; i++ {
		ctx.StackedOldStates[i] = comp.InsertCommit(round,
			ifaces.ColIDf("Poseidon2_STACKED_OLD_STATES_%v_%v_%v", comp.SelfRecursionCount, uniqueID(comp), i),
			totalSize)

		ctx.StackedBlocks[i] = comp.InsertCommit(round,
			ifaces.ColIDf("Poseidon2_STACKED_BLOCKS_%v_%v_%v", comp.SelfRecursionCount, uniqueID(comp), i),
			totalSize)

		ctx.StackedNewStates[i] = comp.InsertCommit(round,
			ifaces.ColIDf("Poseidon2_STACKED_NEW_STATES_%v_%v_%v", comp.SelfRecursionCount, uniqueID(comp), i),
			totalSize)
	}

	var input, output, copy_input []ifaces.Column
	input = append(input, ctx.StackedOldStates[:]...)
	input = append(input, ctx.StackedBlocks[:]...)
	output = append(input, ctx.StackedNewStates[:]...)

	copy_input = append(input[8:]) // saved to feed forward later

	// 3. Define the constraints for the Poseidon2 permutation rounds.
	// Initial matMulExternalInPlace
	input = defineMatMulExternalInPlace(comp, ctx, round, totalSize, input, 0)

	// Rounds 1 - 3
	for i := 1; i < 4; i++ {
		input = defineAddRoundKey(comp, ctx, round, totalSize, input, i)
		for col := 0; col < 16; col++ {
			input[col] = defineSBox(comp, ctx, round, totalSize, col, input, i)
		}
		input = defineMatMulExternalInPlace(comp, ctx, round, totalSize, input, i)
	}

	// Rounds 4 - 24
	for i := 4; i < 25; i++ {
		input = defineAddRoundKey(comp, ctx, round, totalSize, input, i)
		input[0] = defineSBox(comp, ctx, round, totalSize, 0, input, i)
		input = defineRoundInternal(comp, ctx, round, totalSize, input, i)
	}

	// Rounds 24 - 27
	for i := 25; i < 28; i++ {
		input = defineAddRoundKey(comp, ctx, round, totalSize, input, i)
		for col := 0; col < 16; col++ {
			input[col] = defineSBox(comp, ctx, round, totalSize, col, input, i)
		}
		input = defineMatMulExternalInPlace(comp, ctx, round, totalSize, input, i)
	}

	for i := range copy_input {
		comp.InsertGlobal(round, ifaces.QueryIDf("Poseidon2_Feed_Forward_COMPUTATION_%v_%v_%v", comp.SelfRecursionCount, uniqueID(comp), i),
			sym.Sub(output[i], sym.Add(input[i+8], copy_input[i])))
	}

	for i := range ctx.CompiledQueries {

		for col := 0; col < 8; col++ {
			comp.GenericFragmentedConditionalInclusion(
				round,
				ifaces.QueryIDf("Poseidon2_QUERY_%v_INCLUSION_%v_%v_%v", i, comp.SelfRecursionCount, uniqueID(comp), col),
				[][]ifaces.Column{
					{
						ctx.StackedBlocks[col],
						ctx.StackedOldStates[col],
						ctx.StackedNewStates[col],
					},
				},
				[]ifaces.Column{
					ctx.CompiledQueries[i].Blocks[col],
					ctx.CompiledQueries[i].OldState[col],
					ctx.CompiledQueries[i].NewState[col],
				},
				nil,
				ctx.CompiledQueries[i].Selector,
			)
		}
	}

	comp.RegisterProverAction(round, ctx)

	return ctx
}

// The Run function implements the [wizard.ProverAction] interface. It starts by
// collecting all the unique triplets provided in the inputs and stacks them into
// a column and then pads the column with (0, 0, H(0, 0)) to match the size of the
// columns. The padding is done on the right.
//
// After, [StackedOldStates], [StackedBlocks] and [StackedNewStates] are assigned
// to the corresponding columns. The function goes and computes the [SumPow4s] and
// [RoundResults] columns.
func (ctx *Poseidon2Context) Run(run *wizard.ProverRuntime) {

	var (
		zeroBlock        field.Octuplet
		stackedOldStates = make([][]field.Element, 8)
		stackedBlocks    = make([][]field.Element, 8)
		stackedNewStates = make([][]field.Element, 8)
		totalSize        = ctx.StackedOldStates[0].Size()
		poseidon2OfZero  = poseidon2.Poseidon2BlockCompression(zeroBlock, zeroBlock)
	)

	for i := range ctx.CompiledQueries {

		var (
			q         = ctx.CompiledQueries[i]
			os, b, ns [8]smartvectors.SmartVector
			sel       smartvectors.SmartVector
		)

		if q.Selector != nil {
			sel = q.Selector.GetColAssignment(run)
		}

		for col := 0; col < 8; col++ {
			os[col] = q.OldState[col].GetColAssignment(run)
			b[col] = q.Blocks[col].GetColAssignment(run)
			ns[col] = q.NewState[col].GetColAssignment(run)

			start, stop := smartvectors.CoWindowRange(os[col], b[col], ns[col], sel)

			// tryPushToStacked looks at the selector at position "j" and appends
			// the corresponding triplet (old state, block, new state) to the "stacked"
			// columns if the selector is not nil and is not zero at this position.
			tryPushToStacked := func(j int) {
				if sel != nil && sel.GetPtr(j).IsZero() {
					return
				}

				stackedOldStates[col] = append(stackedOldStates[col], os[col].Get(j))
				stackedBlocks[col] = append(stackedBlocks[col], b[col].Get(j))
				stackedNewStates[col] = append(stackedNewStates[col], ns[col].Get(j))
			}

			for j := start; j < stop; j++ {
				tryPushToStacked(j)
			}

			// The padding is done in the left, the first value is understood
			// by the query as a padding row.
			if start > 0 {
				tryPushToStacked(0)
				continue
			}

			// The padding is done on the right, the last value is understood
			// by the query as a padding row.
			if stop < os[col].Len() {
				tryPushToStacked(os[col].Len() - 1)
				continue
			}
		}
	}

	// If the range is not full, we add an extra row of padding. This is handy
	// because it allows us to specify the padding of all intermediate rows
	// as their last value. We can then simplify the code by not having a code
	// path dedicated to handling the padding.
	for col := 0; col < 8; col++ {
		if len(stackedOldStates[col]) < totalSize {

			stackedOldStates[col] = append(stackedOldStates[col], field.NewElement(0))
			stackedBlocks[col] = append(stackedBlocks[col], field.NewElement(0))
			stackedNewStates[col] = append(stackedNewStates[col], poseidon2OfZero[col])
		}

		run.AssignColumn(
			ctx.StackedOldStates[col].GetColID(),
			smartvectors.RightZeroPadded(stackedOldStates[col], totalSize))

		run.AssignColumn(
			ctx.StackedBlocks[col].GetColID(),
			smartvectors.RightZeroPadded(stackedBlocks[col], totalSize))

		run.AssignColumn(
			ctx.StackedNewStates[col].GetColID(),
			smartvectors.RightPadded(stackedNewStates[col], poseidon2OfZero[col], totalSize))
	}

	var (
		effectiveSize = len(stackedOldStates[0])
		matMulM4Tmp   = make([][][20]field.Element, 28)
		matMulM4      = make([][][16]field.Element, 28)

		t              = make([][][4]field.Element, 28)
		matMulExternal = make([][][16]field.Element, 28)

		addRoundKey = make([][][16]field.Element, 28)

		sBox = make([][][16]field.Element, 28)

		sBoxSum = make([][]field.Element, 28)

		matMulInternal = make([][][16]field.Element, 28)
	)

	for i := range matMulM4Tmp {
		matMulM4Tmp[i] = make([][20]field.Element, effectiveSize)

	}

	parallel.Execute(effectiveSize, func(start, stop int) {

		for row := start; row < stop; row++ {

			var input [16]field.Element

			for col := 0; col < 8; col++ {
				input[col] = stackedOldStates[col][row]
				input[col+8] = stackedBlocks[col][row]
			}

			matMulM4Tmp[0][row], matMulM4[0][row], t[0][row], matMulExternal[0][row] = matMulExternalInPlace(input)
			input = matMulExternal[0][row]

			// Rounds 1 - 3
			for round := 1; round < 4; round++ {
				addRoundKey[round][row] = addRoundKeyCompute(round-1, input)
				for col := 0; col < 16; col++ {
					sBox[round][row][col] = sBoxCompute(col, addRoundKey[round][row])
				}
				matMulM4Tmp[round][row], matMulM4[round][row], t[round][row], matMulExternal[round][row] = matMulExternalInPlace(sBox[round][row])
				input = matMulExternal[round][row]
			}

			// Rounds 4 - 24
			for round := 4; round < 25; round++ {
				addRoundKey[round][row] = addRoundKeyCompute(round-1, input)
				sBox[round][row] = addRoundKey[round][row]
				sBox[round][row][0] = sBoxCompute(0, addRoundKey[round][row])
				sBoxSum[round][row], matMulInternal[round][row] = matMulInternalInPlace(sBox[round][row])
				input = matMulInternal[round][row]
			}

			// Rounds 24 - 27
			for round := 25; round < 28; round++ {
				addRoundKey[round][row] = addRoundKeyCompute(round-1, input)
				for col := 0; col < 16; col++ {
					sBox[round][row][col] = sBoxCompute(col, addRoundKey[round][row])
				}
				matMulM4Tmp[round][row], matMulM4[round][row], t[round][row], matMulExternal[round][row] = matMulExternalInPlace(sBox[round][row])
				input = matMulExternal[round][row]
			}
		}
	})
	for i := range matMulM4 {

		// As a reminder, the last value of sumPow4s[i] is the padding value. (if need be).
		// If it does not, the function [RightPadded] will simply ditch the provided value.
		run.AssignColumn(
			ctx.matMulM4Tmp[i].GetColID(),
			smartvectors.RightPadded(sumPow4s[i], sumPow4s[i][effectiveSize-1], totalSize))

		run.AssignColumn(
			ctx.RoundResults[i].GetColID(),
			smartvectors.RightPadded(roundResults[i], roundResults[i][effectiveSize-1], totalSize))
	}
	/////

	for i := range sumPow4s {

		// As a reminder, the last value of sumPow4s[i] is the padding value. (if need be).
		// If it does not, the function [RightPadded] will simply ditch the provided value.
		run.AssignColumn(
			ctx.SumPow4s[i].GetColID(),
			smartvectors.RightPadded(sumPow4s[i], sumPow4s[i][effectiveSize-1], totalSize))

		run.AssignColumn(
			ctx.RoundResults[i].GetColID(),
			smartvectors.RightPadded(roundResults[i], roundResults[i][effectiveSize-1], totalSize))
	}

}

// uniqueID returns an integer helping to uniquely identify the items generated
// by the compilation of a Poseidon2 query.
func uniqueID(comp *wizard.CompiledIOP) int {
	return len(comp.Columns.AllKeys())
}
