(module mmu)

(defcolumns
	RAM_STAMP 
	MICRO_INSTRUCTION_STAMP
	(IS_MICRO_INSTRUCTION :BOOLEAN) 

	OFF_1_LO
	OFF_2_HI
	OFF_2_LO

	SIZE_IMPORTED

	VAL_HI
	VAL_LO

	CONTEXT_NUMBER
	CALLER
	RETURNER
	CONTEXT_SOURCE
	CONTEXT_TARGET

	COUNTER
	(OFFSET_OUT_OF_BOUNDS :BOOLEAN)

	PRECOMPUTATION
	TERNARY
	MICRO_INSTRUCTION
	(EXO_IS_ROM :BOOLEAN)
	(EXO_IS_LOG :BOOLEAN)
	(EXO_IS_HASH :BOOLEAN)
	(EXO_IS_TXCD :BOOLEAN)

	SOURCE_LIMB_OFFSET
	SOURCE_BYTE_OFFSET
	TARGET_LIMB_OFFSET
	TARGET_BYTE_OFFSET
	SIZE
  
	(NIB_1 :NIBBLE)
	(NIB_2 :NIBBLE)
	(NIB_3 :NIBBLE)
	(NIB_4 :NIBBLE)
	(NIB_5 :NIBBLE)
	(NIB_6 :NIBBLE)
	(NIB_7 :NIBBLE)
	(NIB_8 :NIBBLE)
	(NIB_9 :NIBBLE)

    (BYTE_1 :BYTE)
	(BYTE_2 :BYTE)
	(BYTE_3 :BYTE)
	(BYTE_4 :BYTE)
	(BYTE_5 :BYTE)
	(BYTE_6 :BYTE)
	(BYTE_7 :BYTE)
	(BYTE_8 :BYTE)

    ACC_1
    ACC_2
    ACC_3
    ACC_4
    ACC_5
    ACC_6
    ACC_7
    ACC_8

    (BIT_1 :BOOLEAN)
	(BIT_2 :BOOLEAN)
	(BIT_3 :BOOLEAN)
	(BIT_4 :BOOLEAN)
	(BIT_5 :BOOLEAN)
	(BIT_6 :BOOLEAN)
	(BIT_7 :BOOLEAN)
	(BIT_8 :BOOLEAN)

	ALIGNED
	FAST

	MIN

	CALL_STACK_DEPTH
	CALL_DATA_SIZE
	CALL_DATA_OFFSET
	INSTRUCTION
	
	TOTAL_NUMBER_OF_MICRO_INSTRUCTIONS
	TOTAL_NUMBER_OF_READS
	TOTAL_NUMBER_OF_PADDINGS

	(TO_RAM :BOOLEAN)
	(ERF    :BOOLEAN)

	RETURN_OFFSET
	RETURN_CAPACITY

	REFS
	REFO

	INFO

	(IS_DATA :BOOLEAN))

(defalias 
	CSD				CALL_STACK_DEPTH
	CDS				CALL_DATA_SIZE
	CDO				CALL_DATA_OFFSET
	INST			INSTRUCTION
	CN				CONTEXT_NUMBER
	CN_S			CONTEXT_SOURCE
	CN_T			CONTEXT_TARGET
	TERN			TERNARY
	TOT				TOTAL_NUMBER_OF_MICRO_INSTRUCTIONS
	TOTRD			TOTAL_NUMBER_OF_READS
	TOTPD			TOTAL_NUMBER_OF_PADDINGS
	OFFOOB			OFFSET_OUT_OF_BOUNDS
	IS_MICRO		IS_MICRO_INSTRUCTION
	PRE				PRECOMPUTATION
	CT				COUNTER
	MICRO_STAMP		MICRO_INSTRUCTION_STAMP
	MICRO_INST		MICRO_INSTRUCTION
	SLO				SOURCE_LIMB_OFFSET
	SBO				SOURCE_BYTE_OFFSET
	TLO				TARGET_LIMB_OFFSET
	TBO				TARGET_BYTE_OFFSET)