(module blsdata)

(defun (g2-add-hypothesis)
  (* DATA_BLS_G2_ADD_FLAG (first_row_of_new_input)))

(defconstraint internal-checks-g2-add (:guard (g2-add-hypothesis))
  (let ((A_x_Im_3 LIMB)
        (A_x_Im_2 (shift LIMB 1))
        (A_x_Im_1 (shift LIMB 2))
        (A_x_Im_0 (shift LIMB 3))
        (A_x_Re_3 (shift LIMB 4))
        (A_x_Re_2 (shift LIMB 5))
        (A_x_Re_1 (shift LIMB 6))
        (A_x_Re_0 (shift LIMB 7))
        (A_y_Im_3 (shift LIMB 8))
        (A_y_Im_2 (shift LIMB 9))
        (A_y_Im_1 (shift LIMB 10))
        (A_y_Im_0 (shift LIMB 11))
        (A_y_Re_3 (shift LIMB 12))
        (A_y_Re_2 (shift LIMB 13))
        (A_y_Re_1 (shift LIMB 14))
        (A_y_Re_0 (shift LIMB 15)))
    (wellFormedFp2CoordinatesAndInfinityCheck 0 A_x_Im_3 A_x_Im_2 A_x_Im_1 A_x_Im_0 A_x_Re_3 A_x_Re_2 A_x_Re_1 A_x_Re_0 A_y_Im_3 A_y_Im_2 A_y_Im_1 A_y_Im_0 A_y_Re_3 A_y_Re_2 A_y_Re_1 A_y_Re_0)))