(module blsdata)

(defun (pairing-check-second-input-hypothesis)
  (* DATA_BLS_PAIRING_CHECK_FLAG (first_row_of_new_second_input)))

(defconstraint internal-checks-pairing-check-second-input (:guard (pairing-check-second-input-hypothesis))
  (let ((B_x_Im_3 LIMB)
        (B_x_Im_2 (shift LIMB 1))
        (B_x_Im_1 (shift LIMB 2))
        (B_x_Im_0 (shift LIMB 3))
        (B_x_Re_3 (shift LIMB 4))
        (B_x_Re_2 (shift LIMB 5))
        (B_x_Re_1 (shift LIMB 6))
        (B_x_Re_0 (shift LIMB 7))
        (B_y_Im_3 (shift LIMB 8))
        (B_y_Im_2 (shift LIMB 9))
        (B_y_Im_1 (shift LIMB 10))
        (B_y_Im_0 (shift LIMB 11))
        (B_y_Re_3 (shift LIMB 12))
        (B_y_Re_2 (shift LIMB 13))
        (B_y_Re_1 (shift LIMB 14))
        (B_y_Re_0 (shift LIMB 15)))
    (wellFormedFp2CoordinatesAndInfinityCheck 0 B_x_Im_3 B_x_Im_2 B_x_Im_1 B_x_Im_0 B_x_Re_3 B_x_Re_2 B_x_Re_1 B_x_Re_0 B_y_Im_3 B_y_Im_2 B_y_Im_1 B_y_Im_0 B_y_Re_3 B_y_Re_2 B_y_Re_1 B_y_Re_0)))