/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  
export declare namespace IPlonkVerifier {
      
    export type ChainConfigurationParameterStruct = {value: BytesLike, name: string}

    export type ChainConfigurationParameterStructOutput = [value: string, name: string] & {value: string, name: string }
  
    }

  export interface PlonkVerifierForDataAggregationInterface extends Interface {
    getFunction(nameOrSignature: "Verify" | "getChainConfiguration"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "ChainConfigurationSet"): EventFragment;

    encodeFunctionData(functionFragment: 'Verify', values: [BytesLike, BigNumberish[]]): string;
encodeFunctionData(functionFragment: 'getChainConfiguration', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'Verify', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getChainConfiguration', data: BytesLike): Result;
  }

  
    export namespace ChainConfigurationSetEvent {
      export type InputTuple = [chainConfigurationHash: BytesLike, parameters: IPlonkVerifier.ChainConfigurationParameterStruct[]];
      export type OutputTuple = [chainConfigurationHash: string, parameters: IPlonkVerifier.ChainConfigurationParameterStructOutput[]];
      export interface OutputObject {chainConfigurationHash: string, parameters: IPlonkVerifier.ChainConfigurationParameterStructOutput[] };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface PlonkVerifierForDataAggregation extends BaseContract {
    
    connect(runner?: ContractRunner | null): PlonkVerifierForDataAggregation;
    waitForDeployment(): Promise<this>;

    interface: PlonkVerifierForDataAggregationInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    Verify: TypedContractMethod<
      [proof: BytesLike, public_inputs: BigNumberish[], ],
      [boolean],
      'view'
    >
    

    
    getChainConfiguration: TypedContractMethod<
      [],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'Verify'): TypedContractMethod<
      [proof: BytesLike, public_inputs: BigNumberish[], ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'getChainConfiguration'): TypedContractMethod<
      [],
      [string],
      'view'
    >;

    getEvent(key: 'ChainConfigurationSet'): TypedContractEvent<ChainConfigurationSetEvent.InputTuple, ChainConfigurationSetEvent.OutputTuple, ChainConfigurationSetEvent.OutputObject>;

    filters: {
      
      'ChainConfigurationSet(bytes32,tuple[])': TypedContractEvent<ChainConfigurationSetEvent.InputTuple, ChainConfigurationSetEvent.OutputTuple, ChainConfigurationSetEvent.OutputObject>;
      ChainConfigurationSet: TypedContractEvent<ChainConfigurationSetEvent.InputTuple, ChainConfigurationSetEvent.OutputTuple, ChainConfigurationSetEvent.OutputObject>;
    
    };
  }