/*
 * Copyright Consensys Software Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
 * an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

package net.consensys.linea;

import static org.junit.jupiter.api.Assertions.fail;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.util.ArrayList;
import java.util.List;
import java.util.zip.GZIPInputStream;

import com.google.gson.Gson;
import lombok.extern.slf4j.Slf4j;
import net.consensys.linea.blockcapture.snapshots.ConflationSnapshot;
import net.consensys.linea.testing.ReplayExecutionEnvironment;
import net.consensys.linea.zktracer.ChainConfig;
import net.consensys.linea.zktracer.Fork;
import net.consensys.linea.zktracer.ZkTracer;
import net.consensys.linea.zktracer.types.PublicInputs;
import org.junit.jupiter.api.TestInfo;
import org.junit.jupiter.api.extension.ExtendWith;
import org.junit.jupiter.params.provider.Arguments;

/**
 * Replays are captured on a fully (not snapshot) synchronized Besu node running the plugin:
 *
 * <pre>{@code
 * curl -X POST 'http://localhost:8545'
 * --data '{
 *    "jsonrpc":"2.0",
 *    "method":"rollup_captureConflation",
 *    "params":["296519", "296521"], "id":"1"
 *  }'
 * | jq '.result.capture' -r
 * | gzip > arithmetization/src/test/resources/replays/my-test-case.json.gz
 * }</pre>
 *
 * One can run this command: scripts/capture.pl --start xxx --end yyy --output my-test-case.json.gz
 */
@Slf4j
@ExtendWith(UnitTestWatcher.class)
public class ReplayTestTools {
  /** A list of block numbers used for testing purposes in {@link ReplayTests}. */
  static List<Arguments> BLOCK_NUMBERS = new ArrayList<>();

  /**
   * Loads a .json or .json.gz replay file generated by the {@link
   * net.consensys.linea.blockcapture.BlockCapturer} and execute it as a test.
   *
   * @param chain Chain for testing (e.g. mainnet or sepolia, etc)
   * @param filename the file in resources/replays/ containing the replay
   * @param resultChecking enable checking of transaction results. This should always be enabled.
   *     However until existing problems are resolved with the replay mechanism, it may be useful to
   *     disable this for specific tests on a case-by-case basis.
   * @param runWithBesuNode enable the test to run on a Besu node whose version is defined in libs.versions.toml
   */
  public static void replay(
      ChainConfig chain, String filename, TestInfo testInfo, boolean resultChecking, boolean runWithBesuNode) {
    final InputStream fileStream =
        ReplayTestTools.class
            .getClassLoader()
            .getResourceAsStream("replays/%s".formatted(filename));
    if (fileStream == null) {
      fail("unable to find %s in replay resources".formatted(filename));
    }

    final InputStream stream;
    try {
      stream = filename.toLowerCase().endsWith("gz") ? new GZIPInputStream(fileStream) : fileStream;
    } catch (IOException e) {
      log.error("while loading {}: {}", filename, e.getMessage());
      throw new RuntimeException(e);
    }

    final Gson gson = new Gson();
    final ConflationSnapshot conflation =
        gson.fromJson(new BufferedReader(new InputStreamReader(stream)), ConflationSnapshot.class);

    ReplayExecutionEnvironment.builder()
        .filename(filename)
        .zkTracer(
            new ZkTracer(
                chain,
                new PublicInputs(
                    conflation.historicalBlockHashes(), conflation.blobBaseFeesOrDefault())))
        .txResultChecking(resultChecking)
      .runWithBesuNode(runWithBesuNode)
        .useCoinbaseAddressFromBlockHeader(Fork.isPostPrague(chain.fork))
        .build()
        .replay(chain, testInfo, conflation);
  }

  /**
   * Implementation of replay for tests running on a given chain, with result checking enabled.
   *
   * @param chain Chain for testing (e.g. mainnet or sepolia, etc)
   * @param filename Name of replay file
   */
  public static void replay(ChainConfig chain, String filename, TestInfo testInfo) {
    // Try parsing the JSON as an object or a string containing the JSON
    replay(chain, filename, testInfo, true, false);
  }

  /**
   * Implementation of replay for tests running on a given chain, with result checking enabled.
   *
   * @param chain Chain for testing (e.g. mainnet or sepolia, etc)
   * @param filename Name of replay file
   * @param resultChecking enable checking of transaction results. This should always be enabled.
   *     However until existing problems are resolved with the replay mechanism, it may be useful to
   *     disable this for specific tests on a case-by-case basis.
   */
  public static void replay(ChainConfig chain, String filename, TestInfo testInfo, boolean resultChecking) {
    replay(chain, filename, testInfo, resultChecking, false);
  }

  /**
   * Adds a range of block numbers to the BLOCK_NUMBERS list.
   *
   * @param start the starting block number (inclusive)
   * @param end the ending block number (inclusive)
   */
  static void add(int start, int end) {
    for (int i = start; i <= end; i++) {
      BLOCK_NUMBERS.add(Arguments.of(i));
    }
  }

  /**
   * Adds a single block number to the BLOCK_NUMBERS list.
   *
   * @param start the block number to add
   */
  static void add(int start) {
    BLOCK_NUMBERS.add(Arguments.of(start));
  }
}
