// Code generated by gpu/internal/generator DO NOT EDIT

//go:build cuda

package bw6761

/*
#include "gnark_gpu.h"
*/
import "C"

import (
	"unsafe"

	fr "github.com/consensys/gnark-crypto/ecc/bw6-761/fr"
)

type pinnedFrBuffer struct {
	ptr  unsafe.Pointer
	data []fr.Element
}

func newPinnedFrBuffer(n int) (pinnedFrBuffer, error) {
	var ptr unsafe.Pointer
	nbytes := C.size_t(n) * C.size_t(fr.Bytes)
	if err := toError(C.gnark_gpu_alloc_pinned(&ptr, nbytes)); err != nil {
		return pinnedFrBuffer{}, err
	}
	return pinnedFrBuffer{
		ptr:  ptr,
		data: unsafe.Slice((*fr.Element)(ptr), n),
	}, nil
}

func (b *pinnedFrBuffer) free() {
	if b.ptr != nil {
		C.gnark_gpu_free_pinned(b.ptr)
		b.ptr = nil
		b.data = nil
	}
}
