#!/bin/bash

### PURPOSE
# This script will automate pushing a PR branch into the docs.linea.build repo
# The new PR branch will contain autogenerated smart contract documentation for the Linea monorepo
# You must manually create the Github PR yourself (from the new branch)

### ASSUMPTIONS
# - Requires permissions to create a branch on docs.linea.build repo
# - Must execute this script from within linea-monorepo (can be anywhere)

### CONSTANTS
DOCS_WEBSITE_REPO_NAME=doc.linea
DOCS_WEBSITE_REPO_GIT_LINK=https://github.com/Consensys/$DOCS_WEBSITE_REPO_NAME.git
DOCS_REPO_PR_BRANCH_NAME=update-linea-smart-contract-docs
DOCS_REPO_PR_COMMIT_MESSAGE="Update Linea smart contract docs"

UPDATE_SIDEBAR_SCRIPT_NAME=updateSidebar.js
UPDATE_SIDEBAR_SCRIPT_PATH=contracts/docs/scripts/$UPDATE_SIDEBAR_SCRIPT_NAME
MONOREPO_SMART_CONTRACT_DOCS_DIRECTORY=contracts/docs/api

DOCS_REPO_SMART_CONTRACT_DOC_DIRECTORY=docs/api/linea-smart-contracts

### SCRIPT START

# Ensure that `contracts` is the starting working directory
MONOREPO_ROOT_PATH=$(git rev-parse --show-toplevel)
cd $MONOREPO_ROOT_PATH
cd contracts

# Docgen
npx hardhat docgen

# Git clone docs website repo and create a new branch
cd $MONOREPO_ROOT_PATH
cd ..
git clone $DOCS_WEBSITE_REPO_GIT_LINK --depth 1
cd $DOCS_WEBSITE_REPO_NAME
DOCS_WEBSITE_REPO_PATH=$(pwd)
git checkout -b $DOCS_REPO_PR_BRANCH_NAME

# Copy autogenerated smart contract docs + UPDATE_SIDEBAR_SCRIPT to docs website repo
cd $MONOREPO_ROOT_PATH
rm -rf "$DOCS_WEBSITE_REPO_PATH/$DOCS_REPO_SMART_CONTRACT_DOC_DIRECTORY"
cp -r "$MONOREPO_ROOT_PATH/$MONOREPO_SMART_CONTRACT_DOCS_DIRECTORY" "$DOCS_WEBSITE_REPO_PATH/$DOCS_REPO_SMART_CONTRACT_DOC_DIRECTORY"
cp "$MONOREPO_ROOT_PATH/$UPDATE_SIDEBAR_SCRIPT_PATH" "$DOCS_WEBSITE_REPO_PATH/$UPDATE_SIDEBAR_SCRIPT_NAME"

# Ensure directories is entirely lowercase
# To pass Github Action enforcing no uppercase for file name
for FOLDER in `find "$DOCS_WEBSITE_REPO_PATH/$DOCS_REPO_SMART_CONTRACT_DOC_DIRECTORY" -type d`
do
    # NEW_FILENAME=$(echo $FILENAME | tr 'A-Z' 'a-z')
    NEW_FOLDER=$(echo $FOLDER | tr 'A-Z' 'a-z')
    mv $FOLDER $NEW_FOLDER
done;

# Ensure filenames is entirely lowercase
# To pass Github Action enforcing no uppercase for file name
for FILENAME in `find "$DOCS_WEBSITE_REPO_PATH/$DOCS_REPO_SMART_CONTRACT_DOC_DIRECTORY" -type f  \( -iname \*.md -o -iname \*.mdx \)`
do
    NEW_FILENAME=$(echo $FILENAME | tr 'A-Z' 'a-z')
    mv $FILENAME $NEW_FILENAME
done;

# Execute UPDATE_SIDEBAR_SCRIPT then delete the script (so it is not in the commit)
cd $DOCS_WEBSITE_REPO_PATH
node $UPDATE_SIDEBAR_SCRIPT_NAME
rm $UPDATE_SIDEBAR_SCRIPT_NAME

# Git commit and push
git add .
git commit -m "$DOCS_REPO_PR_COMMIT_MESSAGE"
git push --set-upstream origin $DOCS_REPO_PR_BRANCH_NAME