// Code generated by gpu/internal/generator DO NOT EDIT

// Package bls12377 provides GPU-accelerated PlonK operations for the bls12377 curve.
//
// Generated from gpu/internal/generator. Do not edit by hand.
// Re-generate with: cd gpu/internal/generator && go run .
package bls12377
