(module hub_v2)

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;                                             ;;
;;   10.2 SCEN/CREATE instruction shorthands   ;;
;;                                             ;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

;;  CREATE/failure_condition
(defun (scen-shorthand-CREATE-failure-condition)
  (+ 
    ;; CREATE_EXCEPTION
    ;; CREATE_ABORT
    CREATE_FAILURE_CONDITION_WILL_REVERT
    CREATE_FAILURE_CONDITION_WONT_REVERT
    ;; CREATE_EMPTY_INIT_CODE_WILL_REVERT
    ;; CREATE_EMPTY_INIT_CODE_WONT_REVERT
    ;; CREATE_NONEMPTY_INIT_CODE_FAILURE_WILL_REVERT
    ;; CREATE_NONEMPTY_INIT_CODE_FAILURE_WONT_REVERT
    ;; CREATE_NONEMPTY_INIT_CODE_SUCCESS_WILL_REVERT
    ;; CREATE_NONEMPTY_INIT_CODE_SUCCESS_WONT_REVERT
    ))

;;  CREATE/execution_will_revert
(defun (scen-shorthand-CREATE-execution-will-revert)
  (+ 
    ;; CREATE_EXCEPTION
    ;; CREATE_ABORT
    ;; CREATE_FAILURE_CONDITION_WILL_REVERT
    ;; CREATE_FAILURE_CONDITION_WONT_REVERT
    CREATE_EMPTY_INIT_CODE_WILL_REVERT
    ;; CREATE_EMPTY_INIT_CODE_WONT_REVERT
    CREATE_NONEMPTY_INIT_CODE_FAILURE_WILL_REVERT
    ;; CREATE_NONEMPTY_INIT_CODE_FAILURE_WONT_REVERT
    CREATE_NONEMPTY_INIT_CODE_SUCCESS_WILL_REVERT
    ;; CREATE_NONEMPTY_INIT_CODE_SUCCESS_WONT_REVERT
    ))

;;  CREATE/execution_wont_revert
(defun (scen-shorthand-CREATE-execution-wont-revert)
  (+ 
    ;; CREATE_EXCEPTION
    ;; CREATE_ABORT
    ;; CREATE_FAILURE_CONDITION_WILL_REVERT
    ;; CREATE_FAILURE_CONDITION_WONT_REVERT
    ;; CREATE_EMPTY_INIT_CODE_WILL_REVERT
    CREATE_EMPTY_INIT_CODE_WONT_REVERT
    ;; CREATE_NONEMPTY_INIT_CODE_FAILURE_WILL_REVERT
    CREATE_NONEMPTY_INIT_CODE_FAILURE_WONT_REVERT
    ;; CREATE_NONEMPTY_INIT_CODE_SUCCESS_WILL_REVERT
    CREATE_NONEMPTY_INIT_CODE_SUCCESS_WONT_REVERT
    ))

;;  CREATE/empty_init_code
(defun (scen-shorthand-CREATE-empty-init-code)
  (+ 
    ;; CREATE_EXCEPTION
    ;; CREATE_ABORT
    ;; CREATE_FAILURE_CONDITION_WILL_REVERT
    ;; CREATE_FAILURE_CONDITION_WONT_REVERT
    CREATE_EMPTY_INIT_CODE_WILL_REVERT
    CREATE_EMPTY_INIT_CODE_WONT_REVERT
    ;; CREATE_NONEMPTY_INIT_CODE_FAILURE_WILL_REVERT
    ;; CREATE_NONEMPTY_INIT_CODE_FAILURE_WONT_REVERT
    ;; CREATE_NONEMPTY_INIT_CODE_SUCCESS_WILL_REVERT
    ;; CREATE_NONEMPTY_INIT_CODE_SUCCESS_WONT_REVERT
    ))

;;  CREATE/nonempty_init_code
(defun (scen-shorthand-CREATE-nonempty-init-code)
  (+ 
    ;; CREATE_EXCEPTION
    ;; CREATE_ABORT
    ;; CREATE_FAILURE_CONDITION_WILL_REVERT
    ;; CREATE_FAILURE_CONDITION_WONT_REVERT
    ;; CREATE_EMPTY_INIT_CODE_WILL_REVERT
    ;; CREATE_EMPTY_INIT_CODE_WONT_REVERT
    CREATE_NONEMPTY_INIT_CODE_FAILURE_WILL_REVERT
    CREATE_NONEMPTY_INIT_CODE_FAILURE_WONT_REVERT
    CREATE_NONEMPTY_INIT_CODE_SUCCESS_WILL_REVERT
    CREATE_NONEMPTY_INIT_CODE_SUCCESS_WONT_REVERT
    ))

;;  CREATE/execution
(defun (scen-shorthand-CREATE-execution)
  (+ 
    (scen-shorthand-CREATE-nonempty-init-code)
    (scen-shorthand-CREATE-empty-init-code)
    ;; CREATE_EXCEPTION
    ;; CREATE_ABORT
    ;; CREATE_FAILURE_CONDITION_WILL_REVERT
    ;; CREATE_FAILURE_CONDITION_WONT_REVERT
    ;; CREATE_EMPTY_INIT_CODE_WILL_REVERT
    ;; CREATE_EMPTY_INIT_CODE_WONT_REVERT
    ;; CREATE_NONEMPTY_INIT_CODE_FAILURE_WILL_REVERT
    ;; CREATE_NONEMPTY_INIT_CODE_FAILURE_WONT_REVERT
    ;; CREATE_NONEMPTY_INIT_CODE_SUCCESS_WILL_REVERT
    ;; CREATE_NONEMPTY_INIT_CODE_SUCCESS_WONT_REVERT
    ))

;;  CREATE/undo_account_operations
(defun (scen-shorthand-CREATE-undo-account-operations)
  (+ 
    ;; CREATE_EXCEPTION
    ;; CREATE_ABORT
    ;; CREATE_FAILURE_CONDITION_WILL_REVERT
    ;; CREATE_FAILURE_CONDITION_WONT_REVERT
    CREATE_EMPTY_INIT_CODE_WILL_REVERT
    ;; CREATE_EMPTY_INIT_CODE_WONT_REVERT
    CREATE_NONEMPTY_INIT_CODE_FAILURE_WILL_REVERT
    CREATE_NONEMPTY_INIT_CODE_FAILURE_WONT_REVERT
    CREATE_NONEMPTY_INIT_CODE_SUCCESS_WILL_REVERT
    ;; CREATE_NONEMPTY_INIT_CODE_SUCCESS_WONT_REVERT
    ))

;;  CREATE/compute_deployment_address
(defun (scen-shorthand-CREATE-compute-deployment-address)
  (+ 
    (scen-shorthand-CREATE-failure-condition)
    (scen-shorthand-CREATE-execution)
    ;; CREATE_EXCEPTION
    ;; CREATE_ABORT
    ;; CREATE_FAILURE_CONDITION_WILL_REVERT
    ;; CREATE_FAILURE_CONDITION_WONT_REVERT
    ;; CREATE_EMPTY_INIT_CODE_WILL_REVERT
    ;; CREATE_EMPTY_INIT_CODE_WONT_REVERT
    ;; CREATE_NONEMPTY_INIT_CODE_FAILURE_WILL_REVERT
    ;; CREATE_NONEMPTY_INIT_CODE_FAILURE_WONT_REVERT
    ;; CREATE_NONEMPTY_INIT_CODE_SUCCESS_WILL_REVERT
    ;; CREATE_NONEMPTY_INIT_CODE_SUCCESS_WONT_REVERT
    ))

;;  CREATE/unexceptional
(defun (scen-shorthand-CREATE-unexceptional)
  (+ 
    ;; CREATE_EXCEPTION
    CREATE_ABORT
    ;; CREATE_FAILURE_CONDITION_WILL_REVERT
    ;; CREATE_FAILURE_CONDITION_WONT_REVERT
    ;; CREATE_EMPTY_INIT_CODE_WILL_REVERT
    ;; CREATE_EMPTY_INIT_CODE_WONT_REVERT
    ;; CREATE_NONEMPTY_INIT_CODE_FAILURE_WILL_REVERT
    ;; CREATE_NONEMPTY_INIT_CODE_FAILURE_WONT_REVERT
    ;; CREATE_NONEMPTY_INIT_CODE_SUCCESS_WILL_REVERT
    ;; CREATE_NONEMPTY_INIT_CODE_SUCCESS_WONT_REVERT
    (scen-shorthand-CREATE-failure-condition)
    (scen-shorthand-CREATE-execution)
    ))

;;  CREATE/sum
(defun (scen-shorthand-CREATE-sum)
  (+ 
    CREATE_EXCEPTION
    ;; CREATE_ABORT
    ;; CREATE_FAILURE_CONDITION_WILL_REVERT
    ;; CREATE_FAILURE_CONDITION_WONT_REVERT
    ;; CREATE_EMPTY_INIT_CODE_WILL_REVERT
    ;; CREATE_EMPTY_INIT_CODE_WONT_REVERT
    ;; CREATE_NONEMPTY_INIT_CODE_FAILURE_WILL_REVERT
    ;; CREATE_NONEMPTY_INIT_CODE_FAILURE_WONT_REVERT
    ;; CREATE_NONEMPTY_INIT_CODE_SUCCESS_WILL_REVERT
    ;; CREATE_NONEMPTY_INIT_CODE_SUCCESS_WONT_REVERT
    (scen-shorthand-CREATE-unexceptional)
    ))

;;  CREATE/no_context_change
(defun (scen-shorthand-CREATE-no-context-change)
  (+ 
    ;; CREATE_EXCEPTION
    CREATE_ABORT
    ;; CREATE_FAILURE_CONDITION_WILL_REVERT
    ;; CREATE_FAILURE_CONDITION_WONT_REVERT
    ;; CREATE_EMPTY_INIT_CODE_WILL_REVERT
    ;; CREATE_EMPTY_INIT_CODE_WONT_REVERT
    ;; CREATE_NONEMPTY_INIT_CODE_FAILURE_WILL_REVERT
    ;; CREATE_NONEMPTY_INIT_CODE_FAILURE_WONT_REVERT
    ;; CREATE_NONEMPTY_INIT_CODE_SUCCESS_WILL_REVERT
    ;; CREATE_NONEMPTY_INIT_CODE_SUCCESS_WONT_REVERT
    (scen-shorthand-CREATE-failure-condition)
    (scen-shorthand-CREATE-empty-init-code)
    ))

;;  CREATE/deployment_success
(defun (scen-shorthand-CREATE-deployment-success)
  (+ 
    ;; CREATE_EXCEPTION
    ;; CREATE_ABORT
    ;; CREATE_FAILURE_CONDITION_WILL_REVERT
    ;; CREATE_FAILURE_CONDITION_WONT_REVERT
    CREATE_EMPTY_INIT_CODE_WILL_REVERT
    CREATE_EMPTY_INIT_CODE_WONT_REVERT
    ;; CREATE_NONEMPTY_INIT_CODE_FAILURE_WILL_REVERT
    ;; CREATE_NONEMPTY_INIT_CODE_FAILURE_WONT_REVERT
    CREATE_NONEMPTY_INIT_CODE_SUCCESS_WILL_REVERT
    CREATE_NONEMPTY_INIT_CODE_SUCCESS_WONT_REVERT
    ))

;;  CREATE/deployment_failure
(defun (scen-shorthand-CREATE-deployment-failure)
  (+ 
    ;; CREATE_EXCEPTION
    ;; CREATE_ABORT
    ;; CREATE_FAILURE_CONDITION_WILL_REVERT
    ;; CREATE_FAILURE_CONDITION_WONT_REVERT
    ;; CREATE_EMPTY_INIT_CODE_WILL_REVERT
    ;; CREATE_EMPTY_INIT_CODE_WONT_REVERT
    CREATE_NONEMPTY_INIT_CODE_FAILURE_WILL_REVERT
    CREATE_NONEMPTY_INIT_CODE_FAILURE_WONT_REVERT
    ;; CREATE_NONEMPTY_INIT_CODE_SUCCESS_WILL_REVERT
    ;; CREATE_NONEMPTY_INIT_CODE_SUCCESS_WONT_REVERT
    ))


;; ;;  CREATE/
;; (defun (scen-shorthand-CREATE-)
;;   (+ 
;;     CREATE_EXCEPTION
;;     CREATE_ABORT
;;     CREATE_FAILURE_CONDITION_WILL_REVERT
;;     CREATE_FAILURE_CONDITION_WONT_REVERT
;;     CREATE_EMPTY_INIT_CODE_WILL_REVERT
;;     CREATE_EMPTY_INIT_CODE_WONT_REVERT
;;     CREATE_NONEMPTY_INIT_CODE_FAILURE_WILL_REVERT
;;     CREATE_NONEMPTY_INIT_CODE_FAILURE_WONT_REVERT
;;     CREATE_NONEMPTY_INIT_CODE_SUCCESS_WILL_REVERT
;;     CREATE_NONEMPTY_INIT_CODE_SUCCESS_WONT_REVERT
;;     ))
