(module blsdata)

(defun (wcpCallToLT k a b c d)
  (begin (eq! (shift WCP_FLAG k) 1)
         (eq! (shift WCP_INST k) EVM_INST_LT)
         (eq! (shift WCP_ARG1_HI k) a)
         (eq! (shift WCP_ARG1_LO k) b)
         (eq! (shift WCP_ARG2_HI k) c)
         (eq! (shift WCP_ARG2_LO k) d)))

(defun (wcpCallToEQ k a b c d)
  (begin (eq! (shift WCP_FLAG k) 1)
         (eq! (shift WCP_INST k) EVM_INST_EQ)
         (eq! (shift WCP_ARG1_HI k) a)
         (eq! (shift WCP_ARG1_LO k) b)
         (eq! (shift WCP_ARG2_HI k) c)
         (eq! (shift WCP_ARG2_LO k) d)))

(defun (wcpGeneralizedCallToLT k a b c d e f g h)
    (begin (wcpCallToLT (+ k 1) a b e f)
           (wcpCallToEQ (+ k 2) a b e f)
           (wcpCallToLT (+ k 3) c d g h)
           (eq! (shift WCP_RES k) 
                (+ (shift WCP_RES (+ k 1))
                   (* (shift WCP_RES (+ k 2)) (shift WCP_RES (+ k 3)))))))