(module rlpTxRcpt)

(defconst 
  SUBPHASE_ID_TYPE               7
  SUBPHASE_ID_STATUS_CODE        2
  SUBPHASE_ID_CUMUL_GAS          3
  SUBPHASE_ID_NO_LOG_ENTRY       11
  SUBPHASE_ID_ADDR               53
  SUBPHASE_ID_TOPIC_BASE         65
  SUBPHASE_ID_DATA_LIMB          77
  SUBPHASE_ID_DATA_SIZE          83
  SUBPHASE_ID_TOPIC_DELTA        96
  SUBPHASE_ID_WEIGHT_IS_PREFIX   6
  SUBPHASE_ID_WEIGHT_IS_OT       12
  SUBPHASE_ID_WEIGHT_IS_OD       24
  SUBPHASE_ID_WEIGHT_DEPTH       48
  SUBPHASE_ID_WEIGHT_INDEX_LOCAL 96)


