(module blsdata)

(defun (same_data_to_data)
    (+ (* DATA_POINT_EVALUATION_FLAG (next DATA_POINT_EVALUATION_FLAG))
       (* DATA_BLS_G1_ADD_FLAG (next DATA_BLS_G1_ADD_FLAG))
       (* DATA_BLS_G1_MSM_FLAG (next DATA_BLS_G1_MSM_FLAG))
       (* DATA_BLS_G2_ADD_FLAG (next DATA_BLS_G2_ADD_FLAG))
       (* DATA_BLS_G2_MSM_FLAG (next DATA_BLS_G2_MSM_FLAG))
       (* DATA_BLS_PAIRING_CHECK_FLAG (next DATA_BLS_PAIRING_CHECK_FLAG))
       (* DATA_BLS_MAP_FP_TO_G1_FLAG (next DATA_BLS_MAP_FP_TO_G1_FLAG))
       (* DATA_BLS_MAP_FP2_TO_G2_FLAG (next DATA_BLS_MAP_FP2_TO_G2_FLAG))))

(defun (same_data_to_result)
    (+ (* DATA_POINT_EVALUATION_FLAG (next RSLT_POINT_EVALUATION_FLAG))
       (* DATA_BLS_G1_ADD_FLAG (next RSLT_BLS_G1_ADD_FLAG))
       (* DATA_BLS_G1_MSM_FLAG (next RSLT_BLS_G1_MSM_FLAG))
       (* DATA_BLS_G2_ADD_FLAG (next RSLT_BLS_G2_ADD_FLAG))
       (* DATA_BLS_G2_MSM_FLAG (next RSLT_BLS_G2_MSM_FLAG))
       (* DATA_BLS_PAIRING_CHECK_FLAG (next RSLT_BLS_PAIRING_CHECK_FLAG))
       (* DATA_BLS_MAP_FP_TO_G1_FLAG (next RSLT_BLS_MAP_FP_TO_G1_FLAG))
       (* DATA_BLS_MAP_FP2_TO_G2_FLAG (next RSLT_BLS_MAP_FP2_TO_G2_FLAG))))

(defun (same_result_to_result)
    (+ (* RSLT_POINT_EVALUATION_FLAG (next RSLT_POINT_EVALUATION_FLAG))
       (* RSLT_BLS_G1_ADD_FLAG (next RSLT_BLS_G1_ADD_FLAG))
       (* RSLT_BLS_G1_MSM_FLAG (next RSLT_BLS_G1_MSM_FLAG))
       (* RSLT_BLS_G2_ADD_FLAG (next RSLT_BLS_G2_ADD_FLAG))
       (* RSLT_BLS_G2_MSM_FLAG (next RSLT_BLS_G2_MSM_FLAG))
       (* RSLT_BLS_PAIRING_CHECK_FLAG (next RSLT_BLS_PAIRING_CHECK_FLAG))
       (* RSLT_BLS_MAP_FP_TO_G1_FLAG (next RSLT_BLS_MAP_FP_TO_G1_FLAG))
       (* RSLT_BLS_MAP_FP2_TO_G2_FLAG (next RSLT_BLS_MAP_FP2_TO_G2_FLAG))))

(defconstraint legal-transitions ()
    (if-not-zero STAMP 
        (eq! (+ (same_data_to_data)
                (same_data_to_result)
                (same_result_to_result)
                (transition_to_data)) 1))) 