name: Tracer riscv-constraints check compilation

on:
  pull_request:
    branches:
      - main
    paths:
      - 'arithmetization/**'
      - '.github/actions/setup-arithmetization-riscv/**'
      - '.github/workflows/arithmetization-*.yml'
  push:
    branches:
     - main
    paths:
     - 'arithmetization/**'
     - '.github/actions/setup-arithmetization-riscv/**'
     - '.github/workflows/arithmetization-*.yml'
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read
  actions: read

jobs:
  build:
    runs-on: gha-runner-scale-set-ubuntu-24-amd64-small
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: false

      - name: Setup Environment
        uses: ./.github/actions/setup-arithmetization-riscv

      - name: Linting Check
        run: make -C arithmetization riscv-check-lint
	
      - name: Install zkc and check compilation of RISC-V in ZkC
        run: make -C arithmetization riscv-check-compilation
