name: Tracer sample guest programs run (Add in Zig and Blake in Rust)

on:
  pull_request:
    branches:
      - main
    paths:
      - 'arithmetization/**'
      - '.github/actions/setup-arithmetization-riscv/**'
      - '.github/workflows/arithmetization-*.yml'
  push:
    branches:
     - main
    paths:
     - 'arithmetization/**'
     - '.github/actions/setup-arithmetization-riscv/**'
     - '.github/workflows/arithmetization-*.yml'
  workflow_call:
    inputs:
      zkc-ref:
        description: 'zkc commit/branch/tag (defaults to main)'
        required: false
        type: string
  workflow_dispatch:
    inputs:
      zkc-ref:
        description: 'zkc commit/branch/tag (defaults to main)'
        required: false
        type: string

permissions:
  contents: read
  actions: read

jobs:
  sample-guest-programs-run:
    runs-on: gha-lfdt-lineth-ss-ubuntu-24-amd64-large
    env:
      ZKC_REF: ${{ inputs.zkc-ref || 'main' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: false

      - name: Setup Environment
        uses: ./.github/actions/setup-arithmetization-riscv

      - name: Install zkc and run simple Zig guest program with zkc interpreter
        # IN_BYTES values not used in the sum test program but is still written in memory
        run: make TEST=test.zig IN_BYTES="0xAABB" IN_ORIGIN=0x08800000
        working-directory: arithmetization/src/test/examples
        timeout-minutes: 6

      - name: Run Blake rust against test vectors with zkc interpreter
        run: make blake-rust-exec
        working-directory: arithmetization/src/test/examples
        timeout-minutes: 30
