name: Tracer sample guest programs run (Add and Blake)

on:
  pull_request:
    branches:
      - main
    paths:
      - 'arithmetization/**'
      - '.github/actions/setup-arithmetization-riscv/**'
      - '.github/workflows/arithmetization-*.yml'
  push:
    branches:
     - main
    paths:
     - 'arithmetization/**'
     - '.github/actions/setup-arithmetization-riscv/**'
     - '.github/workflows/arithmetization-*.yml'
  workflow_call:
    inputs:
      go-corset-ref:
        description: 'go-corset commit/branch/tag for zkc (defaults to main)'
        required: false
        type: string
  workflow_dispatch:
    inputs:
      go-corset-ref:
        description: 'go-corset commit/branch/tag for zkc (defaults to main)'
        required: false
        type: string

permissions:
  contents: read
  actions: read

jobs:
  build:
    runs-on: gha-runner-scale-set-ubuntu-24-amd64-small
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: false

      - name: Setup Environment
        uses: ./.github/actions/setup-arithmetization-riscv

      - name: Install zkc and run simple Zig guest program with zkc interpreter
        # IN_BYTES values not used in the sum test program but is still written in memory
        run: make TEST=test.zig IN_BYTES="0xAABB" IN_BYTES_OFFSET=0x08800000
        working-directory: arithmetization/src/test/examples
        env:
          ## Override with a custom go-corset repo commit here in the event zkc on main is failing
          GO_CORSET_REF_FOR_ZKC: ${{ inputs.go-corset-ref || 'main' }}
        timeout-minutes: 6

      - name: Run Blake test vectors with zkc
        run: make blake-all
        working-directory: arithmetization/src/test/examples
        env:
          GO_CORSET_REF_FOR_ZKC: ${{ inputs.go-corset-ref || 'main' }}
        timeout-minutes: 30
