name: "Besu Package Release (manual)"

permissions:
  actions: read
  id-token: write
  contents: write
  packages: write

on:
  workflow_dispatch:
    inputs:
      release_tag_prefix:
        description: 'Custom release tag prefix, i.e. docker image tag would be [prefix]-[YYYYMMDDHHMMSS]-[commit], if not given, would be [besu-package-semver]-[YYYYMMDDHHMMSS]-[commit]'
        required: false
        type: string
        default: ''
      draft_release:
        description: 'Draft Release'
        required: false
        default: false
        type: boolean
      pre_release:
        description: 'Pre Release'
        required: false
        default: false
        type: boolean
      without_besu_fleet_plugin:
        description: 'Type "true" to exclude besu-fleet-plugin in the release'
        required: false
        type: string
        default: ''
  push:
    branches:
      - feat/coordinator-automate-changelog-versioning-poc
    paths:
      - linea-besu-package/RELEASE_TEST.md

concurrency:
  group: besu-package-release-${{ github.ref }}
  cancel-in-progress: false

jobs:
  release-besu-package:
    uses: ./.github/workflows/reusable-component-release.yml
    with:
      component-name: besu-package
      folder-name: linea-besu-package
      include-path: '["tracer/**","tracer-constraints/**","besu-plugins/linea-sequencer/**","linea-besu/**","linea-besu-package/**","gradle/libs.versions.toml"]'

  build-besu-package-docker-image-and-gh-release:
    needs: [release-besu-package]
    uses: ./.github/workflows/reuse-linea-besu-package-build-test-push.yml
    if: needs.release-besu-package.outputs.docker_tag != ''
    with:
      release_tag_prefix: ${{ inputs.release_tag_prefix != '' && inputs.release_tag_prefix || needs.release-besu-package.outputs.release_version }}
      run_test: true
      run_e2e_test: true
      push_image: true
      draft_release: ${{ inputs.draft_release || true }}
      pre_release: ${{ inputs.pre_release || false}}
      with_besu_fleet_plugin: ${{ inputs.without_besu_fleet_plugin != 'true' }}
      changelog: ${{ needs.release-besu-package.outputs.changelog }}
    secrets: inherit
