name: Check target lib versions changes

permissions:
  contents: read
  actions: read

on:
  workflow_call:
    outputs:
      besu_commit_changed:
        description: 'Whether the target lib version has changed: true (changed) and false (unchanged)'
        value: ${{ jobs.check_lib_version_change.outputs.besu_commit_changed }}

concurrency:
  group: check-lib-versions-changes-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  check_lib_version_change:
    runs-on: gha-lfdt-lineth-ss-ubuntu-24-amd64-small
    outputs:
      besu_commit_changed: ${{ steps.check_besu_commit.outputs.version_changed }}

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 2

      - name: Check besuCommit change
        uses: ./.github/actions/check-lib-version-change
        id: check_besu_commit
        with:
          target_lib: besuCommit
          target_file_path: gradle/libs.versions.toml