name: "Linea Besu Release (still in testing phase)"

permissions:
  actions: read
  id-token: write
  contents: write
  packages: write

on:
  workflow_call:
    inputs:
      image_tag_suffix:
        description: 'Custom image tag suffix, i.e. docker image tag would be [semver]-[YYYYMMDDHHMMSS]-[commit]-[suffix], if not given, would be [semver]-[YYYYMMDDHHMMSS]-[commit]'
        required: false
        type: string
        default: ''
      without_besu_fleet_plugin:
        description: 'Type "true" to exclude besu-fleet-plugin in the release'
        required: false
        type: string
        default: ''
      draft_release:
        description: 'Draft Release'
        required: false
        default: false
        type: boolean
      pre_release:
        description: 'Pre Release'
        required: false
        default: false
        type: boolean
      build_local_only:
        description: 'Build local image only'
        required: false
        default: false
        type: boolean
    outputs:
      tag_changed:
        description: "Indicate whether the release tag of the component has changed"
        value: ${{ jobs.compute-linea-besu-release-metadata.outputs.tag_changed }}
      docker_tag:
        description: "Docker image tag associated with the release tag, empty if tag_changed is false"
        value: ${{ inputs.build_local_only && jobs.build-and-upload-artifact.outputs.linea_besu_package_tag || jobs.build-linea-besu-docker-image-and-gh-release.outputs.linea_besu_package_tag }}
      release_version:
        description: "Release semver associated with the release tag (e.g. 1.2.3), empty if tag_changed is false"
        value: ${{ jobs.compute-linea-besu-release-metadata.release_version }}
      release_tag:
        description: "Release tag (e.g. releases/coordinator/v1.2.3), empty if tag_changed is false"
        value: ${{ jobs.compute-linea-besu-release-metadata.outputs.release_tag }}

  workflow_dispatch:
    inputs:
      image_tag_suffix:
        description: 'Custom image tag suffix, i.e. docker image tag would be [semver]-[YYYYMMDDHHMMSS]-[commit]-[suffix], if not given, would be [semver]-[YYYYMMDDHHMMSS]-[commit]'
        required: false
        type: string
        default: ''
      without_besu_fleet_plugin:
        description: 'Type "true" to exclude besu-fleet-plugin in the release'
        required: false
        type: string
        default: ''
      draft_release:
        description: 'Draft Release'
        required: false
        default: false
        type: boolean
      pre_release:
        description: 'Pre Release'
        required: false
        default: false
        type: boolean

concurrency:
  group: linea-besu-release-${{ github.ref }}
  cancel-in-progress: false

jobs:
  compute-linea-besu-release-metadata:
    uses: ./.github/workflows/reusable-component-release-metadata.yml
    with:
      component-name: linea-besu
      include-path: '["tracer/**","tracer-constraints/**","linea-besu/plugins/linea-sequencer/**","linea-besu/**","gradle/libs.versions.toml"]'

  build-and-upload-artifact:
    needs: [compute-linea-besu-release-metadata]
    if: ${{ needs.compute-linea-besu-release-metadata.outputs.tag_changed == 'true' }}
    uses: ./.github/workflows/linea-besu-package-build-and-upload.yml
    with:
      release_tag_prefix: ${{ needs.compute-linea-besu-release-metadata.outputs.release_version }}
      with_besu_fleet_plugin: ${{ inputs.without_besu_fleet_plugin != 'true' }}
    secrets: inherit

  run-test:
    needs: [ build-and-upload-artifact ]
    if: ${{ !inputs.build_local_only }}
    concurrency:
      group: run-test-${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}
    uses: ./.github/workflows/reuse-linea-besu-package-run-test.yml
    with:
      dockerimage: ${{ needs.build-and-upload-artifact.outputs.dockerimage }}

  run-e2e-tests:
    needs: [ build-and-upload-artifact ]
    if: ${{ !inputs.build_local_only }}
    concurrency:
      group: run-e2e-tests-${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}
    uses: ./.github/workflows/reuse-linea-besu-package-run-e2e-tests.yml
    with:
      linea_besu_package_tag: ${{ needs.build-and-upload-artifact.outputs.linea_besu_package_tag }}
      e2e-tests-logs-dump: true
      e2e-tests-with-besu-fleet: ${{ inputs.without_besu_fleet_plugin != 'true' }}
    secrets: inherit

  release-linea-besu-push-tag-changelog:
    needs: [run-test, run-e2e-tests]
    uses: ./.github/workflows/reusable-component-release-push-tag-changelog.yml
    with:
      component-name: linea-besu
      folder-name: linea-besu/package
      include-path: '["tracer/**","tracer-constraints/**","linea-besu/plugins/linea-sequencer/**","linea-besu/**","gradle/libs.versions.toml"]'
    secrets: inherit

  build-linea-besu-docker-image-and-gh-release:
    needs: [compute-linea-besu-release-metadata, release-linea-besu-push-tag-changelog]
    uses: ./.github/workflows/reuse-linea-besu-package-build-test-push.yml
    with:
      release_tag_prefix: ${{ needs.compute-linea-besu-release-metadata.outputs.release_version }}
      image_tag_suffix: ${{ inputs.image_tag_suffix }}
      run_test: false
      run_e2e_test: false
      push_image: true
      draft_release: ${{ inputs.draft_release }}
      pre_release: ${{ inputs.pre_release }}
      with_besu_fleet_plugin: ${{ inputs.without_besu_fleet_plugin != 'true' }}
      changelog: ${{ needs.compute-linea-besu-release-metadata.outputs.changelog }}
      release_tag: ${{ needs.compute-linea-besu-release-metadata.outputs.release_tag }}
      release_version: ${{ needs.compute-linea-besu-release-metadata.outputs.release_version }}
    secrets: inherit
