name: partial-prover-e2e-tests

permissions:
  actions: read
  contents: read
  packages: read

on:
  workflow_dispatch:
    inputs:
      linea_besu_package_image_tag:
        description: 'Target linea-besu-package image tag, if not given, would build the linea-besu-package image from source'
        required: false
        type: string
      prover_image_tag:
        description: 'Target prover image tag, if not given, would build the prover image from source'
        required: false
        type: string
      shomei_image_tag:
        description: 'Target shomei image tag, if not given, would use the version declared in docker/compose-spec-l2-services.yml'
        required: false
        type: string

jobs:
  build-and-upload-images:
    runs-on: gha-runner-scale-set-ubuntu-24-amd64-med
    concurrency:
      group: build-images-${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}
    name: Build docker images from source and upload (if needed) for e2e tests
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup Tracer Environment (for linea-besu-package build)
        if: ${{ inputs.linea_besu_package_image_tag == '' }}
        uses: ./.github/actions/setup-tracer-environment

      - name: Build linea-besu-package from source 
        if: ${{ inputs.linea_besu_package_image_tag == '' }}
        shell: bash
        run: cd linea-besu/package && make build
        env:
          JAVA_OPTS: -Xmx2g

      - name: show folder structure
        if: ${{ inputs.linea_besu_package_image_tag == '' }}
        shell: bash
        run: |
          cd linea-besu/package
          sudo apt update
          sudo apt-get install --no-install-recommends --assume-yes tree
          tree .
      
      - name: Save linea-besu-package docker image as artifact
        if: ${{ inputs.linea_besu_package_image_tag == '' }}
        run: |
          docker images
          docker save consensys/linea-besu-package:local | gzip > linea-besu-package-image.tar.gz
        shell: bash

      - name: Upload linea-besu-package docker image artifact
        if: ${{ inputs.linea_besu_package_image_tag == '' }}
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a #v7
        with:
          name: linea-besu-package
          path: linea-besu-package-image.tar.gz
          retention-days: 1

      - name: Install Go (for prover build)
        if: ${{ inputs.linea_besu_package_image_tag != '' &&  inputs.prover_image_tag == '' }}
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version: '1.24.6'
          cache-dependency-path: "**/*.sum"

      - name: Build prover from source 
        if: ${{ inputs.prover_image_tag == '' }}
        shell: bash
        run: cd linea-besu/package && make build-prover
        env:
          JAVA_OPTS: -Xmx2g -Dorg.gradle.daemon=false

      - name: Save prover docker image as artifact
        if: ${{ inputs.prover_image_tag == '' }}
        run: |
          docker images
          docker save consensys/linea-prover:local | gzip > linea-prover-image.tar.gz
        shell: bash

      - name: Upload prover docker image artifact
        if: ${{ inputs.prover_image_tag == '' }}
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a #v7
        with:
          name: linea-prover
          path: linea-prover-image.tar.gz
          retention-days: 1
  
  run-e2e-tests-with-partial-prover:
    needs: [build-and-upload-images]
    uses: ./.github/workflows/partial-prover-run-e2e-tests-in-parallel.yml
    with:
      linea_besu_package_image_tag: ${{ inputs.linea_besu_package_image_tag }}
      prover_image_tag: ${{ inputs.prover_image_tag }}
      shomei_image_tag: ${{ inputs.shomei_image_tag }}

