name: "Lint Commit Messages"

permissions:
  contents: read

on:
  workflow_call:

concurrency:
  group: lint-commit-messages-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-latest-commit-messages:
    if: github.event_name == 'pull_request'
    runs-on: gha-runner-scale-set-ubuntu-24-amd64-small
    name: Lint latest PR commit messages
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          # Need enough history to resolve the latest PR commit
          fetch-depth: 0
          submodules: false

      - name: Lint latest PR commit messages with commitlint
        uses: wagoid/commitlint-github-action@b948419dd99f3fd78a6548d48f94e3df7f6bf3ed #(v6.2.1)
        with:
          configFile: commitlint.config.mjs
          failOnWarnings: true
          commitDepth: 1
          helpURL: https://www.conventionalcommits.org
