name: "Maru Release"

permissions:
  actions: read
  contents: write
  packages: write
  pull-requests: write

on:
  workflow_dispatch:
    inputs:
      image_tag_suffix:
        description: 'Custom image tag suffix, i.e. docker image tag would be [semver]-[YYYYMMDD]-[commit]-[suffix], if not given, would be [semver]-[YYYYMMDD]-[commit]'
        required: false
        type: string
        default: ''
      release_tag_suffix:
        description: 'Custom release tag suffix (must need for non-main release), i.e. release tag would be releases/[component]/v[semver]-[suffix]'
        required: false
        type: string
        default: ''
      pre_release:
        description: 'Pre Release if checked; Draft release otherwise'
        required: false
        default: false
        type: boolean
  push: #TODO: to be removed
    branches:
      - ci/feat-maru-manual-and-milestone-release

concurrency:
  group: maru-release-${{ github.ref }}
  cancel-in-progress: false

jobs:
  component-release:
    uses: ./.github/workflows/reusable-component-release.yml
    with:
      component-name: maru
      folder-name: maru
      include-path: maru/**
      image_tag_suffix: ${{ inputs.image_tag_suffix }}
      release_tag_suffix: ${{ inputs.release_tag_suffix }}
      draft_release: ${{ !inputs.pre_release || false }} #TODO: default will be removed
      pre_release: ${{ inputs.pre_release || true }} #TODO: default will be removed
    secrets: inherit
