name: "Postman Release"

permissions:
  actions: read
  contents: write
  packages: write
  pull-requests: write

on:
  workflow_dispatch:
    inputs:
      image_tag_suffix:
        description: 'Custom image tag suffix, i.e. docker image tag would be [semver]-[YYYYMMDD]-[commit]-[suffix], if not given, would be [semver]-[YYYYMMDD]-[commit]'
        required: false
        type: string
        default: ''
      release_tag_suffix:
        description: 'Custom release tag suffix (must need for non-main release), i.e. release tag would be releases/[component]/v[semver]-[suffix]'
        required: false
        type: string
        default: ''
      pre_release:
        description: 'Pre Release if checked; Draft release otherwise'
        required: false
        type: boolean
        default: false

concurrency:
  group: postman-release-${{ github.ref }}
  cancel-in-progress: false

jobs:
  component-release:
    uses: ./.github/workflows/reusable-component-release.yml
    with:
      component-name: postman
      folder-name: postman
      include-path: postman/**
      image_tag_suffix: ${{ inputs.image_tag_suffix }}
      release_tag_suffix: ${{ inputs.release_tag_suffix }}
      draft_release: ${{ !inputs.pre_release }}
      pre_release: ${{ inputs.pre_release }}
    secrets: inherit
