name: "Reusable: Compute Component Docker Image Tag"

on:
  workflow_call:
    inputs:
      version-prefix:
        description: 'Semver version as the docker image tag prefix'
        required: true
        type: string
      image-tag-suffix:
        description: 'Custom image tag suffix, i.e. docker image tag would be [semver]-[YYYYMMDD]-[commit]-[suffix], if not given, would be [semver]-[YYYYMMDD]-[commit]'
        required: false
        type: string
        default: ''
    outputs:
      docker_tag:
        description: "Docker image tag base (without suffix)"
        value: ${{ jobs.compute-docker-image-tag.outputs.docker_tag }}
      docker_tag_with_suffix:
        description: "Docker image tag with suffix (same value as docker_tag if no suffix is given)"
        value: ${{ jobs.compute-docker-image-tag.outputs.docker_tag_with_suffix }}

jobs:
  compute-docker-image-tag:
    runs-on: gha-lfdt-lineth-ss-ubuntu-24-amd64-small
    name: Compute docker image tag
    outputs:
      docker_tag: ${{ steps.dockertag.outputs.dockertag }}
      docker_tag_with_suffix: ${{ steps.dockertag.outputs.dockertag_with_suffix }}
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ github.ref_name }}
          fetch-depth: 2   # need at least 2 commits so HEAD~1 resolves later would not fail on compute-version-tags

      - name: Compute version tags
        id: compute_version_tags
        uses: ./.github/actions/compute-version-tags

      - name: Compute docker tag
        id: dockertag
        uses: ./.github/actions/compute-docker-tag
        with:
          version_prefix: ${{ inputs.version-prefix }}
          image_tag_suffix: ${{ inputs.image-tag-suffix }}
          commit_tag: ${{ steps.compute_version_tags.outputs.commit_tag }}

