name: sdk-testing

on:
  pull_request:
    paths:
      - "sdk/**"
      - ".github/workflows/sdk-testing.yml"
      - ".nvmrc"
  push:
    branches:
      - main
    paths:
      - "sdk/**"
      - ".github/workflows/sdk-testing.yml"
      - ".nvmrc"

permissions:
  contents: read

concurrency:
  group: sdk-testing-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  build-and-test:
    runs-on: gha-runner-scale-set-ubuntu-22.04-amd64-small
    name: SDK Build, Test, Lint
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup nodejs environment
        uses: ./.github/actions/setup-nodejs
        with:
          pnpm-install-options: "--frozen-lockfile --prefer-offline"

      - name: Build sdk-core
        run: pnpm -F @consensys/linea-sdk-core run build

      - name: Test sdk-core
        run: pnpm -F @consensys/linea-sdk-core run test

      - name: Lint sdk-core
        run: pnpm -F @consensys/linea-sdk-core run lint

      - name: Build sdk-viem
        run: pnpm -F @consensys/linea-sdk-viem run build

      - name: Test sdk-viem
        run: pnpm -F @consensys/linea-sdk-viem run test

      - name: Lint sdk-viem
        run: pnpm -F @consensys/linea-sdk-viem run lint
