name: Export Security Report to CSV

permissions:
  contents: read
  actions: read
  security-events: read

on: workflow_dispatch
jobs:
  data_gathering:
    runs-on: gha-runner-scale-set-ubuntu-24-amd64-small
    steps:
      - name: CSV export
        uses: advanced-security/ghas-to-csv@8c2ad35efb234e8e1bd12efaced0f0609ad8afbb # v3
      - name: Upload CSV
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: ghas-data
          path: ${{ github.workspace }}/*.csv
          if-no-files-found: error
