(module blake2fmodexpdata)

(defconst
  INDEX_MAX_MODEXP_BASE     31
  INDEX_MAX_MODEXP_EXPONENT 31
  INDEX_MAX_MODEXP_MODULUS  31
  INDEX_MAX_MODEXP_RESULT   31
  INDEX_MAX_BLAKE_DATA      12
  INDEX_MAX_BLAKE_PARAMS    1
  INDEX_MAX_BLAKE_RESULT    3)

